### ISSUE TITLE
[META] Ensure JDK-21 (baseline) ecosystem readiness 

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#10334]
**Is your feature request related to a problem? Please describe.**
The JDK-21 is already out and becomes the next LTS release.

**Describe the solution you'd like**
We need to make sure the ecosystem is ready to be using JDK-21 at runtime as well as build time:
- [x] https://github.com/opensearch-project/opensearch-build/issues/4071
- [x] https://github.com/opensearch-project/OpenSearch/pull/10138
    >  New features include: initial support for JDK 21 only to compile, test, and run Gradle projects since Kotlin does not yet support JDK 21; 
- [x] https://github.com/opensearch-project/OpenSearch/issues/10591
- [x] https://github.com/opensearch-project/OpenSearch/pull/11035
- [x] https://github.com/opensearch-project/OpenSearch/pull/11003 
- [x] https://github.com/opensearch-project/OpenSearch/pull/11045

Plugins / clients / tools:
- [x] https://github.com/opensearch-project/opensearch-java/pull/705
   - [X] https://github.com/opensearch-project/opensearch-java/pull/707
- [x] https://github.com/opensearch-project/opensearch-sdk-java/pull/962
- [x] [security](https://github.com/opensearch-project/security)
  - [x] https://github.com/opensearch-project/security/pull/3641
  - [x] https://github.com/opensearch-project/security/pull/3638
  - [x] https://github.com/opensearch-project/security/pull/3715
  - [x] https://github.com/opensearch-project/security/pull/3640
- [x] [custom-codecs](https://github.com/opensearch-project/custom-codecs)
  - [x] https://github.com/opensearch-project/custom-codecs/pull/76
  - [x] https://github.com/opensearch-project/custom-codecs/pull/78
- [x] [custom-codecs](https://github.com/opensearch-project/custom-codecs)
- [x] [data-prepper](https://github.com/opensearch-project/data-prepper)
  - [x] https://github.com/opensearch-project/data-prepper/pull/3622
- [X] https://github.com/opensearch-project/neural-search
  - [X] https://github.com/opensearch-project/neural-search/pull/500
- [x] https://github.com/opensearch-project/ml-commons
  - [x] https://github.com/opensearch-project/ml-commons/pull/1612
  - [x] https://github.com/opensearch-project/ml-commons/pull/1698
  - [x] https://github.com/opensearch-project/ml-commons/pull/1697
  - [x] https://github.com/opensearch-project/ml-commons/pull/1868
- [x] https://github.com/opensearch-project/sql
  - [x] https://github.com/opensearch-project/sql/pull/2433
  - [x] https://github.com/opensearch-project/sql/pull/2480
  - [x] https://github.com/opensearch-project/sql/pull/2481
- [x] https://github.com/opensearch-project/security-analytics
  - [x] https://github.com/opensearch-project/security-analytics/pull/720
- [x] https://github.com/opensearch-project/k-NN
  - [x] https://github.com/opensearch-project/k-NN/pull/1289
  - [x] https://github.com/opensearch-project/k-NN/pull/1288
- [X] https://github.com/opensearch-project/geospatial
  - [X]  https://github.com/opensearch-project/geospatial/pull/599
  - [X] https://github.com/opensearch-project/geospatial/pull/596
- [x] https://github.com/opensearch-project/index-management
  - [x] https://github.com/opensearch-project/index-management/pull/1069
  - [x] https://github.com/opensearch-project/index-management/pull/1070
- [x] https://github.com/opensearch-project/anomaly-detection
  - [x] https://github.com/opensearch-project/anomaly-detection/pull/1131
  - [x] https://github.com/opensearch-project/anomaly-detection/pull/1132
- [x] https://github.com/opensearch-project/notifications
  - [X] https://github.com/opensearch-project/notifications/pull/824
  - [x] https://github.com/opensearch-project/notifications/pull/825
- [x] https://github.com/opensearch-project/opensearch-hadoop
  - [x] https://github.com/opensearch-project/opensearch-hadoop/pull/377
- [x] https://github.com/opensearch-project/search-processor
  - [x] https://github.com/opensearch-project/search-processor/pull/213
- [x] https://github.com/opensearch-project/alerting
  - [x] https://github.com/opensearch-project/alerting/pull/1369
  - [x] https://github.com/opensearch-project/alerting/pull/1371
- [x] https://github.com/opensearch-project/job-scheduler
  - [X] https://github.com/opensearch-project/job-scheduler/pull/542
  - [x] https://github.com/opensearch-project/job-scheduler/pull/545
  - [x] https://github.com/opensearch-project/job-scheduler/pull/546
- [x] https://github.com/opensearch-project/asynchronous-search
  - [x] https://github.com/opensearch-project/asynchronous-search/pull/516
  - [x] https://github.com/opensearch-project/asynchronous-search/pull/519
  - [x] https://github.com/opensearch-project/asynchronous-search/pull/522
- [x] https://github.com/opensearch-project/common-utils
  - [x] https://github.com/opensearch-project/common-utils/pull/560
  - [x] https://github.com/opensearch-project/common-utils/pull/561
  - [x] https://github.com/opensearch-project/common-utils/pull/564
  - [x] https://github.com/opensearch-project/common-utils/pull/563
- [x] https://github.com/opensearch-project/performance-analyzer-commons
  - [x]  https://github.com/opensearch-project/performance-analyzer-commons/pull/72
- [x] https://github.com/opensearch-project/opensearch-learning-to-rank-base
  - [x] https://github.com/opensearch-project/opensearch-learning-to-rank-base/pull/28
- [x] https://github.com/opensearch-project/performance-analyzer
  - [x] https://github.com/opensearch-project/performance-analyzer/pull/617
  - [x] https://github.com/opensearch-project/performance-analyzer/pull/619
  - [x] https://github.com/opensearch-project/performance-analyzer/pull/618
- [x] https://github.com/opensearch-project/performance-analyzer-rca
  - [x] https://github.com/opensearch-project/performance-analyzer-rca/pull/528
  - [x] https://github.com/opensearch-project/performance-analyzer-rca/pull/535
  - [x] https://github.com/opensearch-project/performance-analyzer-rca/pull/533
- [x] https://github.com/opensearch-project/opensearch-oci-object-storage
  - [x] https://github.com/opensearch-project/opensearch-oci-object-storage/pull/58
- [x] https://github.com/opensearch-project/sql-jdbc
  - [x] https://github.com/opensearch-project/sql-jdbc/pull/120
- [x] https://github.com/opensearch-project/flow-framework/
  - [x] https://github.com/opensearch-project/flow-framework/pull/227
  - [x] https://github.com/opensearch-project/flow-framework/pull/247
- [x] https://github.com/opensearch-project/opensearch-plugin-template-java/
  - [x] https://github.com/opensearch-project/opensearch-plugin-template-java/pull/63
- [x] https://github.com/opensearch-project/observability
  - [x] https://github.com/opensearch-project/observability/pull/1777
  - [x] https://github.com/opensearch-project/observability/pull/1779
- [x] https://github.com/opensearch-project/reporting
  - [X] https://github.com/opensearch-project/reporting/pull/941
  - [x] https://github.com/opensearch-project/reporting/pull/942

There are some foreseeing delays unfortunately with Eclipse Temurin JDK-21 distribution:
- https://adoptium.net/blog/2023/09/temurin21-delay/
- https://github.com/adoptium/temurin/issues/8

**Describe alternatives you've considered**

**Additional context**
- https://github.com/opensearch-project/OpenSearch/issues/9423

**Comment by heemin32** [comment]
Can't wait to see this to be completed.

**Comment by reta** [comment]
> Can't wait to see this to be completed.

Thanks @heemin32 , moving forward as things become available :-)

**Comment by reta** [comment]
> Hey @reta, for some plugins, I see current jdk matrix is 11/17/20 or 11/17 - I assume we can drop testing of 20 for 21, but keep 11 and 17, correct?

Thanks @jmazanec15 , that is correct, I will be going through all plugins to get them ready for JDK-21

**Comment by jmazanec15** [comment]
Hey @reta knn CI upgrade has been completed for main/2.x. I cant check off the box in the issue, but wanted to update.

**Comment by reta** [comment]
> Hey @reta knn CI upgrade has been completed for main/2.x. I cant check off the box in the issue, but wanted to update.

Thanks a lot @jmazanec15 , I've added both pull requests, thank you!

**Comment by reta** [comment]
@prudhvigodithi FYI, since your are taking some updates :)

**Comment by prudhvigodithi** [comment]
Thanks @reta should we go with gradle 8.5? ([released an hour back](https://github.com/gradle/gradle/releases/tag/v8.5.0)) as I noticed for jdk21 8.5 is in the [compatibility version](https://docs.gradle.org/current/userguide/compatibility.html).

**Comment by Pallavi-AWS** [comment]
@reta, @bbarani @prudhvigodithi - Are we impacted with the JDK bug in https://bugs.openjdk.org/browse/JDK-8323659?

**Comment by reta** [comment]
> @reta, @bbarani @prudhvigodithi - Are we impacted with the JDK bug in https://bugs.openjdk.org/browse/JDK-8323659?

@Pallavi-AWS not at the moment, the bug was introduced in 21.0.2 / 22 (which we haven't updated yet, see please https://github.com/opensearch-project/OpenSearch/issues/11906), we'll watch for any regressions once 21.0.2 bits become available (Eclipse Temurin), thank you for heads up

**Comment by prudhvigodithi** [comment]
Thanks @reta I have just updated the title to reflect `21.0.1` and apart from core the build/assemble I see its using 21.0.1 as well https://github.com/opensearch-project/opensearch-build/issues/4071.
@Pallavi-AWS @bbarani @peterzhuamazon

**Comment by joshuali925** [comment]
this meta issue is missing two plugins
https://github.com/opensearch-project/observability
https://github.com/opensearch-project/reporting

I created https://github.com/opensearch-project/observability/pull/1778 for observability, will do for reporting, but currently CI on windows is failing

**Comment by reta** [comment]
@Pallavi-AWS this issues has no reference to the JDK version, this is just for tracking JDK-21 baseline

**Comment by reta** [comment]
> I created [opensearch-project/observability#1778](https://github.com/opensearch-project/observability/pull/1778) for observability, will do for reporting, but currently CI on windows is failing

Thanks @joshuali925 , updated the description

**Comment by joshuali925** [comment]
any other plugin running into `javax.management.InstanceNotFoundException: org.jacoco:type=Runtime` ([link](https://github.com/opensearch-project/observability/actions/runs/7589416330/job/20674000733?pr=1778#step:4:624)) on windows after upgrading gradle to 8.5?

i'm having trouble with debugger on windows, but i pulled notifications `main` on windows and got the same error using `./gradlew build`

**Comment by reta** [comment]
@joshuali925 replied you https://github.com/opensearch-project/observability/pull/1778/files#r1460155617
