### ISSUE TITLE
[META] Remote Cluster State Issues (Phase - 2)

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#10523]
**Is your feature request related to a problem? Please describe.**
 Issues listed under this meta issue are related Remote Cluster State feature for Phase 2. As part of Phase 2, we will add support to backup and restore global metadata to and from remote store.

**Describe the solution you'd like**
https://github.com/opensearch-project/OpenSearch/issues/9143

**Tasks**

***OpenSearch 2.10 Release***

- [ ] https://github.com/opensearch-project/OpenSearch/issues/10525
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10526
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10527
- [ ] https://github.com/opensearch-project/OpenSearch/issues/9816
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10662
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10658
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10841
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10697
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10691
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10888
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10586
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10555
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10071
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10911
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10809
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10773
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10688
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10687
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10645
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10978
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10683
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10682
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10686
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10890
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10990
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10913
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10905
- [ ] <adjust remote retries to have a shorter back-off/more attempts as compared to translog/segments>

**Additional context**
Previous Release - https://github.com/opensearch-project/OpenSearch/issues/9344

**Comment by kiranprakash154** [comment]
Hi, are we on track for this to be released in 2.12 ?

**Comment by shwetathareja** [comment]
@soosinha can you update this Meta issue with latest status?

**Comment by soosinha** [comment]
The changes planned for 2.12 have been released. The major changes are upload of global metadata on cluster state publication and download of global metadata during cluster-manager node bootstrap. The timeout of metadata upload has been added as dynamic settings. Cluster UUID chaining logic has been modified according to global metadata. Cluster state upload stats having added under discovery metric in node stats API. Cluster state uploads are now being performed from a separate threadpool.
Resolving this meta issue now. The pending issues will be tracked individually
