### ISSUE TITLE
[META] Generic Query Insights Framework and Top N Queries

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/OpenSearch#11522]
**Is your feature request related to a problem? Please describe.**
Meta issue to keep track of necessary tasks for the Top N Queries feature. Tasks for the Generic Query Insights Framework are also tracked here since we need them for the Top N Queries.

**Describe the solution you'd like**
related RFC: 
- https://github.com/opensearch-project/OpenSearch/issues/11186
- https://github.com/opensearch-project/OpenSearch/issues/11429

Dashboard
- https://github.com/opensearch-project/OpenSearch-Dashboards/issues/5571

### Related Issues
- [ ] https://github.com/opensearch-project/OpenSearch/issues/11520
- [ ] https://github.com/opensearch-project/OpenSearch/issues/11295
- [ ] https://github.com/opensearch-project/OpenSearch/issues/11296
- [ ] https://github.com/opensearch-project/OpenSearch/issues/11431

### Tasks

- [ ] https://github.com/opensearch-project/OpenSearch/pull/11506

**Additional context**

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/dbwiddis) [3](https://github.com/andrross) [4](https://github.com/reta)]
@ansjcy Thanks for filing this issue
