### ISSUE TITLE
[META] Schema on Reads

### ISSUE THREAD

**Issue by qreshi** [opensearch-project/OpenSearch#12281]
### Please describe the end goal of this project

"Schema on reads" is a mechanism where query result data can be defined at runtime of the query. This is useful for users who may not be aware of the structure of the data and want to explore its usage before choosing what and how to index it. More simply, this feature allows users to have additional attributes to query upon post-ingest.

### Supporting References

The RFC for this feature request can be found here https://github.com/opensearch-project/OpenSearch/issues/1133

### Issues

- [ ] Add a DerivedFieldMapper class
- [ ] Update IndicesModule and MapperService to recognize DerivedFieldMapper and be able to parse the mappings content
- [ ] Create a QueryBuilder for executing queries with derived fields
- [ ] Aggregation support
- [ ] Scoring support
- [ ] Sorting support

I will update this section with created issues with more details. For the time being I wanted to create the META issue for tracking.

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta/) [3](https://github.com/andrross) [4](https://github.com/dbwiddis) [5](https://github.com/sohami) [6](https://github.com/lukas-vlcek) [7](https://github.com/kotwanikunal) [8](https://github.com/Bukhtawar)]
@qreshi Thanks for filing, it would be useful to to create subtasks with additional details for some of those items, looking forward to seeing progress here.

**Comment by rishabhmaurya** [comment]
List of all tasks associated - 

- [x] Derived fields building blocks: DerivedFieldQuery, DerivedFieldScript and DerivedFieldValueFetcher - https://github.com/opensearch-project/OpenSearch/pull/12746
- [x] Derived fields supported field types implementation -` boolean`, `keyword`, `long`, `double`, `ip`, `geo_point`, `date` - https://github.com/opensearch-project/OpenSearch/pull/12808
- [x] Derived fields Mapper definition and integration through index mapping way - https://github.com/opensearch-project/OpenSearch/pull/12569
- [x]  Support for adding multiple values from derived field scripts - https://github.com/opensearch-project/OpenSearch/pull/12837
- [x] Support defining derived field through search requests and rest client. Also adds support for derived fields in fetch and highlight phase  - https://github.com/opensearch-project/OpenSearch/pull/12850
- [ ] Support for object type in derived fields - https://github.com/opensearch-project/OpenSearch/issues/13143
- [ ] Documentation - https://github.com/opensearch-project/documentation-website/issues/6943

**Comment by jayaddison** [comment]
I'd like to be able to `sort` using derived fields in OpenSearch, and began attempting to prototype an implementation locally.  It seems that determining the datatype of each derived field at query runtime (that will be required for subsequent comparator operations, I believe) is a challenge.

**Comment by rishabhmaurya** [comment]
@jayaddison could you point to your changes?

> It seems that determining the datatype of each derived field at query runtime (that will be required for subsequent comparator operations, I believe) is a challenge.

We do that already when derived fields are defined in query. Check https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/mapper/DefaultDerivedFieldResolver.java#L99

**Comment by jayaddison** [comment]
Thanks for taking an interest @rishabhmaurya - I should mention that I've hardly made any progress on it, and it's been many years since I coded in Java.  Even so, the commit/line where I'd run into this is:

https://github.com/openculinary/OpenSearch/blob/31a65207600568630dacd0cf66649ba9e3487c39/server/src/test/java/org/opensearch/search/query/QueryPhaseTests.java#L775

My plan is to develop test case(s) to expose where the gap in sort functionality exists, and then to get those to pass (initially perhaps with a naive solution, and then to optimize).

**Comment by avinashrad** [comment]
@rishabhmaurya Any open tickets on when the sort functionality will be available for derived fields? We are building a feature where we derive some results and would like to use it for both sort and filtering.

**Comment by jayaddison** [comment]
Self-quoting:
> My plan is to develop test case(s) to expose where the gap in sort functionality exists, and then to get those to pass (initially perhaps with a naive solution, and then to optimize).

Update: I haven't made much additional progress on implementing this, and have to admit that I don't think I'm likely to soon (it may have been overambitious for me -- and/or I did not make time to focus on it).
