### ISSUE TITLE
[RFC] View feature wishlist

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#12424]
### Description
Views helping sysadmins define data that query authors make requests against.  There are many possible features that have been gleamed from discussion in the original views RFC [1].  This RFC is looking to collect feedback and allow for discussion around the direction in this space.

_Why isn't this a meta issue?_  For views, the implementation and delivery is being pushed more organically, there is no set release target.  After critical mass has been achieved views will be included in the next scheduled minor release of OpenSearch.

### Unorder proposed features
- [ ] Use views as part of Index Pattern in OpenSearch Dashboards
  - In OpenSearch Dashboards an component called index pattern is required to associate visualizations with data.  This creates a gap in the backend data model vs the visualization front end.  Making a single backend supported object would simplify the user model and 
- [ ] Document Security
  -  While the security plugin supports document level security and field level security, Views could serve as a focal point for this configuration rather than roles.  
  - _Related Issues_
    - https://github.com/opensearch-project/security/issues/2834
    - https://github.com/opensearch-project/security/issues/3773
    - https://github.com/opensearch-project/security/issues/3963
    - https://github.com/opensearch-project/security/issues/3274
- [ ] Support view resource permission
  - Expand OpenSearch to allow for granting permission to individual views as is done with indices.  This would enable permission grants for other non-index objects such as resources in plugins.
  - _Related Issues_
    - https://github.com/opensearch-project/security/issues/3890 
- [ ] Pipelines integration
  - A suite of composable processers that transform search request and search responses is expanded to support views.
  - _Related Issues_
    - https://github.com/opensearch-project/OpenSearch/issues/11053
    - https://github.com/opensearch-project/OpenSearch/issues/10938
    - https://github.com/opensearch-project/OpenSearch/issues/11188
    - https://github.com/opensearch-project/OpenSearch/issues/7512
- [ ] Constraint cluster resources
  - OpenSearch systems have limited CPU/Memory and cluster operators could use views as a single place to declare cluster resource limits between different query workloads
  - _Related Issues_
    - https://github.com/opensearch-project/OpenSearch/issues/11173
    
### Next steps
As entries gain a stakeholder to implement them they will be broken out into their own items and referenced.  

#### Want to add a wish list entry or deliver one of these feature areas?
Please tag @peternied to make updates to this descriptions.

### Related items:
- [1] Views RFC https://github.com/opensearch-project/OpenSearch/issues/6181
- [2] Views basic implementation https://github.com/opensearch-project/OpenSearch/pull/11957
