### ISSUE TITLE
[META] Optimised prefix pattern per shard for remote store data and metadata files for higher throughput

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#12589]
### Please describe the end goal of this project

Proposing a path structure that tries to distribute all shards deterministically over multiple prefixes. The end goal of this initiative is to reduce the throttling or rate limiting done by cloud providers. The organic recommendation in such cases by the same cloud providers is to distribute the load to them over multiple prefixes. In this meta, we will breakdown the issue to smaller issues that we would be working on to complete this feature request.

### Supporting References

Feature request - https://github.com/opensearch-project/OpenSearch/issues/12567

### PRs

 - [x] https://github.com/opensearch-project/OpenSearch/pull/12607
 - [x] https://github.com/opensearch-project/OpenSearch/pull/12753
 - [x] https://github.com/opensearch-project/OpenSearch/pull/12822
 - [x] https://github.com/opensearch-project/OpenSearch/pull/12920
 - [x] https://github.com/opensearch-project/OpenSearch/pull/12986
 - [x] https://github.com/opensearch-project/OpenSearch/pull/12988
 - [x] https://github.com/opensearch-project/OpenSearch/pull/13103
 - [x] https://github.com/opensearch-project/OpenSearch/pull/13150
 - [x] https://github.com/opensearch-project/OpenSearch/pull/13251
 - [x] https://github.com/opensearch-project/OpenSearch/pull/13225
 - [x] https://github.com/opensearch-project/OpenSearch/pull/13150
 - [x] https://github.com/opensearch-project/OpenSearch/pull/13386
 - [ ] & more to follow

I will keep creating issue as and when I am starting on the pending sub tasks.

### Related component

Storage:Performance

**Comment by ashking94** [comment]
Marking this meta closed since all items have been completed.
