### ISSUE TITLE
[META]  Remote Store Migration Support

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#12718]
### Please describe the end goal of this project

To support migration of existing Doc Rep cluster to/from Remote backed cluster which has Remote backed Segment , and Translog enabled.

### Supporting References

https://github.com/opensearch-project/OpenSearch/issues/12246

### Issues

- [x] Mixed Mode Support https://github.com/opensearch-project/OpenSearch/issues/12245
- [x] Primary Shard Relocation to Remote node https://github.com/opensearch-project/OpenSearch/issues/12689
- [x] Local Recovery - Seeding  https://github.com/opensearch-project/OpenSearch/pull/12922 
- [x] Add allocation decider for mixed cluster https://github.com/opensearch-project/OpenSearch/issues/12518 
- [x] Dual Replication - Primary changes
- [x] Set index settings for new indices/snapshot restores appropriately in mixed mode  https://github.com/opensearch-project/OpenSearch/issues/12852 
- [x] Shard Allocation side changes to prefer primary promotion based on direction https://github.com/opensearch-project/OpenSearch/pull/13136 
- [x]  Complete migration of an index to remote store backed by updating index settings https://github.com/opensearch-project/OpenSearch/pull/13316 
- [x] Reject Resize index requests while remote store migration is undergoing - https://github.com/opensearch-project/OpenSearch/pull/12686 
- [x] Replica Shard Relocation to Remote node
- [x] Failover handling  - DocRep Shard Promotion
- [x] Failover handling  - Remote Shard Promotion
- [x]  https://github.com/opensearch-project/cross-cluster-replication/issues/1360
- [x] https://github.com/opensearch-project/OpenSearch/issues/12961
- [x] https://github.com/opensearch-project/OpenSearch/issues/13101
- [x] https://github.com/opensearch-project/OpenSearch/issues/13102
- [ ] https://github.com/opensearch-project/OpenSearch/issues/8610
- [x] https://github.com/opensearch-project/OpenSearch/pull/13159
- [x] https://github.com/opensearch-project/OpenSearch/issues/13302
- [x] https://github.com/opensearch-project/OpenSearch/pull/13322
- [ ] Remove experimental flag for remote store direction . 

### Related component

Storage:Remote

**Comment by gbbafna** [comment]
[Storage Triage - attendees [1](https://github.com/reta) [2](https://github.com/lukas-vlcek) [3](https://github.com/akolarkunnu) [4](https://github.com/gbbafna) [5](https://github.com/linuxpi) [6](https://github.com/ltaragi) [7](https://github.com/sachinpkale) [8](https://github.com/astute-decipher) [9](https://github.com/BhumikaSaini-Amazon) 

Closing as this is already GA
