### ISSUE TITLE
[META] Translog Optimisation: Upload .ckp file data as object metadata of .tlog file

### ISSUE THREAD

**Issue by skumawat2025** [opensearch-project/OpenSearch#13091]
### Please describe the end goal of this project

Proposing a optimisation for translog files uploads. In this optimisation we purpose a solution to store checkpoint file data as object metadata/header of translog.tlog file for supported cloud providers. The end goal of this is to reduce the rate or number of calls to remote store during translog uploads.  In this meta, we will breakdown the issue to smaller issues that we would be working on to complete this feature request.

### Supporting References

Feature request - https://github.com/opensearch-project/OpenSearch/issues/13022

### Issues

- [x] https://github.com/opensearch-project/OpenSearch/issues/13092
- [x] https://github.com/opensearch-project/OpenSearch/issues/13093
- [x] https://github.com/opensearch-project/OpenSearch/issues/13094

### Related component

Storage:Performance
