### ISSUE TITLE
[META] The org.opensearch.search.aggregations.bucket.nested.NestedAggregatorTests.* test cases are flaky

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#13106]
### Please describe the end goal of this project

The org.opensearch.search.aggregations.bucket.nested.NestedAggregatorTests.* test cases are flaky

### Supporting References

Other tests:
 - org.opensearch.search.aggregations.bucket.nested.NestedAggregatorTests.testPreGetChildLeafCollectors 

Failing builds:
 - https://build.ci.opensearch.org/job/gradle-check/36609/testReport/junit/org.opensearch.search.aggregations.bucket.nested/NestedAggregatorTests/testPreGetChildLeafCollectors/

### Issues

- [ ] https://github.com/opensearch-project/OpenSearch/issues/12595
- [ ] https://github.com/opensearch-project/OpenSearch/issues/12306
- [ ] https://github.com/opensearch-project/OpenSearch/issues/12239

### Related component

Search

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/vikasvb90
) [4](https://github.com/andrross
) [5](https://github.com/lukas-vlcek/
) [6](https://github.com/srikanthpadakanti)]
@reta Thanks for filing this issue to track these flaky tests

**Comment by jed326** [comment]
Potentially related: 
- https://github.com/opensearch-project/OpenSearch/issues/13303

**Comment by kkewwei** [comment]
> Potentially related:
> 
> * [[BUG] The aggs result of NestedAggregator with sub NestedAggregator may be not accurately #13303](https://github.com/opensearch-project/OpenSearch/issues/13303)

@jed326, from the exception stack, it seems hit the #13303, but I have not reproduced the flaky test.

**Comment by reta** [comment]
Closing in favour https://github.com/opensearch-project/OpenSearch/issues/14322
