### ISSUE TITLE
[META] Writable Warm Index

### ISSUE THREAD

**Issue by rayshrey** [opensearch-project/OpenSearch#13149]
## Please describe the end goal of this project

This meta task will keep track of all the ongoing and completed development work related to Writable Warm Index.
This includes the composite directory and file cache integration, hot/warm migration support and performance optimizations.

## Supporting References

Writable Warm RFC - https://github.com/opensearch-project/OpenSearch/issues/12809

### Composite Directory:

- [x] #12781
- [x] #13647
- [x] #21101

### FileCache Improvements:

- [x] #13648
- [x] #17479 
- [x] #17526

### Hot/Warm Migration
To be followed up in separate META issue #21016

---

Follow-up AIs from the above issues:

- [ ] Optimize readInput for Block files of RemoteDirectory to avoid loading whole 8MB chunk in memory
- [ ] Explore and verify impact of temp files in directory as they are not tracked in FileCache
- [ ] Add new role for Writable Warm for FileCache initialization logic (instead of being dependent on Feature Flag)
- [ ] Refactor OnDemandSnapshotIndexInput and FileInfo to more generic names as they are now being used by Composite directory as well which is not Snapshot related.
- [ ] Optimize and make listAll() of RemoteSegmentStoredircetory more robust (fix NPE on empty metadata and improve complexity)

Backlogs:

- [ ] Use String as key of FileCache instead of Path to avoid having hard dependency of local directory being FSDirectory

### Related component

Storage:Remote
