### ISSUE TITLE
[META] Multi-tenancy support in OpenSearch

### ISSUE THREAD

**Issue by ansjcy** [opensearch-project/OpenSearch#13516]
### Please describe the end goal of this project

Introduce and enable multi-tenancy as a first class citizen in OpenSearch by associating traffic with specific users or workloads. This will allow better categorization, management, troubleshooting and analysis of subsets of traffic hitting an OpenSearch cluster.

We can start from the search use cases and build a generic framework/solution, which can be extend it to other workflow like indexing.

### Related RFC
- [ ] https://github.com/opensearch-project/OpenSearch/issues/13341 

### MVP version:
- [ ] POC: https://github.com/opensearch-project/OpenSearch/pull/13374
- [ ] Add the ability to attach tenancy labels in a SearchRequest
- [ ] Add rule-based labeling service

### Related component

Search

**Comment by andrross** [comment]
[Triage - attendees [1](https://github.com/jed326) [2](https://github.com/dbwiddis) [3](https://github.com/reta/) [4](https://github.com/vikasvb90/)]
@ansjcy Thanks for filing. Looking forward to seeing progress here.

**Comment by kaushalmahi12** [comment]
Hi @ansjcy thanks for opening this issue. I have an open PR for this for QSB use case(search workloads): https://github.com/opensearch-project/OpenSearch/pull/13713

**Comment by getsaurabh02** [comment]
this looks like a good plan. Thanks @ansjcy
