### ISSUE TITLE
[META] User Behavior Insights (UBI) Enhancements

### ISSUE THREAD

**Issue by jzonthemtn** [opensearch-project/OpenSearch#13605]
### Please describe the end goal of this project

There are several UBI enhancements that are desired. The issues listed below are to provide more flexibility to UBI and make it more user-friendly while improving its ability to meet its goals.

### Supporting References

The [UBI RFC](https://github.com/opensearch-project/OpenSearch/issues/12084) and #13545 are the initial UBI commits.

### Issues

- [ ] #13580 - Make the `query_id` optional
- [ ] #13581 - Improve how UBI indexes are created
- [ ] #13582 - Support sending queries to Data Prepper
- [ ] #13604 - Allow UBI to accept custom attributes in a search request

### Related component

Search
