### ISSUE TITLE
[META][2.15] Cluster State Publication using Remote State 

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#13683]
### Please describe the end goal of this project

For remote store enabled clusters, the cluster state is being published to a remote repository. This can be used to publish the cluster state to all nodes in the cluster. Instead of sending the cluster state object over the transport layer, the cluster manager node can just send the term and version of the cluster state over the transport layer which can then be used to download the corresponding cluster state by all the nodes directly from the remote store.

This meta issue includes the tasks required for experiemental release in 2.15.

### Supporting References

RFC: https://github.com/opensearch-project/OpenSearch/issues/13257

### Issues
- [x] https://github.com/opensearch-project/OpenSearch/issues/13730
- [x] https://github.com/opensearch-project/OpenSearch/issues/13791
- [x] https://github.com/opensearch-project/OpenSearch/pull/13834
- [x] https://github.com/opensearch-project/OpenSearch/pull/13836
- [x] https://github.com/opensearch-project/OpenSearch/pull/14095
- [x] https://github.com/opensearch-project/OpenSearch/pull/14006
- [x] https://github.com/opensearch-project/OpenSearch/issues/13682
- [x] https://github.com/opensearch-project/OpenSearch/issues/13728
- [x] https://github.com/opensearch-project/OpenSearch/issues/13729

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/vikasvb90/) [3](https://github.com/scrawfor99) [4](https://github.com/andrross) [5](https://github.com/reta/) [6](https://github.com/dbwiddis) [7](https://github.com/cwperks) [8](https://github.com/lukas-vlcek/)]
@soosinha Thanks for creating this issue

**Comment by lukas-vlcek** [comment]
Is #13576 already part of this effort? I just want to make sure it is linked if it is related.

**Comment by shiv0408** [comment]
@lukas-vlcek Yes, that PR is required for this. Created a new issue #13691 as a task for this. 
@soosinha can you please help in adding this issue to the task list of this Meta issue.
