### ISSUE TITLE
[META] Star Tree Index issue list 

### ISSUE THREAD

**Issue by bharath-techie** [opensearch-project/OpenSearch#13875]
### Please describe the end goal of this project

Implement star tree index to precompute aggregations which helps to enforce upper bound on the aggregation queries ensuring predictable latency and resource usage. It is also storage space efficient and configurable.

### Supporting References

- [ ] https://github.com/opensearch-project/OpenSearch/issues/12498

### Config / codec changes

Covers user/client experience to create star tree indices via specifying star tree config and custom codec changes to support star tree index in experimental mode.

- [ ] https://github.com/opensearch-project/OpenSearch/issues/14386 - Star tree index config and settings
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14387 - Star tree index codec changes

### Flush changes

- [ ] https://github.com/opensearch-project/OpenSearch/issues/14116 - Basic changes for interfaces to build star tree during flush
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14624 - Support min / max aggregations as part of star tree

### File format changes
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14837
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15279
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15296

### Merge / Off heap changes

- [ ] https://github.com/opensearch-project/OpenSearch/issues/14626 - Star tree merge changes - Segment merge changes as part of indexing flow
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14815 - Off heap changes - Build star tree index by performing sort and aggregations off heap as on-heap build is quite heavy

### Search changes 
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15257

###  Other 2.17 changes
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15265
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15231
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15443

### Testing / benchmarks / Bugs
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14813
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15275
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15097
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15467
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15288
- [ ] https://github.com/opensearch-project/OpenSearch/issues/16218
- [ ] https://github.com/opensearch-project/OpenSearch/issues/15491
-----
Milestone 2 - Support for keyword fields to support terms / multi-terms aggregations
- [ ] https://github.com/opensearch-project/OpenSearch/issues/16232
- [ ] https://github.com/opensearch-project/OpenSearch/issues/16642

Milestone 3 - Guardrails , handling cases such as high cardinality etc.

Milestone 4 and later is yet to be scoped - But we will have other cases such as deleted docs handling, metrics extension, query/indexing optimizations etc.

### Feature requests / Backlog

- https://github.com/opensearch-project/OpenSearch/issues/15266
- https://github.com/opensearch-project/OpenSearch/issues/14657
- https://github.com/opensearch-project/OpenSearch/issues/15231

### Related component

Other
