### ISSUE TITLE
[META] Set OpenSearch 3.0.0 baseline JDK version to JDK-21

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#14011]
### Please describe the end goal of this project

Currently, the 3.0.0 baseline JDK version is set to JDK-11. The Apache Lucene 10 is going to require JDK-21 and it would make sense to align the OpenSearch JDK baseline requirements with that. 

In order to make the migration as painless as possible, the suggestion is to start from dependent components (plugins, clients, extensions, libraries) and finish up with core, for the following reasons:
 - if we change core to JDK-21 baseline (bytecode), it will break all and every dependent component
 - however, because we always build core with JDK-21 (and bundle it in as well with JDK-21), there won't be any issues dealing the dependent components that are on JDK-21 baseline

### Supporting References

Please see https://github.com/opensearch-project/OpenSearch/issues/10745

### Issues

- [x] #14010 
- [x] https://github.com/opensearch-project/common-utils/issues/668
- [x] https://github.com/opensearch-project/security/issues/4407
- [x] https://github.com/opensearch-project/job-scheduler/issues/636
- [x] https://github.com/opensearch-project/reporting/issues/1002
- [x] https://github.com/opensearch-project/observability/issues/1830
- [x] https://github.com/opensearch-project/sql/issues/2713
- [x] https://github.com/opensearch-project/security-analytics/issues/1056
- [x] https://github.com/opensearch-project/data-prepper/issues/4605
- [x] https://github.com/opensearch-project/anomaly-detection/issues/1223
- [x] https://github.com/opensearch-project/k-NN/issues/1729
- [x] https://github.com/opensearch-project/opensearch-plugin-template-java/issues/70
- [x] https://github.com/opensearch-project/alerting/issues/1565
- [x] https://github.com/opensearch-project/performance-analyzer-commons/issues/75
- [x] https://github.com/opensearch-project/ml-commons/issues/2503
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/1393
- [x] https://github.com/opensearch-project/neural-search/issues/775
- [x] https://github.com/opensearch-project/flow-framework/issues/729
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/998
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/555
- [x] https://github.com/opensearch-project/opensearch-hadoop/issues/472
- [x] https://github.com/opensearch-project/search-processor/issues/225
- [x] https://github.com/opensearch-project/custom-codecs/issues/153
- [x] https://github.com/opensearch-project/asynchronous-search/issues/581
- [x] https://github.com/opensearch-project/opensearch-learning-to-rank-base/issues/36
- [x] https://github.com/opensearch-project/geospatial/issues/659
- [x] https://github.com/opensearch-project/opensearch-oci-object-storage/issues/60
- [x] https://github.com/opensearch-project/notifications/issues/924
- [x] https://github.com/opensearch-project/index-management/issues/1181
- [x] https://github.com/opensearch-project/performance-analyzer/issues/659
- [x] https://github.com/opensearch-project/query-insights/issues/134

### Related component

Build

**Comment by reta** [comment]
@msfroh @andrross @dblock @getsaurabh02 fyi folks :) kicking off the campaign ...

**Comment by dbwiddis** [comment]
@reta Quick question on this.

In response to this campaign, I updated our compatibility from JDK 11 to JDK 21 like this:
```groovy
java {
    targetCompatibility = JavaVersion.VERSION_21
    sourceCompatibility = JavaVersion.VERSION_21
}
```

Our normal development flow is to merge to `main` and backport to `2.x`, which still supports earlier JDK's.   I can see the potential for someone introducing code from a JDK between 12 and 20 (logically, 17) such as text blocks, switch expressions, records, and my new favorite stream operator, `toList()`.   They'd pass muster on all our `main` branch CI but fail the backport and require substituting alternate code.   Currently we limit this just to a very few differences to keep backporting simple.

I'm curious what the best approach here is.  Can we keep `targetCompatibility` as 21 to address this campaign while still requiring `sourceCompatibility` of 11 to make sure backporting goes smoothly and doesn't diverge too much?    

Or if we're keeping both, it seems this style may be more broadly applicable and recommended here. Thoughts?
```groovy
tasks.withType(JavaCompile) {
    options.release.set(21)
}
```

**Comment by andrross** [comment]
@dbwiddis See some more discussion here: https://github.com/opensearch-project/custom-codecs/pull/154#discussion_r1629998769

The risk is that some new language features will be exposed by a library using JDK21 as a baseline (i.e. Lucene) and that won't work smoothly if your source compatibility is lower than that. I'm not totally sure what those risks look like in practice though.

**Comment by dbwiddis** [comment]
> The risk is that some new language features will be exposed by a library using JDK21 as a baseline (i.e. Lucene) and that won't work smoothly if your source compatibility is lower than that. I'm not totally sure what those risks look like in practice though.

Agreed that it's not clear what the risks are.   I think there are other options (e.g., ForbiddenAPIs) for enforcing lower-JDK source standards, so I'll look into those to address the risk of "dang, my backport failed".  And evaluate whether it's more effort to prevent it than to just fix it when it breaks...

**Comment by reta** [comment]
> I'm curious what the best approach here is. Can we keep `targetCompatibility` as 21 to address this campaign while still requiring `sourceCompatibility` of 11 to make sure backporting goes smoothly and doesn't diverge too much?

Thank you @dbwiddis , additionally to what @andrross said, I think the benefits of using new language features (as well as standard library) outweigh the inconvenience of manual backports (otherwise the legacy will always hold us back). Surely, there is also an option to use baseline constructs  (JDK-11) without lowering the source compatibility levels.
