### ISSUE TITLE
[META] [2.16] Cluster State Publication using Remote State

### ISSUE THREAD

**Issue by soosinha** [opensearch-project/OpenSearch#14682]
### Please describe the end goal of this project

For remote store enabled clusters, the cluster state is being published to a remote repository. This can be used to publish the cluster state to all nodes in the cluster. Instead of sending the cluster state object over the transport layer, the cluster manager node can just send the term and version of the cluster state over the transport layer which can then be used to download the corresponding cluster state by all the nodes directly from the remote store.

Previous meta issue for 2.15 release : https://github.com/opensearch-project/OpenSearch/issues/13683
The current meta issue is targetted for the enhancements targetted for 2.16 release.

### Supporting References

Previous meta issue for 2.15 release : https://github.com/opensearch-project/OpenSearch/issues/13683
RFC: https://github.com/opensearch-project/OpenSearch/issues/13257

### Issues

- [x] https://github.com/opensearch-project/OpenSearch/issues/14113
- [x] https://github.com/opensearch-project/OpenSearch/issues/14176
- [x] https://github.com/opensearch-project/OpenSearch/issues/14470
- [ ] https://github.com/opensearch-project/OpenSearch/issues/10682

### Related component

Cluster Manager

**Comment by getsaurabh02** [comment]
@soosinha Can we close this issue out for 2.16?

**Comment by soosinha** [comment]
This will be completed in 2.17. I have removed 2.16 tag.
