### ISSUE TITLE
[META] Paginating _cat APIs

### ISSUE THREAD

**Issue by gargharsh3134** [opensearch-project/OpenSearch#15014]
### Please describe the end goal of this project

This meta issue is targeted towards providing pagination support for ```_cat``` APIs in opensearch version 2.17 release.

### Supporting References

RFC: https://github.com/opensearch-project/OpenSearch/issues/15013

### Issues

- [ ] https://github.com/opensearch-project/OpenSearch/issues/14258
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14257
- [ ] https://github.com/opensearch-project/OpenSearch/issues/14259

### Related component

Cluster Manager

**Comment by peternied** [comment]
[Triage - attendees [1](https://github.com/peternied) [2](https://github.com/reta) [3](https://github.com/andrross) [4](https://github.com/enjoychange) [5](https://github.com/lukas-vlcek/)]
@gargharsh3134 Thanks for creating this issue, look forward to these updates.
