### ISSUE TITLE
[BWC] Temporarily disable BWC Tests until branch versions are synced

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#1507]
- [x] 1.1 bumped to 1.1.1 (#1503)
- [x] 1.2 updated to include 1.1.1 for bwc testing (#1505)
- [x] 1.x updated to include 1.1.1 for bwc testing (#1509)
- [x] main updated to include 1.1.1 for bwc testing (#1506)
- [x] 1.x bumped to 1.3.0 (#1494)
- [x] main updated to include 1.3.0 (#1510)
