### ISSUE TITLE
Add alternative usages for the REST APIs and configurations that contain "master" terminology

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#1549]
**Is your feature request related to a problem? Please describe.**
Replace "master" terminology in REST APIs and configurations, where the backwards compatibility will be impacted.

A part of #472

**Describe the solution you'd like**
1. Replace the old usages that having the word "master" with "cluster manager" in REST APIs and configurations, then create duplicate usages with the original name for backwards compatibility (including fallback logic to fallback to settings with the new name).
2. Add tests to check both old and new usages of the REST APIs and configurations.
3. Add proper deprecation notice to the old usages.

**Sub-tasks:**

Setting name:
- [x] Deprecate setting `cluster.initial_master_nodes` and introduce the alternative setting `cluster.initial_cluster_manager_nodes`. (PR: https://github.com/opensearch-project/OpenSearch/pull/2463)
- [x] Deprecate setting  `cluster.service.slow_master_task_logging_threshold` and introduce the alternative setting  .`cluster.service.slow_cluster_manager_task_logging_threshold`. (PR: https://github.com/opensearch-project/OpenSearch/pull/2451)
- [x] Deprecate setting `cluster.no_master_block`  and introduce the alternative setting `cluster.no_cluster_manager_block`. (PR: https://github.com/opensearch-project/OpenSearch/pull/2453)

Setting value:
- [x] Add a new node role `cluster_manager` that has the same functionality with `master` in the node setting `node.roles: [ master ]` (PR: https://github.com/opensearch-project/OpenSearch/pull/2424)

REST API endpoint:
- [x] Add a new REST API `GET _cat/cluster_manager` as the replacement of `GET _cat/master` (PR: https://github.com/opensearch-project/OpenSearch/pull/2404)

REST API path parameter:
- [x] Make the "node filters" <node_id> used as the request parameter for some REST API accept values with "cluster_manager" as an alternative to "master" (PR: https://github.com/opensearch-project/OpenSearch/pull/2424)

REST API request parameter name:
- [x] Add a new request parameter "cluster_manager_timeout" in the REST APIs that accept "master_timeout" parameter, and deprecate "master_timeout" (Issue: https://github.com/opensearch-project/OpenSearch/issues/2511)
- - [x] CAT Nodes API - this will be a sample (PR: https://github.com/opensearch-project/OpenSearch/pull/2435)
- See below for the full list of impacted REST APIs

REST API request parameter value:
- [x] Make the request parameter "metric" in "Cluster reroute" and "Cluster state" API accept value "cluster_manager_node" as an alternative to "master_node" (PR: https://github.com/opensearch-project/OpenSearch/pull/2415)

REST API response field:
- [x] Add a new field "discovered_cluster_manager" in the response of `GET _cluster/health` API that shows identical value of field "discovered_master" (PR: https://github.com/opensearch-project/OpenSearch/pull/2437)
- [x] Replace the "discovered_master" with "discovered_cluster_manager" in the response of `GET _cat/health` API (PR: https://github.com/opensearch-project/OpenSearch/pull/2438)
- [x] Replace the "master" with "cluster_manager" in the response of `GET _cat/nodes` API (PR: https://github.com/opensearch-project/OpenSearch/pull/2441)

**Describe alternatives you've considered**
None.

**Additional context**
Location that contains the exclusionary term and will impact the compatibility when changed:
**Setting names**
1 Discovery and cluster formation settings
`cluster.initial_master_nodes` (static)
`cluster.no_master_block` (dynamic)
`discovery.zen.no_master_block`
`discovery.zen.minimum_master_nodes`
`discovery.zen.master_election.*`
Note: discovery.zen.* settings are already [deprecated in Elasticsearch 7.0](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/release-notes-7.0.0.html#deprecation-7.0.0), but code remains to be removed. Update: they have been removed in OpenSearch 2.0 by the commit https://github.com/opensearch-project/OpenSearch/commit/4db97aa47064a425832a0858710e3395bbd717d5

2 Local gateway settings
`gateway.expected_master_nodes`
`gateway.recover_after_master_nodes`
Note: the above 2 settings are already [deprecated in Elasticsearch 7.7](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/breaking-changes-7.7.html#deprecate-defer-cluster-recovery-settings), but code remains to be removed.

3 Miscellaneous
`cluster.service.slow_master_task_logging_threshold` (dynamic)
Code: https://github.com/opensearch-project/OpenSearch/blob/1.0.0/server/src/main/java/org/opensearch/cluster/service/MasterService.java#L90

**Setting values**
1 Node roles
`node.roles: [ master ]`  (static)

**REST API endpoints**
1 [cat master](https://opensearch.org/docs/opensearch/rest-api/cat/cat-master/)
`GET _cat/master`

**REST API path parameters**
1 "node filters" used in some cluster-level APIs. The APIs are usually in the format: `GET /_nodes/<node_id>`, where `<node_id>` can be set as `_master` or `master:true` or `master:false` to filter the master nodes.
Nodes Info API API - `GET /_nodes/<node_id>` 
Nodes stats API - `GET /_nodes/<node_id>/stats` , `GET/_nodes/<node_id>/stats/<metric>` , `GET /_nodes/<node_id>/stats/<metric>/<index_metric>`
Nodes feature usage API - `GET /_nodes/<node_id>/usage` , `GET /_nodes/<node_id>/usage/<metric>`
Nodes hot threads API - `GET /_nodes/<node_id>/hot_threads`
Nodes reload secure settings API - `POST /_nodes/<node_id>/reload_secure_settings`
Task management API - `GET _tasks?nodes=<node_id>`

**REST API request parameter names**
1 master_timeout (used in multiple APIs)
- In CAT API:
CAT Allocation API https://opensearch.org/docs/opensearch/rest-api/cat/cat-allocation/
CAT Indices API https://opensearch.org/docs/opensearch/rest-api/cat/cat-indices/
CAT Master API https://opensearch.org/docs/opensearch/rest-api/cat/cat-master/
CAT Nodeattrs API https://opensearch.org/docs/opensearch/rest-api/cat/cat-nodeattrs/
CAT Nodes API https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-nodes/
CAT Pending tasks API https://opensearch.org/docs/opensearch/rest-api/cat/cat-pending-tasks/
CAT Plugins API https://opensearch.org/docs/opensearch/rest-api/cat/cat-plugins/
CAT Repositories API https://opensearch.org/docs/opensearch/rest-api/cat/cat-repositories/
CAT Shards API https://opensearch.org/docs/opensearch/rest-api/cat/cat-shards/
CAT Snapshots API https://opensearch.org/docs/opensearch/rest-api/cat/cat-snapshots/
CAT Templates API https://opensearch.org/docs/opensearch/rest-api/cat/cat-templates/
CAT Thread pool API https://opensearch.org/docs/opensearch/rest-api/cat/cat-thread-pool/
CAT Segment API https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-segments/
- In Cluster API:
Cluster health API https://opensearch.org/docs/opensearch/rest-api/cluster-health/
Cluster reroute API - `POST /_cluster/reroute`
Cluster state API - `GET /_cluster/state/<metrics>/<target>`
Cluster get settings API https://opensearch.org/docs/latest/opensearch/rest-api/cluster-settings/
Cluster update settings API https://opensearch.org/docs/latest/opensearch/rest-api/cluster-settings/
Pending cluster tasks API - `GET /_cluster/pending_tasks`
- In Index API:
Index management:
Create index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/create-index/
Delete index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/delete-index/
Get index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/get-index/
Open index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/open-index/
Close index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/close-index/
Clone index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/clone/
Shrink index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/shrink-index/
Split index API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/split/
Rollover index API `POST /<rollover-target>/_rollover/<target-index>`
Alias management:
Add index alias API https://opensearch.org/docs/latest/opensearch/rest-api/alias/
Delete index alias API `DELETE /<index>/_alias/<alias>`
Mapping management:
Get mapping API
Put mapping API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/put-mapping/
Index settings:
Get Index Settings API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/get-settings/
Update index settings API https://opensearch.org/docs/latest/opensearch/rest-api/index-apis/update-settings/
Index templates:
Get (Legacy) Index Template API `GET /_template/<index-template>`
Delete (Legacy) Index Template API `DELETE /_template/<index-template>`
Put (Legacy) Index Template API `PUT /_template/<index-template>`
Get (Composable) Index Template API `GET /_index_template/<index-template>`
Delete (Composable) Index Template API
Put (Composable) Index Template API
Get Component Template API `GET /_component_template/<index-template>`
Delete Component Template API
Put Component Template API
Simulate index API `POST /_index_template/_simulate_index/{name}`
Simulate index template API `POST /_index_template/_simulate`
Dangling indices:
Delete Dangling Index API
Import Dangling Index API `POST /_dangling/<index-uuid>`
Other:
Add index block API `PUT /<index>/_block/<block>`
- In Snapshot API:
Put snapshot repository API `PUT /_snapshot/<repository>`, `POST /_snapshot/<repository>`
Get snapshot repository API
Delete snapshot repository API
Clean up snapshot repository API `POST /_snapshot/<repository>/_cleanup`
Verify snapshot repository API `POST /_snapshot/<repository>/_verify`
Create snapshot API
Get snapshot API
Delete snapshot API
Restore snapshot API `POST /_snapshot/<repository>/<snapshot>/_restore`
Clone snapshot API
Get snapshot status API `GET _snapshot/<repository>/<snapshot>/_status`
- In Ingest API:
Put pipeline API https://opensearch.org/docs/latest/opensearch/rest-api/ingest-apis/create-update-ingest/
Get pipeline API https://opensearch.org/docs/latest/opensearch/rest-api/ingest-apis/get-ingest/
Delete pipeline API https://opensearch.org/docs/latest/opensearch/rest-api/ingest-apis/delete-ingest/
- In Script API:
Get stored script API `GET _scripts/<script-id>`
Put stored script API
Delete stored script API

**REST API request parameter values**
1 metric=master_node
Cluster reroute API - `POST /_cluster/reroute`
Cluster state API - `GET /_cluster/state/<metrics>/<target>`

**REST API response fields**
1 discovered_master
Response of `GET _cluster/health`
doc: https://opensearch.org/docs/latest/opensearch/rest-api/cluster-health/#response
code: https://github.com/opensearch-project/OpenSearch/blob/1.1.0/server/src/main/java/org/opensearch/action/admin/cluster/health/ClusterHealthResponse.java#L69
Response of `GET _cat/health` (in the header of table)
doc: https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-health/#response
code: https://github.com/opensearch-project/OpenSearch/blob/1.2.4/server/src/main/java/org/opensearch/rest/action/cat/RestHealthAction.java#L91

2  [cat nodes](https://opensearch.org/docs/latest/opensearch/rest-api/cat/cat-nodes/#response)
Response of `GET _cat/nodes`

The guide for plugins can be a reference: https://github.com/opensearch-project/opensearch-plugins/blob/ece53bf9e93403272726eb6087ed98f9c821502b/UPGRADING.md#settings

**Comment by tlfeng** [comment]
Pending tasks apart from the above PRs:
- Update the documentation link for API `cat/_cluster_manager`. Source: https://github.com/opensearch-project/OpenSearch/pull/2404#discussion_r827515971

**Comment by tlfeng** [comment]
All required changes for version 2.0 are completed.
All the REST APIs and Settings which contain "master" terminology have got inclusive alternatives.
All the non-inclusive REST APIs and Settings are deprecated in version 2.0, except REST API request parameter `master_timeout`. (See issue https://github.com/opensearch-project/OpenSearch/issues/2928 for the timeline of the deprecation for `master_timeout`)
