### ISSUE TITLE
[Rename] Rename from org.elasticsearch to org.opensearch

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#160]
This meta issue is created to track progress toward renaming from elasticsearch to the new opensearch project. This will be done in incremental PRs and tracked from this single issue:

* [x] .ci (#411)
* [x] .idea (#161)
* [x] benchmarks (#163)
* [x] buildSrc (#182)
* [x] distribution (#218, #316)
* [x] gradle (#276)

### Client
- [x] client/benchmark (#190)
- [x] client/client-benchmark-noop-api-plugin (#192)
- [x] client/rest (#310)
- [x] client/rest-high-level (#312)
- [x] client/sniffer (#243)
- [x] client/test (#242)
- [x] client/transport (#241)

### Libs

- [x] libs/cli (#255)
- [x] libs/core (#350)
- [x] libs/dissect (#263)
- [x] libs/geo (#258)
- [x] libs/grok (#262)
- [x] libs/nio (#318)
- [x] libs/plugin-classloader (#256)
- [x] libs/secure-sm (#256)
- [x] libs/ssl-config (#264)
- [x] libs/x-content (#354)

### Modules
* [x] modules/aggs-matrix-stats (#199)
* [x] modules/analysis-common (#200)
* [x] modules/geo (#201)
* [x] modules/ingest-common (#202)
* [x] modules/ingest-geoip (#205)
* [x] modules/ingest-user-agent (#204)
* [x] modules/kibana (#334)
* [x] modules/lang-expression (#206)
* [x] modules/lang-mustache (#208)
* [x] modules/lang-painless (#210)
* [x] modules/mapper-extras (#329)
* [x] modules/parent-join (#216)
* [x] modules/percolator (#213)
* [x] modules/rank-eval (#214)
* [x] modules/reindex (#230)
* [x] modules/repository-url (#222)
* [x] modules/systemd (#224)
* [x] modules/transport-netty4 (#225)
* [x] modules/build.gradle (#334)

### Plugins
* [x] plugins/analysis-icu (#193)
* [x] plugins/analysis-kuromoji (#193)
* [x] plugins/analysis-nori (#193)
* [x] plugins/analysis-phonetic (#193)
* [x] plugins/analysis-smartcn (#193)
* [x] plugins/analysis-stempel (#193)
* [x] plugins/analysis-ukranian (#193)
* [x] plugins/discovery-azure-classic (#193)
* [x] plugins/discovery-ec2 (#193)
* [x] plugins/discovery-gce (#193)
* [x] plugins/examples (#193)
* [x] plugins/ingest-attachment (#193)
* [x] plugins/mapper-annotated-text (#193)
* [x] plugins/mapper-murmur3 (#193)
* [x] plugins/mapper-size (#193)
* [x] plugins/repository-azure (#193)
* [x] plugins/repository-gcs (#193)
* [x] plugins/repository-s3 (#193)
* [x] plugins/store-smb (#193)
* [x] plugins/transport-nio (#193)
* [x] plugins/build.gradle (#193)

### QA
* [x] qa/die-with-dignity (#194)
* [x] qa/evil-tests (#194)
* [x] qa/full-cluster-restart (#194)
* [x] qa/logging-config (#194)
* [x] qa/mixed-cluster (#194)
* [x] qa/mixed-cluster-search (#194)
* [x] qa/no-bootstrap-tests (#194)
* [x] qa/os (#194)
* [x] qa/remote-clusters (#194)
* [x] qa/repository-multi-version (#194)
* [x] qa/rolling-upgrade (#194)
* [x] qa/smoke-test-client (#194)
* [x] qa/smoke-test-http (#194)
* [x] qa/smoke-test-ingest-disabled (#194)
* [x] qa/smoke-test-ingest-with-all-dependencies (#194)
* [x] qa/smoke-test-multinode (#194)
* [x] qa/smoke-test-plugins (#194)
* [x] qa/translog-policy (#194)
* [x] qa/unconfigured-node-name (#194)
* [x] qa/verify-version-constants (#194)
* [x] qa/wildfly (#194)
* [x] qa/build.gradle (#194)

* [x] rest-api-spec/ (#195)

### Server
* [x] server/src/internalClusterTest (#195)
* [x] server/src/main/java11 (#195)
* [x] server/src/main/resources (#195)
* [x] server/src/main/java/org/apache (#164)
* [x] server/src/main/java/o.e.ElasticsearchCorruptionException (#167)
* [x] server/src/main/java/o.e.ElasticsearchException (#165)
* [x] server/src/main/java/o.e.ElasticsearchGenerationException (#168)
* [x] server/src/main/java/o.e.ElasticsearchParseException (#169)
* [x] server/src/main/java/o.e.ElasticsearchSecurityException (#170)
* [x] server/src/main/java/o.e.ElasticsearchStatusException (#172)
* [x] server/src/main/java/o.e.ElasticsearchTimeoutException (#173)
* [x] server/src/main/java/o.e.ElasticsearchWrapperException (#174)
* [x] server/src/main/java/o.e.client.ElasticsearchClient (#166)
* [x] server/src/main/java/o.e.cluser.coordination.ElasticsearchNodeCommand (#175)
* [x] server/src/main/java/o.e.common.lucene.index.ElasticsearchDirectoryReader (#176)
* [x] server/src/main/java/o.e.common.lucene.index.ElasticsearchLeafReader (#177)
* [x] server/src/main/java/o.e.common.xcontent.XContentElasticsearchExtension (#178)
* [x] server/src/main/java/o.e.index.engine.ElasticsearchConcurrentMergeScheduler (#179)
* [x] server/src/main/java/o.e.index.engine.ElasticsearchReaderManager (#180)
* [x] server/src/main/java/o.e.index.shard.ElasticsearchMergePolicy (#181)
* [x] server/src/main/java/o.e.action (#203, #207, #209, #240, #248, #253, #291, #344)
* [x] server/src/main/java/o.e.bootstrap (#197, #303)
* [x] server/src/main/java/o.e.cli (#254)
* [x] server/src/main/java/o.e.client (#254)
* [x] server/src/main/java/o.e.cluster (#271, #278,  #283, #297)
* [x] server/src/main/java/o.e.common (#307, #309, #313, #317, #330, #331, #332, #335, #336, #337, #339, #356)
* [x] server/src/main/java/o.e.discovery (#308)
* [x] server/src/main/java/o.e.gateway (#282)
* [x] server/src/main/java/o.e.http (#285)
* [x] server/src/main/java/o.e.indices (#285)
* [x] server/src/main/java/o.e.index (#293, #295, #298, #299, #300, #301)
* [x] server/src/main/java/o.e.ingest (#273)  
* [x] server/src/main/java/o.e.monitor (#273)
* [x] server/src/main/java/o.e.node (#273)
* [x] server/src/main/java/o.e.persistent (#272)
* [x] server/src/main/java/o.e.plugins (#272)
* [x] server/src/main/java/o.e.repositories (#275)
* [x] server/src/main/java/o.e.rest (#229)
* [x] server/src/main/java/o.e.script (#250)
* [x] server/src/main/java/o.e.search (#294, #306, #322, #324, #325, #326, #328, #345)
* [x] server/src/main/java/o.e.snapshots (#251)
* [x] server/src/main/java/o.e.tasks (#265)
* [x] server/src/main/java/o.e.threadpool (#267)
* [x] server/src/main/java/o.e.transport (#284)
* [x] server/src/main/java/o.e.usage (#269)

### server/src/test
* [x] server/src/test/resources (#191, #359)
* [x] server/src/test/java/org/apache (#187)
* [x] server/src/test/java/o.e (#188)
* [x] server/src/test/java/o.e.action (#191)
* [x] server/src/test/java/o.e.bootstrap (#217)
* [x] server/src/test/java/o.e.cli (#219)
* [x] server/src/test/java/o.e.client (#219)
* [x] server/src/test/java/o.e.cluster (#396)
* [x] server/src/test/java/o.e.common (#356)
* [x] server/src/test/java/o.e.deps (#219)
* [x] server/src/test/java/o.e.discovery (#220)
* [x] server/src/test/java/o.e.env (#219)
* [x] server/src/test/java/o.e.gateway (#220)
* [x] server/src/test/java/o.e.http (#220)
* [x] server/src/test/java/o.e.index (#393)
* [x] server/src/test/java/o.e.indices (#369)
* [x] server/src/test/java/o.e.ingest (#220)
* [x] server/src/test/java/o.e.monitor (#388)
* [x] server/src/test/java/o.e.node (#351)
* [x] server/src/test/java/o.e.nodesinfo (#351)
* [x] server/src/test/java/o.e.persistent (#388)
* [x] server/src/test/java/o.e.plugins (#388)
* [x] server/src/test/java/o.e.recovery (#388)
* [x] server/src/test/java/o.e.repositories (#275)
* [x] server/src/test/java/o.e.rest (#229)
* [x] server/src/test/java/o.e.script (#250)
* [x] server/src/test/java/o.e.search (#345)
* [x] server/src/test/java/o.e.snapshots (#251)
* [x] server/src/test/java/o.e.tasks (#265)
* [x] server/src/test/java/o.e.test (#377)
* [x] server/src/test/java/o.e.threadpool (#267)
* [x] server/src/test/java/o.e.transport (#284)
* [x] server/src/test/java/o.e.usage (#269)
* [x] server/src/test/java/o.e.watcher (#399)

### Test
* [x] test/external-modules (#398)
* [x] test/fixtures (#370)
* [x] test/framework (#361, #363, #364, #375)
* [x] test/logger-usage (#398)
* [x] test/build.gradle (#403)
