### ISSUE TITLE
[META] Streams using Apache Arrow and Flight 

### ISSUE THREAD

**Issue by rishabhmaurya** [opensearch-project/OpenSearch#16679]
### Please describe the end goal of this project
- In-memory columnar representation of any intermediate results from search
- - Data adjacency for sequential access (scans)
- - O(1) (constant-time) random access
- - SIMD and vectorization-friendly
- - Relocatable without “pointer swizzling”, allowing for true zero-copy access in shared memory. 
- Interoperable representation of columnar data to be used across different engines like sharing between opensearch and datafusion, which is a rust based engine.
- RPC using bidirectional streams: making use of GRPC bidirectional streams handling backpressure from the client in realtime and producing batches of records on demand. Used both for internode communication (between data nodes and cordinator) as well as communication with end client. 

### Use cases
- Optimize memory overhead, cpu utilization and performance for - 
- - Search pagination API
- - Aggregation (more details to follow) .
- - [JOINs](https://github.com/opensearch-project/OpenSearch/issues/15185) in Opensearch.

[Apache Arrow](https://arrow.apache.org/docs/format/Intro.html) will serve as a library for in-memory columnar representation on any transient results used for retrieval in these use cases. [Arrow Flight](https://arrow.apache.org/docs/format/Flight.html) to be used for stream RPC. 

### Supporting References

JOINs RFC making use of this integration - https://github.com/opensearch-project/OpenSearch/issues/15185

#### Basic Framework Changes:
- [x] Library changes containing POJOs and Arrow vector APIs - https://github.com/opensearch-project/OpenSearch/pull/16691
- [x] OpenSearch basic Arrow Flight server and client implementation as a separate module.  https://github.com/opensearch-project/OpenSearch/issues/16963
- - [x] Integration with server module via plugin interface https://github.com/opensearch-project/OpenSearch/issues/16963
- - [x] TLS integration for Flight server and client https://github.com/opensearch-project/security/issues/5011 & https://github.com/opensearch-project/OpenSearch/issues/16963
- - [x] Hot reload of SSL certificate - https://github.com/opensearch-project/OpenSearch/issues/16965 
- - [x] Security plugin changes to expose parameters to build `SslContext` using `SecureTransportSettingsProvider` https://github.com/opensearch-project/security/issues/5011 . PR https://github.com/opensearch-project/security/pull/5122 
- - [x] Auth for flight server - https://github.com/opensearch-project/security/issues/5104 
- - [ ] Revisit defaults for server, client and allocator configs after benchmarks https://github.com/opensearch-project/OpenSearch/issues/16966
- [x] General purpose FlightProducer supporting basic `getStream()` and `getFlightInfo()` APIs. https://github.com/opensearch-project/OpenSearch/issues/17065
- - [x] `ProxyStreamProducer` acting as a proxy stream connecting the right data node holding the stream for a given ticket to the client.
- - [x] https://github.com/opensearch-project/OpenSearch/issues/17671 
- - [ ] partitioned stream support - https://github.com/opensearch-project/OpenSearch/issues/17493

#### Client support
- [x] RFC https://github.com/opensearch-project/opensearch-java/issues/1502 

#### Migrate Search API
- [x] Ideas to support any existing transport API to use flight transport https://github.com/opensearch-project/OpenSearch/issues/17695
- [ ] support search API using flight transport - https://github.com/opensearch-project/OpenSearch/issues/17696

#### Aggregations
- [x] RFC https://github.com/opensearch-project/OpenSearch/issues/16774
- [x] Meta task - https://github.com/opensearch-project/OpenSearch/issues/17278

#### Operational excellence 
- [x] Stream cancellation, error handling and renewal.
- [x] Metrics & Troubleshooting

### Related component

Search

**Comment by dblock** [comment]
[[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/dblock), [2](https://github.com/reta), [3](https://github.com/andrross/), [4](https://github.com/krisfreedain)]

**Comment by jngz-es** [comment]
This feature is awesome! We have one more use case from OpenSearch ML https://github.com/opensearch-project/ml-commons/issues/3328 to address streaming model/agent prediction especially for LLM calls.

**Comment by rishabhmaurya** [comment]
Stream transport based APIs are available now. Please check documentation https://github.com/opensearch-project/OpenSearch/tree/main/plugins/arrow-flight-rpc/docs 
and example plugin https://github.com/opensearch-project/OpenSearch/tree/main/plugins/examples/stream-transport-example

Stream based aggregation https://github.com/opensearch-project/OpenSearch/issues/16774 is also available for experimental use

**Comment by rishabhmaurya** [comment]
In 3.3, we have expanded the scope of streaming aggregation with supported types as string term and numeric terms. We have also improved upon robustness of stream transport. Streaming aggregation is currently behind dynamic cluster setting based feature flag. We have also worked on improving circuit breaker logic at coordinator node to improve on resiliency and also introduced heuristic to automatically fallback to traditional aggregation approach in case planner layer detects regression in running the streaming aggregation.

Linking all related PR - 
https://github.com/opensearch-project/OpenSearch/pull/19335/
. https://github.com/opensearch-project/OpenSearch/pull/19373 and https://github.com/opensearch-project/OpenSearch/pull/19506
https://github.com/opensearch-project/OpenSearch/pull/19396
https://github.com/opensearch-project/OpenSearch/pull/19488
https://github.com/opensearch-project/OpenSearch/pull/19484
