### ISSUE TITLE
[META] Productionalizing Client/Server GRPC in OpenSearch

### ISSUE THREAD

**Issue by amberzsy** [opensearch-project/OpenSearch#16787]
### Please describe the end goal of this project

Please comment on this issue with any feedback on our recent experimental release.
This is a meta issue for all work relating to Client to Server GRPC. 

### Supporting References

- [[RFC] Protobuf in OpenSearch ](https://github.com/opensearch-project/OpenSearch/issues/6844#issuecomment-1742250229)
- [[META] Leverage protobuf for serializing select node-to-node objects](https://github.com/opensearch-project/OpenSearch/issues/15308)
- [[META] Protobuf for Search API ](https://github.com/opensearch-project/OpenSearch/issues/10684)
- [gRPC support for client Search API](https://github.com/opensearch-project/opensearch-clients/issues/69#top) (initial client<>server benchmark result for Search api)

#### V3.0.0 Experimental feature release
| Feature    | GH | Finished| 
| -------- | ------- | ------- | 
| Server Core  | gRPC Server https://github.com/opensearch-project/OpenSearch/issues/16556  | :heavy_check_mark:|
| Search API - matchAll/Term/Terms/MatchNone/ScriptScore |  [Feature] GRPC Search APIs https://github.com/opensearch-project/OpenSearch/issues/16783    | :heavy_check_mark:|
| Document API - Bulk  | [Feature] GRPC Document APIs https://github.com/opensearch-project/OpenSearch/issues/16784   |:heavy_check_mark:|
| Bulk Benchmark | https://github.com/opensearch-project/OpenSearch/issues/16711 | :heavy_check_mark:|
| Search API Benchmark | https://github.com/opensearch-project/OpenSearch/issues/16710 | :heavy_check_mark:|
| API documentation | https://github.com/opensearch-project/documentation-website/issues/9591 | :heavy_check_mark:|

**GRPC Server Core**
- [x] #16556 

**Search APIs**
- [x] #15190 (proposal)
- [x] #16783 

**Document APIs**
- [x] #16784 

**API Documentation**
- [x] https://github.com/opensearch-project/documentation-website/issues/9591

####  Benchmarking
- [x] #16710 
- [x] #16711 

#### V3.1.0 feature release
| Feature    | GH | Finished| 
| -------- | ------- | ------- | 
| Server Core  |  | |
| Query DSL |     | |
| Document API |     | |

**Core**
- [x] #16905 

**Query DSL**
- [ ] [Feature] Term-level queries 
- [ ] [Feature] Full-text queries
- [ ] [Feature] Boolean, Boosting queries
- [ ] [Feature] KNN 

**Document APIs**
- [ ] [Feature] Index Document API
- [ ] [Feature] Update Document API
- [ ] [Feature] Delete Document API
- [ ] [Feature] Get Document API (? TBD)

V3.2.0 feature release or TBD 
**Index APIs**
- [x] #16785 
**Other APIs**
- [ ] [Feature] GRPC Cluster APIs
- [ ] [Feature] GRPC Nodes APIs
- [ ] [Feature] GRPC CAT APIs
- [ ] [Feature] GRPC Ingest APIs
TODO: Other APIs from the public doc are omitted for brevity, and can be added later as we become closer to working on them. 

### Proto conversion
**Protobuf support**
- [x] https://github.com/opensearch-project/opensearch-api-specification/issues/532
- [x] https://github.com/opensearch-project/opensearch-api-specification/issues/677
- [x] https://github.com/opensearch-project/opensearch-api-specification/issues/707 

**CI/CD**
- [x] https://github.com/opensearch-project/opensearch-api-specification/issues/653
- [x] [[FEATURE] Support Java jar publishing to remote Maven repository ](https://github.com/opensearch-project/opensearch-protobufs/issues/9)

### Related
- [ ] #16786 

### Related component

Other

**Comment by finnegancarroll** [comment]
Noting some additional work streams for core and OSB support:
- [Extensibility support for plugins](https://github.com/opensearch-project/OpenSearch/issues/16922)
- [OSB gRPC client support](https://github.com/opensearch-project/opensearch-benchmark/issues/726)

**Comment by finnegancarroll** [comment]
@amberzsy thanks for adding these milestones!
Just want to note that after the 3.0.0-beta1 release there will be a soft feature freeze before 3.0 GA. Any larger additions to core might want to be prioritized for beta release since they will be under greater scrutiny after. Initial Bulk/Search API/Security plugin integration likely fall into this category where as tooling, performance, and plugin related changes probably have a lot more leeway.

**Comment by amberzsy** [comment]
> [@amberzsy](https://github.com/amberzsy) thanks for adding these milestones! Just want to note that after the 3.0.0-beta1 release there will be a soft feature freeze before 3.0 GA. Any larger additions to core might want to be prioritized for beta release since they will be under greater scrutiny after. Initial Bulk/Search API/Security plugin integration likely fall into this category where as tooling, performance, and plugin related changes probably have a lot more leeway.

yeah, good point. few questions: 
1. will security plugin integration be part of 3.0 release? does it have dependency on bulk/search api implementation? (i assume it's not)
2. When's the beta release? or more specific what would be potential process and timeline look like for 3.0 release?

**Comment by finnegancarroll** [comment]
> 1. will security plugin integration be part of 3.0 release? does it have dependency on bulk/search api implementation? (i assume it's not)

The security plugin changes won't have any impact on bulk/search api. Just calling it out as well since it is planned for 3.0 and preferably makes it into beta release. PR is in review [here](https://github.com/opensearch-project/OpenSearch/pull/17406) with security plugin initial changes [here](https://github.com/opensearch-project/security/pull/5152).

> 3. When's the beta release? or more specific what would be potential process and timeline look like for 3.0 release?

Release timeline can be found [here](https://opensearch.org/releases.html) with release candidate generation to start 4/1.

> 4. for opensearch-api-spec, is it the same release process or separate? i guess it's not the same one.

I think the opensearch-api-spec itself doesn't do releases. However client projects periodically pull the latest main branch and generate code for their releases which mirror core.

> 5. as the core bulk/search api would depend on new [opensearch-protobufs](https://github.com/opensearch-project/opensearch-protobufs) repo, will it be any code freeze on new repo etc?

I imagine only large changes to the compiled protobuf libraries consumed by core would be impacted. Tooling/CI/client generation changes are probably not a concern. @peterzhuamazon will know better.
