### ISSUE TITLE
Replace "master" terminology in Java APIs

### ISSUE THREAD

**Issue by tlfeng** [opensearch-project/OpenSearch#1684]
**Is your feature request related to a problem? Please describe.**
Replace the "master" terminology in all Java APIs, including field, method, class, and package names.
The "Java APIs" refers to those packaged in Java libraries and are published to Maven (https://search.maven.org/search?q=g:org.opensearch https://mvnrepository.com/artifact/org.opensearch)

Impact:
All plugins, clients and tools that use OpenSearch Java APIs from OpenSearch Java libraries which contain non-inclusive terminologies have to make corresponding changes to call new APIs, if they want to upgrade the dependency to a future major version of OpenSearch.

A part of #472

**Describe the solution you'd like**
Replace the "master" terminology with "**ClusterManager**" in all Java APIs that are exposed in Java libraries.

Overall solution: https://github.com/opensearch-project/OpenSearch/issues/1684#issuecomment-1145541374
Sub-issue:
- [x] https://github.com/opensearch-project/OpenSearch/issues/3542
- [x] https://github.com/opensearch-project/OpenSearch/issues/3543
- [x] https://github.com/opensearch-project/OpenSearch/issues/3544
- [ ] Remove the deprecated codes. It will be tracked in issue https://github.com/opensearch-project/OpenSearch/issues/2773

**Describe alternatives you've considered**
None.

**Additional context**
Locations of "master" in API of Java library:
These libraries have been published to Maven. (Links: https://mvnrepository.com/artifact/org.opensearch https://search.maven.org/search?q=g:org.opensearch)

server
1 package `org.opensearch.action.support.master`
https://opensearch.org/javadocs/1.1.0/OpenSearch/server/build/docs/javadoc/org/opensearch/action/support/master/package-summary.html
(totally 1 package, the package contains 15 Java classes)
2 class `org.opensearch.cluster.MasterNodeChangePredicate`
https://opensearch.org/javadocs/2.0.0/OpenSearch/server/build/docs/javadoc/org/opensearch/cluster/MasterNodeChangePredicate.html
(totally 14 classes)
3 variable `org.opensearch.action.support.master.MasterNodeRequest.DEFAULT_MASTER_NODE_TIMEOUT`
https://opensearch.org/javadocs/1.1.0/OpenSearch/server/build/docs/javadoc/org/opensearch/action/support/master/MasterNodeRequest.html#DEFAULT_MASTER_NODE_TIMEOUT
(totally 15 variables)
4 method `org.opensearch.cluster.node.DiscoveryNodes.Builder.masterNodeId(String)`
https://opensearch.org/javadocs/2.0.0/OpenSearch/server/build/docs/javadoc/org/opensearch/cluster/node/DiscoveryNodes.Builder.html#masterNodeId(java.lang.String)
... (In version 1.1.0, totally 177 methods) (In version 2.0.0, totally 142 methods)

[Java Low Level REST Client](https://opensearch.org/docs/latest/clients/java/)
1 variable `org.opensearch.client.NodeSelector.SKIP_DEDICATED_MASTERS`
https://opensearch.org/javadocs/1.1.0/OpenSearch/client/rest/build/docs/javadoc/org/opensearch/client/NodeSelector.html#SKIP_DEDICATED_MASTERS
(totally 1 variable)
2 method `org.opensearch.client.Node.Roles.isMasterEligible()`
https://opensearch.org/javadocs/1.1.0/OpenSearch/client/rest/build/docs/javadoc/org/opensearch/client/Node.Roles.html#isMasterEligible()
(totally 1 method)

[Java High Level REST Client](https://opensearch.org/docs/latest/clients/java-rest-high-level/)
1 variable `org.opensearch.client.TimedRequest.DEFAULT_MASTER_NODE_TIMEOUT`
https://opensearch.org/javadocs/1.1.0/OpenSearch/client/rest-high-level/build/docs/javadoc/org/opensearch/client/TimedRequest.html#DEFAULT_MASTER_NODE_TIMEOUT
(totally 1 variable)
2 method `org.opensearch.client.TimedRequest.masterNodeTimeout()`
https://opensearch.org/javadocs/2.0.0/OpenSearch/client/rest-high-level/build/docs/javadoc/org/opensearch/client/TimedRequest.html#masterNodeTimeout()
(totally 11 methods)

Test Framework
1 class `org.opensearch.test.disruption.BlockMasterServiceOnMaster`
https://opensearch.org/javadocs/2.0.0/OpenSearch/test/framework/build/docs/javadoc/org/opensearch/test/disruption/BlockMasterServiceOnMaster.html
(totally 3 classes)
2 variable `org.opensearch.test.InternalTestCluster.DEFAULT_HIGH_NUM_MASTER_NODES`
https://opensearch.org/javadocs/2.0.0/OpenSearch/test/framework/build/docs/javadoc/org/opensearch/test/InternalTestCluster.html#DEFAULT_HIGH_NUM_MASTER_NODES
(totally 4 variables)
3 method `org.opensearch.client.Client.masterClient()`
https://opensearch.org/javadocs/2.0.0/OpenSearch/test/framework/build/docs/javadoc/org/opensearch/test/InternalTestCluster.html#masterClient()
(totally 41 methods)

**Comment by tlfeng** [comment]
The plan to resolve this issue is:
- In `2.x` branch:
1. Add `@deprecated` annotation to all public and protected class/method/field names, which contain master word.
2. Add alternative class/method/field that replace "master" with "cluster manager".
3. No new test will be added.
- In `main` branch:
1. Replace all public and protected class/method/field name that contains  "master" word with "cluster manager". (follow the rule of camel case)
