### ISSUE TITLE
[Feature Request] Security plugin integration for grpc-transport plugin 

### ISSUE THREAD

**Issue by finnegancarroll** [opensearch-project/OpenSearch#16905]
### Is your feature request related to a problem? Please describe

Implement security features and integrate with OpenSearch security plugin for production readiness of experimental gRPC transport. It should be the case that security settings for existing http transport maps cleanly onto newly introduced grpc-transport, providing configurable TLS for this new transport implementation.

### TLS/Certificate Management
- Enable selection of a `experimental-secure-transport-grpc` aux transport type from the `transport-grpc` plugin.
- Provide a distinct namespace for aux transport security settings within security plugin
In keeping with previous transport settings: https://opensearch.org/docs/latest/security/configuration/tls/
Aux transports should have keystore and truststore configurable under the `plugins.security.ssl.aux` prefix.
- Allow users to enable `experimental-secure-transport-grpc` SSL only TLS.
- Enable `experimental-secure-transport-grpc` handling of pemkey/keystore configurations from security plugin.
- Enable `experimental-secure-transport-grpc` handling of pemtrust/trustore configurations from security plugin.

Reach goals: 
 
- Enable hot reloading of SSL context/engine for aux transports.
- Enable separate client/server role configurations for aux transports which plan to make node-to-node requests.

### Roadmap
- [x] Add additional aux transport type `experimental-secure-transport-grpc` to gRPC plugin. 
#17796 
- [x] Add `plugins.security.ssl.aux` keystore and truststore settings to security plugin.
https://github.com/opensearch-project/security/pull/5152
- [x] Enable SSL only TLS for new transport type.
https://github.com/opensearch-project/security/pull/5152
- [x] Enable mTLS for new transport type.
https://github.com/opensearch-project/security/pull/5152
- [x] Allow distinct security configurations per aux transport.
https://github.com/opensearch-project/OpenSearch/issues/17795
- [ ] Enable hot reloading of SSL context/engine for aux transports.

### Authentication/Authorization
_*Authorization is not covered by this issue and will need to be handled in a follow up when API structure is known for this plugin *_

### Related component

Plugins

### Describe alternatives you've considered

Leaving the grpc-transport unsecured.

**Comment by krisfreedain** [comment]
[Catch All Triage](https://github.com/opensearch-project/.github/blob/main/TRIAGING.md) - [1](https://github.com/krisfreedain), [2](https://github.com/andrross/), [3](https://github.com/reta)

**Comment by aparajita31pandey** [comment]
Hi @finnegancarroll  is there any doc or a roadmap available around the implementation of authorization for the gRPC API?

**Comment by finnegancarroll** [comment]
Hi @aparajita31pandey, currently there is not. This issue only covers authentication of users and I have not dug into how that will translate to authorization and back end roles.

**Comment by cwperks** [comment]
Reopening because the companion security PR is still open

**Comment by aparajita31pandey** [comment]
@finnegancarroll How authentication of users is been done for gRPC endpoints?
I am looking for gRPC endpoint hook similar to ActionPlugin.getRestHandlerWrapper  for  all REST API - ? https://github.com/opensearch-project/security/issues/5379

**Comment by finnegancarroll** [comment]
Closing per https://github.com/opensearch-project/security/pull/5375
