### ISSUE TITLE
[Meta] Remove mapping types

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#1940]
**Is your feature request related to a problem? Please describe.**
The mapping types have been deprecated in Elasticsearch (starting from 7.0) [1] with breaking changes to the index creation, put mapping, get mapping, put template, get template and get field mappings APIs and on track to be removed in 8.0 [2]. This is the debt Opensearch has inherited and the code related to mapping types support has to be removed. 

[1] https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html
[2] https://github.com/elastic/elasticsearch/issues/41059

**Describe the solution you'd like**
Remove mapping types support from the core and APIs.

**Describe alternatives you've considered**
1) Keep the code around (nonetheless it is dead)
2) Resurrect mapping types support (what is the case for it?)

**Additional context**
[Removal of mapping types] (https://www.elastic.co/guide/en/elasticsearch/reference/current/removal-of-types.html)

 
OpenSearch Engine Subtasks
- [x] #2109 
- [x] #2239
- [x] #2253
- [x] #2258
- [x] #2262
- [x] https://github.com/opensearch-project/OpenSearch/pull/2335
- [x] #2356
- [ ] #2357
- [x] Type removal from API end-points
   - [x] RestIndexAction https://github.com/opensearch-project/OpenSearch/pull/2026
   - [x] RestUpdateAction https://github.com/opensearch-project/OpenSearch/pull/2204
   - [x] RestDeleteAction https://github.com/opensearch-project/OpenSearch/pull/2239
   - [x] RestGetAction https://github.com/opensearch-project/OpenSearch/pull/2168
   - [x] RestMultiGetAction https://github.com/opensearch-project/OpenSearch/pull/2168
   - [x] RestExplainAction https://github.com/opensearch-project/OpenSearch/pull/2205
   - [x] RestBulkAction #2215
   - [x] RestNoopBulkAction https://github.com/opensearch-project/OpenSearch/pull/2261
   - [x] RestSearchAction https://github.com/opensearch-project/OpenSearch/pull/2263 and https://github.com/opensearch-project/OpenSearch/pull/2168
   - [x] RestMultiSearchAction https://github.com/opensearch-project/OpenSearch/pull/2263
   - [x] RestSearchTemplateAction https://github.com/opensearch-project/OpenSearch/pull/2263
   - [x] RestMultiSearchTemplateAction https://github.com/opensearch-project/OpenSearch/pull/2433 & https://github.com/opensearch-project/OpenSearch/pull/2263
   - [x] RestNoopSearchAction https://github.com/opensearch-project/OpenSearch/pull/2261
   - [x]  RestCountAction https://github.com/opensearch-project/OpenSearch/pull/2379
   - [x] RestUpdateByQueryAction https://github.com/opensearch-project/OpenSearch/pull/2263
   - [x] RestDeleteByQueryAction https://github.com/opensearch-project/OpenSearch/pull/2263
   - [x] RestGetFieldMappingAction https://github.com/opensearch-project/OpenSearch/pull/2238
   - [x] RestGetMappingAction https://github.com/opensearch-project/OpenSearch/pull/2238
   - [x] RestPutMappingAction https://github.com/opensearch-project/OpenSearch/pull/2238
   - [x] RestValidateQueryAction https://github.com/opensearch-project/OpenSearch/pull/2255
   - [x] RestGetSourceAction https://github.com/opensearch-project/OpenSearch/pull/2168
   - [x] RestTermVectorsAction https://github.com/opensearch-project/OpenSearch/pull/2104 and https://github.com/opensearch-project/OpenSearch/pull/2263
   - [x] RestMultiTermVectorsAction https://github.com/opensearch-project/OpenSearch/pull/2263
- [x] #2195
- [x] #2240
- [x] #2267
- [x] #2296


Plugins:
- [x] alerting-dashboards-plugin  https://github.com/opensearch-project/alerting-dashboards-plugin/issues/181
- [x] alerting https://github.com/opensearch-project/alerting/issues/317
- [x] anomaly-detection-dashboards-plugin:  https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/184
- [x] anomaly-detection https://github.com/opensearch-project/anomaly-detection/issues/394
- [x] asynchronous-search https://github.com/opensearch-project/asynchronous-search/issues/98
- [x] common-utils https://github.com/opensearch-project/common-utils/issues/123
- [x] dashboards-reports https://github.com/opensearch-project/dashboards-reports/issues/292
- [x] dashboards-visualizations https://github.com/opensearch-project/dashboards-visualizations/issues/52
- [x] index-management-dashboards-plugin https://github.com/opensearch-project/index-management-dashboards-plugin/issues/155
- [x] index-management https://github.com/opensearch-project/index-management/issues/282
- [x] job-scheduler https://github.com/opensearch-project/job-scheduler/issues/131
- [x] K-NN https://github.com/opensearch-project/k-NN/issues/303
- [x] notifications https://github.com/opensearch-project/notifications/issues/375
- [x] performance-analyzer https://github.com/opensearch-project/performance-analyzer/issues/145
- [x] performance-analyzer-rca https://github.com/opensearch-project/performance-analyzer-rca/issues/134
- [x] security-dashboards-plugin https://github.com/opensearch-project/security-dashboards-plugin/issues/914
- [x] security https://github.com/opensearch-project/security/issues/1658
- [x] sql https://github.com/opensearch-project/sql/issues/452
- [x] observability https://github.com/opensearch-project/observability/issues/523
- [x] cross-cluster-replication https://github.com/opensearch-project/cross-cluster-replication/issues/318
- [ ] OpenSearch-Dashboards https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1290

Clients
- [x] data-prepper https://github.com/opensearch-project/data-prepper/issues/1139
- [ ] logstash-output-opensearch https://github.com/opensearch-project/logstash-output-opensearch/issues/128
- [x] opensearch-clients https://github.com/opensearch-project/opensearch-clients/issues/6

Other
- [ ] opensearch-benchmark https://github.com/opensearch-project/opensearch-benchmark/issues/150
- [ ] opensearch-benchmark-workloads https://github.com/opensearch-project/opensearch-benchmark-workloads/issues/37
- [x] opensearch-cli https://github.com/opensearch-project/opensearch-cli/issues/47
- [x] ml-commons: https://github.com/opensearch-project/ml-commons/issues/158
- [ ] opensearch-oci-object-storage https://github.com/opensearch-project/opensearch-oci-object-storage/issues/8
- [ ] documentation-website https://github.com/opensearch-project/documentation-website/issues/429
- [x] project-website https://github.com/opensearch-project/project-website/issues/709

**Comment by CEHENKLE** [comment]
Thanks @reta This seems to make sense to actually remove in 2.0.  What do you think?'

Thanks again,
/C

**Comment by anasalkouz** [comment]
More discussion already here: https://discuss.opendistrocommunity.dev/t/is-opensearch-planning-to-remove-the-mapping-types-too/8341?u=searchymcsearchface

**Comment by reta** [comment]
@CEHENKLE +1 to include it into `2.0` roadmap

**Comment by dreamer-89** [comment]
Looking into it

**Comment by nknize** [comment]
We may want to convert this to a meta issue. This is a biggie, especially for bwc testing. If we try to remove everything there's a possibility of it not being completed in time for 2.0. Types is already deprecated so I don't think we need to make it a blocker for 2.0; we should be able to continue during the 2.x line.

**Comment by anasalkouz** [comment]
> We may want to convert this to a meta issue. This is a biggie, especially for bwc testing. If we try to remove everything there's a possibility of it not being completed in time for 2.0. Types is already deprecated so I don't think we need to make it a blocker for 2.0; we should be able to continue during the 2.x line.

@nknize my understanding that removing mapping types is breaking changes and we should target a major a release. Otherwise, we can target any minor release.

**Comment by dreamer-89** [comment]
Update

1. Remove type references from rest end-points [In-Progress]
2. Remove internal references of type mapping e.g. Transport layer, builders etc
3. Update plugin integrations in respective repositories
4. Client Update - Java/Python/Go
5. Testing
a. Automated - covered by UT & ITs in OpenSearch repo
b. Manual - Verify various upgrades paths from 1.x -> 2.0
c. Plugins integration - Build OpenSearch main branch with default plugins; following existing build process. Sample build [manifest file](https://github.com/opensearch-project/opensearch-build/blob/main/manifests/1.3.0/opensearch-1.3.0.yml)
d. Clients - Java/Python/Go

**Comment by dreamer-89** [comment]
### Proposal for v2.0 release

* Rest end-points updates
    * Document APIs
        * Ingestion, Update, Delete, Get APIs
        * UpdateByQuery, DeleteByQuery
        * Bulk Request. Request and response
        * Term, multi-term vectors
    * Index APIs
        * Create Index
        * Index mapping (put/get)
        * Field mapping (put/get)
        * Source API
    * Search APIs
        * Search, multi Search, explain
        * Query
            * Terms lookup
            * Type Query - Remove
        * Validate API
    * Query DSL
* Search templates
* include_type_name param from APIs
* Backward compatibility changes necessary for upgrade
* Update sdk clients (java/python/go/php/rust etc)
* Update plugins (if needed)
* Testing 
    * Automated. 
        * Upgrade/bwc tests. Verify older OS versions are compatible with OS 2.0. Sample upgrades to test:
            * Basic. Test basic features 
                * Index. Verify indices created with types (or without) allows ingestion in OS 2.0
                * Templates. Verify templates created on OS 1.x with types, allows new index creation.
                * Searching. Verify older indices created with types, are searchable on OS 2.0 without returning type information. 
                * Snapshots. Verify older indices are getting snapshots successfully in OS 2.0. It should be possible to recover older index from snapshot in OS 2.0.
        * Integration Tests. 
    * Manual.
        * Verify main builds with different plugin repos
        * Verify advance test cases (TBD)
* Documentation

**Comment by dblock** [comment]
@dreamer-89 What's left for 2.0 here?

**Comment by dreamer-89** [comment]
> @dreamer-89 What's left for 2.0 here?

@dblock : We have completed all changes for `2.0`. 

We are targeting remaining pending changes post `2.0` release. Created https://github.com/opensearch-project/OpenSearch/issues/2979 to capture remaining changes.

**Comment by dblock** [comment]
Let's close this, then. 

We have https://github.com/opensearch-project/OpenSearch/issues/2357 and https://github.com/opensearch-project/OpenSearch/issues/2979 for 2.1.
