### ISSUE TITLE
[PURIFY] Remove all trace of XPack code from High Level Rest Client

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#2]
This meta issue tracks removal of references of Elastic licensed classes from the `client/high-level-rest` module. 

- [x] @nknize ~~EQL~~  (PR: #2)
- [x] @nknize~~Enrichment Processor~~ (PR: #3)
- [x] @nknize ~~Async Search~~ (PR: #5)
- [x] @nknize ~~CCR~~ (PR: #6)
- [x] @nknize ~~Graph~~ (PR: #7)
- [x] @nknize ~~ILM~~ (PR: #11)
- [x] @adnapibar  ~~License Tools~~ (PR: #15, #25)
- [x] @nknize ~~Migration~~ (#12)
- [x] @nknize ~~Monitoring~~ (#13)
- [x] @nknize ~~ML~~ (#14)
- [x] @adnapibar  Security / SSL (PR: #18, #26) 
- [x] @nknize ~~Watcher~~ (PR: #16)
- [x] @nknize ~~SQL~~ (PR: #17)
- [x] @nknize ~~Rollups~~ (PR: #19)
- [x] @nknize ~~Transform~~ (PR: #31)
- [x] @nknize ~~Data Streams~~ (PR: #28)
- [x] @adnapibar ~~Analytics~~ (PR: #59 #62)
- [x] @abbashus  ~~Freeze/Unfreeze~~ Index (PR: #85)
