### ISSUE TITLE
[META] Segment Replication Issue list

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#2194]
Please comment on this issue with any feedback on our recent experimental release.

This is a meta issue for all work relating to Segment Replication.
- [x] #2229 
- [x] #3969 
- [x] #5147

Performance Improvements:
- [ ] #4245 
- [x] #4448
- [x] #4478 

Compatibility:
- [x] #3881 
- [x] #3823 

Bugs:
- [x] https://github.com/opensearch-project/OpenSearch/issues/4538
- [x] https://github.com/opensearch-project/OpenSearch/issues/4530
- [x] #4136

Benchmarking:
- [ ] https://github.com/opensearch-project/OpenSearch/issues/2583

Future Extensions:
- [ ] #3685
- [x] #4036 
- [x] #4291
- [ ] #3929
- [ ] #4577

Completed:
-----
- [x] #2355
- [x] #2197 
- [x] #2199
- [x] #2202 
- [x] #2330 
- [x] #2331 
- [x] #2332
- [x] #2358
- [x] #2588 
- [x] #3558 
- Bugs: 
  - [x] #2414
  - [x] #2285
  - [x] #2431 
  - [x] #2815

**Comment by kartg** [comment]
Capturing pending refactor work from the last refactor PR - https://github.com/opensearch-project/OpenSearch/pull/2468 

- Remove `ShardRoutingReplicationListener` and use a single class based on extracting `PeerRecoveryTargetService.RecoveryListener` instead - https://github.com/opensearch-project/OpenSearch/pull/2468#discussion_r827414977
- Refactor the `*Collection` classes and merge common functionality - https://github.com/opensearch-project/OpenSearch/pull/2468#discussion_r827426972

**Comment by kartg** [comment]
Action items from another PR - #2551 
* Improve replication lifecycle management by avoiding distributed ownership across classes - https://github.com/opensearch-project/OpenSearch/pull/2551#discussion_r833583823
* Update segment replication test verification steps to validate file structure (and therefore point-in-time consistency) over and above hit count - https://github.com/opensearch-project/OpenSearch/pull/2551#issuecomment-1078258509

**Comment by navneet1v** [comment]
I want to understand few cases and how they are handled overall, my understanding is based on this GH issue: https://github.com/opensearch-project/OpenSearch/issues/2229

1. If during syncing of segments to replicas if the node containing primary dies how the cluster will recover?
2. What will happen to the shard re-routing process when a node left the cluster during the fsync is happening?
