### ISSUE TITLE
[TEST] Fix Unit and Integration Tests as part of Removal of XPack code

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#23]
This meta issue tracks fixing all the tests which are failing as part of the removal of references of Elastic licensed code (CR #2)

- [x] @adnapibar Compile Issues (#29)
- [x] Build Tools Integration Tests (Gradle Task :build-tools:integTest)

**REST High Level Client Tests (Gradle Task :client:rest-high-level:test)**
  Tests with failures:
- [x] org.elasticsearch.client.RequestConvertersTests.testExists (#55)
- [x] org.elasticsearch.client.RequestConvertersTests.testGetSource (#55) 
- [x] org.elasticsearch.client.RequestConvertersTests.testMultiGet (#55) 
- [x] org.elasticsearch.client.RequestConvertersTests.testSourceExistsWithType (#55) 
- [x] org.elasticsearch.client.indices.GetDataStreamResponseTests.testFromXContent

**REST High Level Client Integ Tests (Gradle Task :client:rest-high-level:asyncIntegTest)**
  Tests with failures:
- [x] org.elasticsearch.client.IndicesClientIT.testFreezeAndUnfreeze(#85)
- [x] org.elasticsearch.client.IndicesClientIT.testReloadAnalyzer(#48)
- [x] org.elasticsearch.client.ReindexIT.testDeleteByQuery 
- [x] org.elasticsearch.client.analytics.AnalyticsAggsIT.testTopMetricsDoubleMetric(#59)
- [x] org.elasticsearch.client.analytics.AnalyticsAggsIT.testStringStats (#59)
- [x] org.elasticsearch.client.analytics.AnalyticsAggsIT.testTopMetricsSizeTwo (#59)
- [x] org.elasticsearch.client.analytics.AnalyticsAggsIT.testTopMetricsLongMetric (#59)
- [x] org.elasticsearch.client.analytics.AnalyticsAggsIT.testTopMetricsDateMetric (#59)
- [x] org.elasticsearch.client.analytics.AnalyticsAggsIT.testTopMetricsManyMetrics (#59)
- [x] org.elasticsearch.client.UpdateByQueryIT.testUpdateByQuery 
- [x] org.elasticsearch.client.documentation.IndicesClientDocumentationIT.testFreezeIndex(#85)
- [x] org.elasticsearch.client.documentation.IndicesClientDocumentationIT.testUnfreezeIndex(#85)
- [x] org.elasticsearch.client.documentation.IndicesClientDocumentationIT.testReloadSearchAnalyzers(#48)
- [x] org.elasticsearch.client.documentation.CRUDDocumentationIT.testGetSource 
- [x] org.elasticsearch.client.SearchIT.testSearchWithBasicLicensedQuery (#60)
   ```
