### ISSUE TITLE
[Segment Replication] Merge back to main tracking issue.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#2355]
There are significant gaps in unit & integration testing of the feature because this was not prioritized with the poc.  This issue will track issues to fill these gaps.

This is a list of how I think we could cut our feature branch to start merging back into main.  Each one of these should have unit coverage.

- [x] #2926 
- [x] #2927
- [x] #3109
- [x] #3110
- [x] #3112
- [x] #3320
- [x] #3322

Misc changes:
- [x] Add segrep index setting - #2904 
- [x]  LocalCheckpointTracker - fast forwarding seqNo. Does not need to be called anywhere yet.  - #2883  

Self review.  These are some Ideas after looking at our diff here - https://github.com/opensearch-project/OpenSearch/compare/feature/segment-replication that I think might be worth doing as we merge back into main:
- [ ] IndicesClusterStateService - Refactor ShardRoutingReplicationListener and ShardRoutingRecoveryListener to a single listener class, these are identical.
- [ ] Store & MultiFileWriter - conditional fsyncs.  Do nothing for now on the merge.  We want this as a separate optional sergep setting, and they should be enabled with segrep on, so logic is different than what’s in feature branch right now.

**Comment by mch2** [comment]
Closing bc merge is complete, recovery path updates is not a merge.  Tracked in meta issue.
