### ISSUE TITLE
CI for search

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#24]
- [x] Add a CI workflow to run for every commit on search #35 
- [ ] Run unit tests and integration tests in CI
- [ ] Remove github actions CI
- [ ] Remove Elastic CI references (running on elastic jenkins)
