### ISSUE TITLE
[Meta] Deprecate non-inclusive naming 

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#2589]
This is a meta issue to track the pan and progress of applying inclusive naming across OpenSearch Repositories

**Timeline**

OpenSearch 2.0 will deprecate several APIs in core. Plugins will deprecate APIs in 2.0. By a 2.x version all non-inclusive terminology will be deprecated, and all deprecated APIs will be removed in 3.0.

**High Level Plan**
Every repository that uses non-inclusive words should replace all the non-inclusive usages in the code base. There are 2 main action to take as following:

- We have provided alternative REST APIs/settings for the existing non-inclusive usages for OpenSearch main repository, which means all the REST APIs/settings that contain "master" or "blacklist/whitelist" will have alternative usages that uses "cluster_manager" or "denylist/allowlist". That being said, **you should use the new introduced REST APIs/settings in 2.0**. Please see [here](https://github.com/opensearch-project/documentation-website/issues/450) for the inclusive alternative REST APIs/settings.
- You should replace non-inclusive usages into your repositories, the following is our suggested plan to follow:
	- Replace the non-inclusive words in code comment and internal variable/method/class/package name in 2.0.
	- Introduce alternative REST APIs/settings for the existing non-inclusive usages and deprecate old usage in 2.0.
	- Replace non-inclusive usages for OpenSearch REST API and setting with provided inclusive ones in 2.0
	- Replace non-inclusive usages for OpenSearch Java API and remove all deprecated usages in 3.0.

**List of Issues** 
When being compatible with OpenSearch 2.0:
- [x] https://github.com/opensearch-project/OpenSearch/issues/472
    - [x] https://github.com/opensearch-project/alerting/issues/320
    - [x] https://github.com/opensearch-project/anomaly-detection/issues/397
    - [x] https://github.com/opensearch-project/index-management/issues/285
    - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1318
    - [x] https://github.com/opensearch-project/k-NN/issues/307
    - [x] https://github.com/opensearch-project/sql/issues/463
    - [x] https://github.com/opensearch-project/asynchronous-search/issues/99
    - [x] https://github.com/opensearch-project/cross-cluster-replication/issues/319
    - [x] https://github.com/opensearch-project/performance-analyzer/issues/152
    - [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/139
    - [x] https://github.com/opensearch-project/security/issues/1664
    - [x] https://github.com/opensearch-project/anomaly-detection-dashboards-plugin/issues/235
    - [x] https://github.com/opensearch-project/documentation-website/issues/450

- [x] https://github.com/opensearch-project/OpenSearch/issues/1483
    - [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1319
    - [x] https://github.com/opensearch-project/sql/issues/464
    - [x] https://github.com/opensearch-project/documentation-website/issues/449
    - [x] https://github.com/opensearch-project/security/issues/1665
    - [x] https://github.com/opensearch-project/alerting/issues/321

**List of REST APIs and settings that contain non-inclusive name in other repositories**
_REST API of plugins_

- Performance Analyzer
Impacted API: `GET <endpoint>:9600/_plugins/_performanceanalyzer/metrics`
Document: https://opensearch.org/docs/latest/monitoring-plugins/pa/api/
Detail: Names of 3 [Performance Analyzer metrics](https://opensearch.org/docs/latest/monitoring-plugins/pa/reference/) can be contained in an optional parameter of the API request, and a field of the API response: Master_PendingQueueSize  , Master_Task_Queue_Time , Master_Task_Run_Time . 

- Security
Impacted API: `GET (or PUT or PATCH) _plugins/_security/api/whitelist`
Code: https://github.com/opensearch-project/security/blob/1.2.4.0/src/main/java/org/opensearch/security/dlic/rest/api/WhitelistApiAction.java
Detail: “whitelist” contains in the API endpoint.

_Configuration / Setting_
- OpenSearch Dashboards
Impacted setting names:
`opensearch.requestHeadersWhitelist` , 
`server.compression.referrerWhitelist` , 
`server.xsrf.whitelist` .
Detail: These settings can be configured through `opensearch_dahsboards.yml` file in `config` directory.

- Security
Impacted configuration file: `whitelist.yml`
Document: https://www.opensearch.org/docs/1.2/security-plugin/configuration/yaml/#whitelistyml
Detail: It is a YAML file in `plugins/opensearch-security/securityconfig` directory, configurations defined in the file can be imported to Security plugin.

**Comment by stockholmux** [comment]
I'm glad to see this!

**Comment by dblock** [comment]
I've updated the timeline: OpenSearch 2.0 will deprecate several APIs in core. Plugins will deprecate APIs in 2.1. By a 2.x version all non-inclusive terminology will be deprecated, and all deprecated APIs will be removed in 3.0.

**Comment by saratvemulapalli** [comment]
@anasalkouz / @tlfeng  this issue is tagged 2.1.0. 
I know we had revert couple of PRs. Is it safe to assume we will not completely ship in 2.1?
