### ISSUE TITLE
List of deprecated code removal in 3.0

### ISSUE THREAD

**Issue by anasalkouz** [opensearch-project/OpenSearch#2773]
This is a list to track all deprecated code or old usages that need to be removed on 3.0.

- [x] https://github.com/opensearch-project/OpenSearch/issues/2748
- [x] https://github.com/opensearch-project/OpenSearch/issues/2595
- [ ] Remove copy_settings parameter from split and shrink AP
- [ ] Remove boost parameter on field mapping
- [ ] CamelCase `nGram` and `edgeNGram` token filters
- [ ] DateHistogram `interval` parameter
- [ ] Adjacency matrix setting `max_adjacency_matrix_filters`
- [ ] Sort orders on [_time and _term](https://github.com/opensearch-project/OpenSearch/blob/b74d71fb747cc2873d4c2ffae825944da4d06e1b/server/src/main/java/org/opensearch/search/aggregations/InternalOrder.java#L529-L536) 
- [ ] Index template with [multiple mappings](https://github.com/opensearch-project/OpenSearch/blob/40024fcf71983c297108fd5907dafc999b1368c1/server/src/main/java/org/opensearch/cluster/metadata/IndexTemplateMetadata.java#L126)
- [ ] [boost](https://github.com/opensearch-project/OpenSearch/blob/7b75fb425f9df2b96049dac8c7dc13273f5026fd/server/src/main/java/org/opensearch/index/mapper/TypeParsers.java#L156) parameter on field mapping
- [ ] `local` parameter on [cat nodes api](https://github.com/opensearch-project/OpenSearch/blob/15161a86491569d94642f3a88174e1389218b303/server/src/main/java/org/opensearch/rest/action/cat/RestNodesAction.java#L115)
- [ ] `local` parameter in [get field mapping requests](https://github.com/opensearch-project/OpenSearch/blob/15161a86491569d94642f3a88174e1389218b303/server/src/main/java/org/opensearch/rest/action/admin/indices/RestGetFieldMappingAction.java#L91)
- [x] Some 'gateway' settings used to defer cluster recovery https://github.com/opensearch-project/OpenSearch/issues/3117
- [x] package, (public and protected) class and method that contains "master" terminology and deprecated in version 2.x in issue https://github.com/opensearch-project/OpenSearch/issues/1684
- [x] package, (public and protected) class and method that contains "whitelist" terminology and deprecated in version 2.x in issue https://github.com/opensearch-project/OpenSearch/issues/1683
- [x] Codes that add the node name to the logging configuration https://github.com/opensearch-project/opensearch/issues/4274
- [x] https://github.com/opensearch-project/OpenSearch/pull/4847
- [x] https://github.com/opensearch-project/OpenSearch/issues/11550

**Comment by dreamer-89** [comment]
Type mapping removal: https://github.com/opensearch-project/OpenSearch/issues/2979

**Comment by andrross** [comment]
3.0 has been released. Closing this issue.
