### ISSUE TITLE
[META] Add check for broken Java 11 versions on startup

### ISSUE THREAD

**Issue by uschindler** [opensearch-project/OpenSearch#2822]
**Is your feature request related to a problem? Please describe.**
As discussed in #2791 we figured out that OpenSearch does not work correctly if you use OpenJDK reference implementation version 11.0.2. The download page on jdk.java.net lists this as latest version (although the currently uptodate version is 11.0.14.1, available via Adoptium or Coretto)

**Describe the solution you'd like**
In the boostrap classes, OpenSearch checks for Java versions. We should add broken Java 11 versions there. Actually this feature request has two components:
- As OpenSearch 2.0 requires Java 11, the customized version parsing code in OpenSearch should be removed. Basically this class is obsolete: https://github.com/opensearch-project/OpenSearch/blob/31a360fc87419cd3a6d5621754f8ad9e8819f1e8/libs/core/src/main/java/org/opensearch/bootstrap/JavaVersion.java; instead the code should use `java.lang.Runtime.Version` and `java.lang.Runtime.version()` to get the current Java version.
- Indise bootsrap we should implement a denylist of Java versions (ranges): https://github.com/opensearch-project/OpenSearch/tree/31a360fc87419cd3a6d5621754f8ad9e8819f1e8/server/src/main/java/org/opensearch/bootstrap; there is already a check that looks for "ea" versions and warns user. Here we should bail out if the Java version is broken. We should use the java.lang API provided by Java and compare versions. You can go down to hotfix and also read the "ea" flag, so theres also cleanup possible.

**Describe alternatives you've considered**
Do those checks in startup script, but this is likely to break depending on charsets, languages, custom JDK builds,....

- [x] https://github.com/opensearch-project/OpenSearch/issues/3003
- [x] https://github.com/opensearch-project/OpenSearch/issues/3005
- [x] https://github.com/opensearch-project/OpenSearch/issues/3008

**Comment by dblock** [comment]
@uschindler Thanks for the detailed write up. A PR would be very welcome!

**Comment by reta** [comment]
@uschindler I could take it, wdyt?

**Comment by reta** [comment]
Done
