### ISSUE TITLE
[Segment Replication] Merge to main tracking - Refactoring of existing classes to support segrep.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#2926]
This is a tracking task for the refactoring tasks outlined in our meta merging issue.
- [x] Move RecoveryIndex to top level class and move inner classes from RecoveryIndex
- [x] Move RecoveryState.Timer to top level
- [x] Change GatedAutoCloseable to AutoCloseableRefCounted
- [x] Create base class ReplicationTarget and refactor RecoveryTarget to inherit from it.
- [x] Engine interface changes for addIndexOperationToTranslog and addDeleteOperationToTranslog

**Comment by kartg** [comment]
>  Move RecoveryIndex to top level class and move inner classes from RecoveryIndex
 Move RecoveryState.Timer to top level
 Change GatedAutoCloseable to AutoCloseableRefCounted

I can pick these up

**Comment by kartg** [comment]
> Move RecoveryState.Timer to top level
 Change GatedAutoCloseable to AutoCloseableRefCounted

PR - https://github.com/opensearch-project/OpenSearch/pull/2965

**Comment by kartg** [comment]
> Move RecoveryIndex to top level class and move inner classes from RecoveryIndex

PR - https://github.com/opensearch-project/OpenSearch/pull/3075
