### ISSUE TITLE
[Remote Store] Validation checklist

### ISSUE THREAD

**Issue by ashking94** [opensearch-project/OpenSearch#3947]
**Is your feature request related to a problem? Please describe.**
This issue will serve as the check list of all validations that must be done to ensure we are covering it from all angles. This is WIP and will continue to have the list expanded.

**Describe the solution you'd like**
 - [ ] Peer recovery validation
 - [ ] Failovers
 - [ ] Primary - Primary recovery
 - [ ] Replica promotion to primary
 - [ ] Auto restore/manul restore

**Describe alternatives you've considered**

**Additional context**
