### ISSUE TITLE
[Meta] Decommissioning and recommissioning a zone 

### ISSUE THREAD

**Issue by gbbafna** [opensearch-project/OpenSearch#3957]
**Is your feature request related to a problem? Please describe.**

There are use-case where decommissioning a zone/rack might be beneficial

 1. In a multi-zone deployment setup it might be good to support zonal deployment rather than a rolling restart per node, which might be too slow for a big cluster and might take sufficiently longer. In such a case zone serves a unit of deployment
 2. Andon cord during zonal outages is another handy mechanism which enables graceful traffic shutdown in the impacted zone/rack espl when certain nodes are still operating in a degraded manner

This issue lists the high level tasks . For more info on feature proposal, please refer: https://github.com/opensearch-project/OpenSearch/issues/3402 .

#### Tasks

* [ ]  [[Zone Decommission] APIs to decommission and storing the metadata ](https://github.com/opensearch-project/OpenSearch/issues/3953)
* [ ] [[Zone Decommission] Abdicating the cluster manager if in decommissioned zone ](https://github.com/opensearch-project/OpenSearch/issues/3954)
* [ ] [[Zone Decommission] Graceful decommission ](https://github.com/opensearch-project/OpenSearch/issues/3955)
* [ ] [[Zone Decommission] Removal of nodes in decommissioned zone ](https://github.com/opensearch-project/OpenSearch/issues/3956)

**Comment by imRishN** [comment]
Adding more meta tasks here - 

- [ ] #4083

**Comment by anasalkouz** [comment]
@imRishN @gbbafna I have update this META issue by adding couple of Zone Decommission issues
