### ISSUE TITLE
[META] Point In Time Search Issue List

### ISSUE THREAD

**Issue by dhruv16dhr** [opensearch-project/OpenSearch#3959]
**Is your feature request related to a problem? Please describe.**
This is a meta issue for all work/tasks related to Point-In-Time Search

**Describe the solution you'd like**
To provide Point-In-Time Search capability to OpenSearch users

- [ ] [OpenSearch Feature Proposal](https://github.com/opensearch-project/OpenSearch/issues/1147)
- [ ] OpenSearch Design Proposal
- [ ] [OpenSearch Dashboards Feature Proposal](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1268)
- [ ] [OpenSearch Dashboards(UX) Design Proposal](https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1612)

**Tasks and Release Timelines**
This is a WIP and below are a list of current tasks identified related to support for Point-In-Time Search feature in both OpenSearch and OpenSearch Dashboards. We will continue to add/update tasks and timelines.

- [ ] Point-In-Time Search OpenSearch Changes (To be released in 2.2.0)
  - [x] [Point-In-Time POC](https://github.com/opensearch-project/OpenSearch/pull/1652)
  - [ ] Create Point-In-Time
    - [x] [Feature Branch Changes](https://github.com/opensearch-project/OpenSearch/pull/2745)
    - [ ] [Merge to mainline](https://github.com/opensearch-project/OpenSearch)
      - [ ] [Create Point-In-Time Service Layer Changes](https://github.com/opensearch-project/OpenSearch/pull/3921)
      - [ ] Create Point-In-Time API Changes
  - [ ] Delete Point-In-Time
    - [x] [Feature Branch Changes](https://github.com/opensearch-project/OpenSearch/pull/3401)
    - [ ] [Merge to mainline](https://github.com/opensearch-project/OpenSearch)
      - [ ] [Delete Point-In-Time Service Layer Changes](https://github.com/opensearch-project/OpenSearch/pull/3949)
      - [ ] Delete Point-In-Time API Changes
  - [ ] List all Point-In-Time
    - [ ] [Merge to mainline](https://github.com/opensearch-project/OpenSearch)
      - [ ] List all Point-In-Time Service Layer Changes
      - [ ] List all Point-In-Time API Changes
  - [ ] Segments/Reader Context Changes
    - [ ] [Merge to mainline](https://github.com/opensearch-project/OpenSearch)
      - [ ] Segments Service Layer Changes
      - [ ] Segments API Changes
  - [ ] Node Stats Changes
    - [ ] [Merge to mainline](https://github.com/opensearch-project/OpenSearch)
      - [ ] Node Stats Service Layer Changes
      - [ ] Node Stats API Changes
  - [ ] [Point-In-Time Search Documentation Changes for OpenSearch](https://github.com/opensearch-project/documentation-website/issues/674)
- [ ] Point-In-Time Search OpenSearch Dashboards Changes
  - [ ] Stack Management Changes
    - [ ] Stack Management POC
  - [ ] Discover Changes
  - [ ] Visualize Changes
  - [ ] Dashboard Changes 
  - [ ] [Point-In-Time Search Documentation Changes for OpenSearch Dashboards](https://github.com/opensearch-project/documentation-website/issues/674)

**Comment by dhruv16dhr** [comment]
Point-In-Time flaky tests : https://github.com/opensearch-project/OpenSearch/pull/4632

**Comment by dhruv16dhr** [comment]
@bharath-techie Lets close the previous Point In Time Security Changes open PRs and only keep the new changes with the simplified model.
Did we update the [security model](https://github.com/opensearch-project/security/issues/2087) with the simplified model that is concluded upon? If yes, lets close this alongwith [pit backend design proposal](https://github.com/opensearch-project/OpenSearch/issues/3960)

**Comment by peternied** [comment]
@bharath-techie @dhruv16dhr I'm pretty sure that you need the following pull request to be backported to 2.4.  I am going to start the backport process, but wait for your confirmation/approval before merging

- https://github.com/opensearch-project/security/pull/2094 
- https://github.com/opensearch-project/security/pull/2223
- https://github.com/opensearch-project/security/pull/2224

**Comment by bharath-techie** [comment]
@peternied yes that's right , we'll need this PR for 2.4 release

**Comment by dhruv16dhr** [comment]
> @peternied yes that's right , we'll need this PR for 2.4 release

@bharath-techie Please close the PRs

**Comment by peternied** [comment]
Thanks, the 2.4 backport has been merged.  2.x backport is waiting on a retried CI workflow, I'll continue to shepherd those changes

**Comment by dhruv16dhr** [comment]
@bharath-techie @peternied I see that all the security (including backport PRs) are merged and closed
There is nothing pending i believe, we are good for 2.4 release for "Point-In-Time Search OpenSearch Changes". Hence marked all tasks related to PIT backend as closed in this META issue.
