### ISSUE TITLE
[Segment Replication] Experimental Release Tracking

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#3969]
This issue tracks work required to complete an experimental release of Segment Replication.

- [x] #4392
- [x] #4295
- [x] https://github.com/opensearch-project/OpenSearch/issues/4216
- [x] https://github.com/opensearch-project/OpenSearch/issues/4178
- [x] https://github.com/opensearch-project/OpenSearch/issues/4205
- [x] #2333 
- [x] #3989
- [x] #4007 
- [x] #2873

- [x] #3923
- [x] #3483 
- [x] https://github.com/opensearch-project/OpenSearch/issues/4129
- [x] #3787
