### ISSUE TITLE
Implementation of GeoBounds Aggregation on Geo Shape field

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#3980]
### Description
This issue tracks the implementation of GeoBounds Aggregation on Geo Shape field. 

### Tasks:
- [x] Refactor code of GeoBounds Aggregation on GeoPoint from server to modules/geo folder.
- [x] Backport the refactor code to 2.x branch
- [x] Implement the GeoBounds on GeoShape field
     - [x] Implement the code to convert the geobounds returned from doc value to internal aggregation.
     - [x] Integration Tests
     - [x] Unit Tests

### Dependency
https://github.com/opensearch-project/OpenSearch/issues/4049

### Useful Links
1. RFC for All Aggregations on GeoShape: https://github.com/opensearch-project/geospatial/issues/84
2. GeoBounds RFC on GeoShape : https://github.com/opensearch-project/geospatial/issues/93
3. Low Level Implementation Proposal: https://github.com/opensearch-project/geospatial/issues/92
4. https://github.com/opensearch-project/OpenSearch/issues/4049
5. All Aggregation Implementation issue: https://github.com/opensearch-project/geospatial/issues/104

**Comment by navneet1v** [comment]
Closing the issue, as the PR is merged in main.
