### ISSUE TITLE
[Meta] gradle check improvements

### ISSUE THREAD

**Issue by dreamer-89** [opensearch-project/OpenSearch#4053]
This issue covers various sub-issues around gradle check improvements and can be bucketed into following categories:

### Fix random test failures
- [ ] https://github.com/opensearch-project/OpenSearch/issues/1715
- [ ] https://github.com/opensearch-project/OpenSearch/issues/3973

### Observability
- [ ] https://github.com/opensearch-project/OpenSearch/issues/3713

### Maintainable
- [ ] Break gradle check into smaller logical sub-tasks

#### Related
https://github.com/opensearch-project/opensearch-build/issues/1572
https://github.com/opensearch-project/OpenSearch/issues/1975
