### ISSUE TITLE
[Feature] GeoHashGrid Aggregation on Geo Shape field

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#4071]
### Description
This issue tracks the implementation of GeoHashGrid Aggregation on Geo Shape field. 

### Tasks:
- [x] Refactor code of GeoHashGrid Aggregation on GeoPoint from server to modules/geo folder.
- [x] Implement the GeoHashGrid on GeoShape field
     - [x] Implement the code to find the intersection with the Hashes and return the results in correct bucket.
     - [x] Integration Tests
     - [x] Unit Tests
### Dependency
https://github.com/opensearch-project/OpenSearch/issues/4049

### Useful Links
1. RFC for All Aggregations on GeoShape: https://github.com/opensearch-project/geospatial/issues/84
2. Low Level Implementation Proposal: https://github.com/opensearch-project/geospatial/issues/92
3. Enabling Doc values for GeoShape: https://github.com/opensearch-project/OpenSearch/issues/4049
4. All Aggregation Implementation issue: https://github.com/opensearch-project/geospatial/issues/104
5. RFC: https://github.com/opensearch-project/geospatial/issues/193

**Comment by saratvemulapalli** [comment]
@navneet1v This issue is tagged for 2.5, I see few PRs out. Do you need help getting them moving?

**Comment by navneet1v** [comment]
@saratvemulapalli removing the tag and marking as 2.6

**Comment by anasalkouz** [comment]
Hey @navneet1v, is this on track for 2.7. The code freeze date is April 17, 2023.

**Comment by navneet1v** [comment]
> Hey @navneet1v, is this on track for 2.7. The code freeze date is April 17, 2023.

No. This is moved to 2.8

**Comment by janhoy** [comment]
In roadmap this is listed under 2.9.0, but this has label 3.0.0. This has been pushed 2.5 -> 2.6 -> 2.7 -> 2.8 -> 2.9 now, a bit hard to plan. We need this to migrate from ES.

**Comment by navneet1v** [comment]
@janhoy I completely understand the concern. The current geoshape aggregation launch is blocked because of the Visualization work required to support them on Dashboard Maps(Ref: https://github.com/opensearch-project/dashboards-maps/issues/59). Hence this feature is being pushed for so many releases.

To understand your usecase more, I want to know do you need this aggregation on OpenSearch Dashboards also? or your usecase is only about getting the backend aggregation results from OpenSearch cluster? 

Adding the PM for this feature @nandi-github and @vamshin to help prioritize the visualization work.

**Comment by janhoy** [comment]
Thanks for answering. We only needs the aggregation in backend and Java HighLevel Rest client. Can you consider releasing the api first, then dashboard visuals later?

**Comment by navneet1v** [comment]
@janhoy thanks this is very helpful. cc: @nandi-github @vamshin

**Comment by dreamer-89** [comment]
@navneet1v @vamshin : Is this in track for 2.9 release. If not, can you please remove (or add v2.10.0) label.

**Comment by navneet1v** [comment]
@dreamer-89 this has been merged and will be released with 2.9.

Closing this issue, the changes are merged to 2.9 branch of OpenSearch

**Comment by lbenedetto** [comment]
Does this issue only cover supporting it on the server side? It does not seem to be supported from the client side. 
I'm expecting to find some equivalent to `AggregationBuilders.geohashGrid` that I have in Elasticsearch. 

I see GeoHashGridAggregationBuilder in this repo, but it is in the `modules` directory and only stuff in the `libs` directory seems to be accessible from the client. 

Maybe I'm doing something wrong? I don't really understand how this repo is structured.

**Comment by navneet1v** [comment]
@janhoy , @lbenedetto 

> Does this issue only cover supporting it on the server side?

GeoHashgrid on geoshapes is available in OpenSearch but not in OpenSearch dashboards.

From the high level client standpoint, the high level client of OpenSearch is on deprecation path. Hence you don't see this aggregation enabled in High Level client.

You can use low level rest client to hit the _search request with the geohash aggregation on geoshape.

**Comment by janhoy** [comment]
Ah, bummer - that prevents us from a stepwise migration from ES with High-level client. Our plan was to first move to OpenSearch, basically changing the Java imports, and then migrating to a new Java client. This agg is part of bigger Builder patterns, so our only chance now is to make our own custom GeoHashGridAggregationBuilder :( But thanks anyway for the backend work, I think this will be within reach.
