### ISSUE TITLE
[Feature] GeoTileGrid Aggregation on Geo Shape field

### ISSUE THREAD

**Issue by navneet1v** [opensearch-project/OpenSearch#4072]
### Description
This issue tracks the implementation of GeoTileGrid Aggregation on Geo Shape field. 

### Tasks:
- [x] Refactor code of GeoTileGrid Aggregation on GeoPoint from server to modules/geo folder.
- [x] Implement the GeoHashGrid on GeoShape field
     - [x] Implement the code to find the intersection with the tiles and return the results in correct bucket.
     - [x] Integration Tests
     - [x] Unit Tests
### Dependency
https://github.com/opensearch-project/OpenSearch/issues/4049

### Useful Links
1. RFC for All Aggregations on GeoShape: https://github.com/opensearch-project/geospatial/issues/84
2. Low Level Implementation Proposal: https://github.com/opensearch-project/geospatial/issues/92
3. Enabling Doc values for GeoShape: https://github.com/opensearch-project/OpenSearch/issues/4049
4. All Aggregation Implementation issue: https://github.com/opensearch-project/geospatial/issues/104
5. https://github.com/opensearch-project/geospatial/issues/195

**Comment by saratvemulapalli** [comment]
@navneet1v moved this issue to 2.6 as well.

**Comment by dreamer-89** [comment]
@navneet1v @vamshin : Is this on track for 2.9 release. If not, can you please remove (or add v2.10.0) label.

**Comment by navneet1v** [comment]
@dreamer-89 this has been pushed to 2.9

**Comment by navneet1v** [comment]
Closing this issue, the changes are merged to 2.9 branch of OpenSearch
