### ISSUE TITLE
Test Failures on main

### ISSUE THREAD

**Issue by saratvemulapalli** [opensearch-project/OpenSearch#441]
Creating an issue to track all test failures on main

Reproduce with:
`./gradlew check`

**Tests with failures:**
- [x] - docker compose tests as in `qa`

- [x] org.opensearch.qa.die_with_dignity.DieWithDignityIT.testDieWithDignity #466 

`:distribution:tools:keystore-cli` Muted by #469 
- [x] org.opensearch.common.settings.UpgradeKeyStoreCommandTests.testKeystoreUpgrade
- [x] org.opensearch.common.settings.KeyStoreWrapperTests.testLegacyV3

`:server:check` Fixed by #471 
- [x] org.opensearch.OpenSearchExceptionTests.testDeduplicate
- [x] org.opensearch.plugins.PluginsServiceTests.testNonExtensibleDep @harold-wang 
- [x] org.opensearch.rest.action.RestActionsTests.testBuildBroadcastShardsHeader
- [x] org.opensearch.plugins.PluginsServiceTests.testExistingMandatoryInstalledPlugin
- [x] org.opensearch.action.search.SearchPhaseExecutionExceptionTests.testToXContent

**Fixed by** #464 #465 
- [x] org.opensearch.gradle.TestClustersPluginFuncTest > test cluster distribution is configured and started
- [x] org.opensearch.gradle.internal.InternalDistributionArchiveCheckPluginFuncTest > fails on unexpected notice content 
- [x] org.opensearch.gradle.TestClustersPluginFuncTest > custom distro folder created for tweaked cluster distribution
- [x] org.opensearch.gradle.DistributionDownloadPluginFuncTest > current version can be resolved
- [x] org.opensearch.gradle.DistributionDownloadPluginFuncTest > bwc version can be resolved
- [x] org.opensearch.gradle.DistributionDownloadPluginFuncTest > released version can be resolved
- [x] org.opensearch.gradle.DistributionDownloadPluginFuncTest > test cluster distribution is configured and started

**Fixed By** #454 
- [x] org.opensearch.analysis.common.SynonymsAnalysisTests.testSynonymsAnalysis

**Fixed By** #457 
- [x] org.opensearch.common.logging.JsonLoggerTests.testPrefixLoggerInJson
- [x]  org.opensearch.common.logging.JsonLoggerTests.testJsonLayout
- [x]  org.opensearch.common.logging.JsonLoggerTests.testJsonInStacktraceMessageIsSplitted
- [x]  org.opensearch.common.logging.JsonLoggerTests.testJsonInMessage
- [x]  org.opensearch.common.logging.JsonLoggerTests.testDeprecatedMessageWithoutXOpaqueId
- [x]  org.opensearch.common.logging.JsonLoggerTests.testStacktrace
- [x]  org.opensearch.common.logging.JsonLoggerTests.testDuplicateLogMessages
- [x]  org.opensearch.common.logging.JsonLoggerTests.testDeprecatedMessage
- [x]  org.opensearch.common.logging.OpenSearchJsonLayoutTests.testLayoutWithAdditionalFields
- [x]  org.opensearch.common.logging.OpenSearchJsonLayoutTests.testLayoutWithAdditionalFieldOverride
- [x]  :example-plugins:painless-whitelist:yamlRestTest
- [x]  org.opensearch.index.reindex.remote.RemoteResponseParsersTests.testFailureWithoutIndex
- [x]  org.opensearch.index.reindex.remote.RemoteScrollableHitSourceTests.testParseRejection

**Fixed By** #453  
- [x] org.opensearch.common.settings.SettingTests.testListSettingsDeprecated
- [x] org.opensearch.common.settings.ScopedSettingsTests.testPrivateIndexSettingsFailsValidation
- [x] org.opensearch.common.settings.SettingsTests.testSecureSettingConflict
- [x] org.opensearch.common.settings.SettingsTests.testSimpleYamlSettings
- [x] org.opensearch.common.settings.SettingsTests.testSimpleJsonSettings
- [x] org.opensearch.common.settings.SettingsTests.testIndentation
- [x] org.opensearch.common.settings.SettingsTests.testIndentationWithExplicitDocumentStart
- [x] org.opensearch.env.NodeEnvironmentTests.testNodeIdNotPersistedAtInitialization
- [x] org.opensearch.gateway.GatewayServiceTests.testDeprecatedSettings
- [x] org.opensearch.common.xcontent.smile.SmileXContentTests.testUnknownObject
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testSkipUnavailableFallbackbleCompileOnly
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testProxyFallback
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testSeedsFallback
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testEnableRemoteClustersFallback
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testDisableSearchEnableRemoteClusters
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testRemoteNodeAttributeFallback
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testDisableEnableRemoteClusters
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testConnectionsPerClusterFallback
- [x] org.opensearch.transport.RemoteClusterSettingsTests.testInitialConnectTimeoutFallback
- [x] org.opensearch.script.ScriptServiceTests.testFallbackToContextDefaults
- [x] org.opensearch.script.ScriptServiceTests.testConflictContextSettings
- [x] org.opensearch.script.ScriptServiceTests.testCacheEvictionCountedInCacheEvictionsStats
- [x] org.opensearch.script.ScriptServiceTests.testUseContextSettingValue
- [x] org.opensearch.script.ScriptServiceTests.testFallbackContextSettings
- [x] org.opensearch.script.ScriptServiceTests.testCacheHolderChangeSettings
- [x] org.opensearch.script.ScriptServiceTests.testCompilationStatsOnCacheHit
- [x] org.opensearch.script.ScriptServiceTests.testCacheHolderGeneralConstructor
- [x] org.opensearch.script.ScriptServiceTests.testDisableCompilationRateSetting
- [x] org.opensearch.script.ScriptServiceTests.testCompilationRateUnlimitedContextOnly
- [x] org.opensearch.cluster.node.DiscoveryNodeRoleSettingTests.testIsIngestNode
- [x] org.opensearch.cluster.node.DiscoveryNodeRoleSettingTests.testIsRemoteClusterClient
- [x] org.opensearch.cluster.node.DiscoveryNodeRoleSettingTests.testIsMasterNode
- [x] org.opensearch.cluster.node.DiscoveryNodeRoleSettingTests.testIsDataNode
- [x] org.opensearch.threadpool.AutoQueueAdjustingExecutorBuilderTests.testValidatingMinMaxSettings
- [x] org.opensearch.threadpool.AutoQueueAdjustingExecutorBuilderTests.testSetHigherSettings
- [x] org.opensearch.threadpool.AutoQueueAdjustingExecutorBuilderTests.testSetLowerSettings
- [x] org.opensearch.common.util.concurrent.OpenSearchExecutorsTests.testProcessorsBound
- [x] org.opensearch.threadpool.FixedThreadPoolTests.testRejectedExecutionCounter
- [x] org.opensearch.common.xcontent.yaml.YamlXContentTests.testUnknownObject
- [x] org.opensearch.common.xcontent.cbor.CborXContentTests.testUnknownObject
- [x] org.opensearch.common.xcontent.json.JsonXContentTests.testUnknownObject
- [x] org.opensearch.cluster.metadata.MetadataIndexUpgradeServiceTests.testFailUpgrade
- [x] org.opensearch.cluster.routing.allocation.BalanceUnbalancedClusterTests.testRun
- [x] org.opensearch.action.admin.cluster.settings.SettingsUpdaterTests.testDeprecationLogging

**Fixed by** #451 (`:rest-api-spec:yamlRestTest`)
- [x] indices.create/10_basic/Create index without soft deletes
- [x] indices.stats/20_translog/Translog stats on closed indices without soft-deletes

**Fixed by** #460 (`plugins.ListPluginsCommandTests.testPluginWithNativeController`)
- [x] org.opensearch.plugins.ListPluginsCommandTests.testPluginWithNativeController

**Fixed by** #461 (`transport.netty4.OpenSearchLoggingHandlerIT.testLoggingHandler`)
**Fixed by** #463 (`org.opensearch.ingest.attachment.IngestAttachmentClientYamlTestSuiteIT`)
**Fixed by** #467 (`org.opensearch.client.documentation.SearchDocumentationIT.testSearchRequestSuggestions`)
