### ISSUE TITLE
[META] Weighted Routing Issue List

### ISSUE THREAD

**Issue by anshu1106** [opensearch-project/OpenSearch#4526]
**Is your feature request related to a problem? Please describe.**

- Issues listed under this meta issue are related to Weighted Routing.

**Describe the solution you'd like**
- [x]  Feature Proposal [[Feature] Support for weighted zonal search request routing policy](https://github.com/opensearch-project/OpenSearch/issues/2859)
- [x] [[Weighted Shard Routing] Fail open weighed away AZ](https://github.com/opensearch-project/OpenSearch/issues/4735)
- [x]   API [[RFC] API for decommissioning/recommissioning zone and weighted zonal search request routing policy](https://github.com/opensearch-project/OpenSearch/issues/3639)

**Tasks**
- [x]  https://github.com/opensearch-project/OpenSearch/issues/4525
- [x]  https://github.com/opensearch-project/OpenSearch/pull/4241
- [x] https://github.com/opensearch-project/OpenSearch/pull/4272
- [x]  https://github.com/opensearch-project/OpenSearch/pull/4275
- [x] https://github.com/opensearch-project/OpenSearch/pull/4400
- [x] https://github.com/opensearch-project/OpenSearch/issues/4747
- [x] https://github.com/opensearch-project/OpenSearch/issues/5038
- [x] https://github.com/opensearch-project/OpenSearch/issues/5037
- [x] https://github.com/opensearch-project/OpenSearch/issues/5304
- [ ] https://github.com/opensearch-project/OpenSearch/issues/5754
- [x] https://github.com/opensearch-project/OpenSearch/pull/5680
- [x] https://github.com/opensearch-project/OpenSearch/issues/5873
- [x] https://github.com/opensearch-project/OpenSearch/pull/6198
- [ ] https://github.com/opensearch-project/OpenSearch/issues/6297

**Bugs**
- [x] https://github.com/opensearch-project/OpenSearch/issues/4690
- [x] https://github.com/opensearch-project/OpenSearch/issues/6056
- [x] https://github.com/opensearch-project/OpenSearch/pull/6327

**Comment by dhwanilpatel** [comment]
@anshu1106 / @pranikum  can this be closed now?
