### ISSUE TITLE
Change the "Master" nomenclature

### ISSUE THREAD

**Issue by Jon-AtAWS** [opensearch-project/OpenSearch#472]
**Is your feature request related to a problem? Please describe.**
Coming from https://github.com/opensearch-project/OpenSearch/issues/2589.

**Describe the solution you'd like**
Change all code, parameters, APIs, and documentation to refer to "leader" nodes instead of "master" nodes. 

The goal is to have a consistent term to refer to this node function, while avoiding offensive language. 

**Describe alternatives you've considered**
Other possible terminology
Manager (Keeps the"M" for abbreviations and existing diagrams)
Controller

---
Added on 04/18/2022:
**Workitems in Plugins**

- [x] https://github.com/opensearch-project/alerting/issues/320
- [x] https://github.com/opensearch-project/anomaly-detection/issues/397
- [x] https://github.com/opensearch-project/index-management/issues/285
- [x] https://github.com/opensearch-project/k-NN/issues/307
- [x] https://github.com/opensearch-project/sql/issues/463
- [x] https://github.com/opensearch-project/asynchronous-search/issues/99
- [x] https://github.com/opensearch-project/cross-cluster-replication/issues/319
- [x] https://github.com/opensearch-project/performance-analyzer/issues/152
- [x] https://github.com/opensearch-project/performance-analyzer-rca/issues/139
- [x] https://github.com/opensearch-project/security/issues/1664

**In Other Projects**

- [x] https://github.com/opensearch-project/documentation-website/issues/450
- [x] https://github.com/opensearch-project/OpenSearch-Dashboards/issues/1318

**Comment by dgomesbr** [comment]
Suggesting `Main` instead of `Leader` as standard following https://github.com/github/renaming

**Comment by sharp-pixel** [comment]
I believe the context is very different between master/main branch in a repo and master/leader node. Master nodes are not the main nodes in the cluster.

**Comment by sharp-pixel** [comment]
@Jon-AtAWS , you mention code and parameters, should we update cluster settings and APIs as well (e.g. /_cat/master)?

**Comment by Jon-AtAWS** [comment]
Ideally, we would change from master/(slave - implied) terminology across the board. So, yes, changing the _cat APIs as well.

Also, I agree "main" doesn't really fit for me. The function of the nodes is to hold and broadcast state, so "manager" is a close second for me.

**Comment by ytfi** [comment]
The terminology 'control plane' used in the kubernetes project might be more accurate than main.

---
https://kubernetes.io/docs/concepts/overview/components/

**Comment by morsik** [comment]
@Jon-AtAWS words are not offensive by themselves! It's time to start learn that finally!
There is nothing offensive in word "master" which here refers *only* to software. Don't change things that work. Don't bring stupid naming, because someone told you so.

Eh, this talk again…

Simple example: If I shout at friend in a friendly-laughy-way: "hey, stupid!" it won't be offensive. But If I should: "Hey You! Stupid!" to someone else - it is offensive. It's not words, it's context. And software context has nothing to do with offense at all.

Changing words like that is very bad and not helpful with your "real world" (I mean slavery) problem as it more like sweeping it under the rug. You're just pretending there's no anything like master-slave relation - while here - in software - it is! Let alone, we don't have slavery right now here in our countries and you're trying to wash your hands by doing such change (like something like that never happened in your country). This is just pure madness and world is broken.

Good luck with project because I'm looking into it, but please leave stupid ideas behind and do something that is really meaningful to us - users - which is actual software.

And don't get me wrong - I'm from Poland - we didn't have slavery and stuff like that, I'm just looking at all that crap from outside of America region and I may be not aware of your internal problems (but it's still your internal problems, not rest of the world!) - but from my point of view it's like: You are just trying to wash your hands from history by removing those words. And I know that because I live in country which was occupied in WW2 by Germany (not Nazis! Nazis was a political party in Germany country!) and they are trying to wash that history too in their country by forbiding telling anything about WW2 (quite similar to your word changing, isn't it?).


@ytfi apart from my personal opinion regarding this change - "Control Plane" in Kubernetes is different thing from "master"/"manager" - so definitely big no for "control plane" in ES. Especially that "Control Plane" is general term for all set of services that makes kubernetes master, database and other tools needed to operate Kube cluster - while here in ElasticSearch it's just single application (I mean: ElasticSearch; or here called: OpenSearch).

**Comment by sercasti** [comment]
I think this issue should be closed and ignored. 

If you change it to "manager", someone else will show up saying "I was raped by my manager 7 years ago, this word is offensive to me, change it"

If you change it to "leader", someone else will show up saying "my mother was abducted by a cult, and murdered by their leader, this word is offensive to me, change it".

Every minute we spend with this stupid nonsense is a waste of time. Jon, nobody is forcing you to use this product, if you don't like it, you're free to use a different one. Period.

**Comment by stockholmux** [comment]
On behalf of the maintainers of the project I agree that the term 'master' may be offensive to some people. [This project is committed to being a community where everyone can join and contribute. This means using inclusive and welcoming language](https://github.com/opensearch-project/OpenSearch/blob/main/CODE_OF_CONDUCT.md). The repo defaults to main for the branch and, in a similar vein, supporting inclusive language should extend to the API and the rest of the software as long as it can be made in a backward compatible way.

**Comment by dblock** [comment]
Thanks @stockholmux. I would kindly ask for future comments to please be limited to technical arguments, and we really appreciate all your suggestions and thoughts and contributions.

**Comment by Jon-AtAWS** [comment]
Thanks for the replies, folks. I appreciate that this is a possibly difficult, and politicized discussion. I want to encourage everyone to stick with the technical. And I want to +1 @stockholmux's comment above on a commitment to inclusivity.

**Comment by morsik** [comment]
@Jon-AtAWS sorry, but I just don't see how "inclusivity" connects with some people's personal problems with wrong understanding of word in this context. And @sercasti has point here. Any word can be offensive to anyone. If "world" decides one day that >any other word< is offensive, will we go with this bullshit over and over again?

You can't make everyone's happy - that's unwritten rule to this world. And inclusivity doesn't mean changing words - inclusivity means we welcome all people to commit to project, we welcome everybody to be part of community no matter who they are. And this I can just write in very simple Code of Conduct rules:

> Be human, not asshole.

That's all. So, be human, be welcome to other people, be nice and I encourage everyone to take part of this (and any other projects) - but please don't change real inclusivity into some political war (like even you mentioned) or some day this will turn to those people who didn't wanted such "offensive" words (which - they are just not offensive, let's be honest - and there's even prove to that because you ignored @sercasti's comment here who makes good point here).

**Comment by rursprung** [comment]
disclaimer: this is very much my personal opinion (anything not 100% technical will always be my personal opinion and not reflect any opinion of an employer or other 3rd party if not explicitly mentioned).
<politics>
i very much try not to be pulled into a political discussion here (you can only lose if you try to be part of such a discussion), but: i agree that changing words in a software (which has nothing to do with slavery) does not change anything in the real world. want to end modern-day slavery or increase equality in society? then work on that, rather than doing virtue signaling.
</politics>

with that out of the way, i have a simple technical reason why this renaming shouldn't be done: this nomenclature is part of various APIs (e.g. in the [cluster API](https://www.elastic.co/guide/en/elasticsearch/reference/7.10/cluster.html)). changing this would change the API. besides this being a breaking change (and you should break as little as possible) it'd also break compatibility with elasticsearch 7.10. and the statement was that you want to be compatible with ES 7.10 for as long as possible.

**Comment by stockholmux** [comment]
@rursprung I don't think an API change like this would happen in a disorderly fashion - like any API change, it would go through a deprecation period on a major version change.

**Comment by beejeebus** [comment]
👋 what's the best way to proceed? I'm happy to work on this with a bit of direction on how to chunk up the changes.

**Comment by CEHENKLE** [comment]
I added the 2.0 release (when we'd want to fix this) and removed "help wanted" as it's not a good starting issue for someone.

**Comment by tlfeng** [comment]
## Goal of the enhancement
Replace non-inclusive terminology "master" throughout this repository with inclusive one.

## Context
#### What is “inclusive language”?
Inclusive language is designed to avoid excluding people on the basis of gender, sexual preference, age, race, ability, etc. By using language that avoids expressions which imply or express ideas that have prejudice to any particular group of people, we aim to create a more equitable community.

#### Why using “inclusive language” is important?
Using inclusive language helps build an inclusive environment, which accepts diversity and ensures any individuals and groups feel welcome, respected, and safe. Diversity does contribute to create a fair and strong organization, and also leads to diversity of ideas, which change into creativity and innovation.

#### How to apply “inclusive language” in a software?
Replace “objectionable language in code bases and documentation. It involves assessing existing code bases and documentation, identifying potentially problematic language, then replacing terms with more preferable language.

## Solution
### Overview
To solve the issue, breaking changes will be introduced to OpenSearch, which requires backwards compatibility. The exclusionary terms exist in APIs and configurations, which will impact the compatibility with previous versions of OpenSearch and its third-party clients and tools.
We will support both and new APIs or configurations for a period of time, to let users get used to the breaking changes gradually. Considering OpenSearch follows [Semantic Versioning](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#versioning), we are going to include the new API and configuration in current minor versions, while continuing to provide support for the previous APIs and configurations for a period of time, then remove support for the old ones in a next major version.

### Substitute for the exclusionary terminology
Our proposed preferable terminologies to replace "master" (when referring to [a role of node](https://opensearch.org/docs/latest/opensearch/cluster/)): *leader*, *primary*, *manager*, *ClusterManager*, *ClusterCoordinator*

Location for the terminology:
* "master branch" in documents
* code comments
* internal variable, method and class names
* field, method, class and package names that are exposed as API in Java libraries (renaming will impact clients and plugins that depend on OpenSearch code base)
* setting names and values (including definition, yml configuration files, and tests)
* REST APIs, including endpoint (such as “cat master (https://opensearch.org/docs/opensearch/rest-api/cat/cat-master/)”), request parameter and response field/value (including tests)

### Versions to introduce the change
The ideal case is to apply inclusive naming to replace the exclusionary terminology as soon as possible, but the backwards compatibility is a key aspect to be considered, so the guideline is to add new usages with inclusive terminology as soon as possible, while keep the old usages for a while to keep the compatibility, then remove the old usages having exclusionary terminology in a future version.
Considering OpenSearch follows [Semantic Versioning](https://github.com/opensearch-project/.github/blob/main/RELEASING.md#versioning), deprecation notice MUST come at a minor version, and the breaking change, such as API removal MUST come at a major version, the plan is:
1. Add the new usages with inclusive terminology and deprecation notice for the old usages in minor versions of 1.x.
2. Remove the support for the old usages (APIs and settings) in a major version, it could be either 2.0 or 3.0.

### Procedure for the replacement
#### 1. Replace the exclusionary words that won’t impact the compatibility.
In the following location:
* Documents (but keep the content for the existing API and configuration usages)
* code comments
* Internal variable, method and class names

#### 2. Replace the old usages that having exclusionary words and impact the compatibility, then create duplicate usages with the old terms.

This step includes the following effort:

1. Replace the exclusionary word in all APIs and configurations, including their original tests.
2. Make duplicate APIs and configurations where having name change, so that calls to the old names can have the same effect with the new names.

The location that will impact the compatibility when changed:
* Configuration, includes setting name.
* REST API, includes endpoint, request and response.
* Java API, includes field, method, class, and package name.

#### 3. Add tests to check both old and new usages - configurations, REST APIs, and Java APIs.

Adding new unit tests to check the old names have got the same functionality.

#### 4. Add proper deprecation notice to the usages with exclusionary words, and documentation update.

This step includes the following effort:

1. Add proper form of deprecation notice for every changes that will impact the compatibility, including in code (such as adding `@Deprecated` annotation), console output and logs.
2. Update the user and developer documents to introduce the new usages, and notice the deprecation of old usages.

#### 5. Remove the deprecated configurations, REST APIs and Java APIs in a future major version.

## Sub-issues
- [ ] ...

## Appendix
### Location that contains the exclusionary term and will impact the compatibility when changed
**Settings**
1 Discovery and cluster formation settings
`cluster.initial_master_nodes`
`cluster.no_master_block`
`discovery.zen.no_master_block` (discovery.zen.* settings are already deprecated in Elasticsearch 7.0 (https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-7.0.0.html#deprecation-7.0.0), but code remains to be removed)
`discovery.zen.minimum_master_nodes`
`discovery.zen.master_election.*`

**API of Java library**
...

### Related issues and PRs
Existing PR before the issue created: #564

**Comment by tlfeng** [comment]
Hi all, 

We proposed to use "ClusterManager" as the replacement to the node role "master", after hearing opinions from PR #564.

"leader" is a concise name, but the responsibilities of the "master" node are not well represented in that. 
Although “ClusterCoordinator” describes the responsibilities of the "master" node, which is explained by @muralikpbhat in https://github.com/opensearch-project/OpenSearch/pull/564#issuecomment-876246886, there is an existing "[coordinating role](https://opensearch.org/docs/latest/opensearch/cluster/)" of the node. 
To make the name suitable to the role and avoiding the confusion, the name "ClusterManager" proposed by @peternied in https://github.com/opensearch-project/OpenSearch/pull/564#issuecomment-875074568 is a good option.

Unless we get a reason not to use “ClusterManager” by 11/29/2021, that's what we're going to go with. 
Thanks!

**Comment by jamshid** [comment]
All for inclusive language and retiring dated computer terms like master and slave, even though it is a bit [ironic](https://www.huffingtonpost.co.uk/amp/entry/amazon-staff-investigation_n_4335894/) here. 
But I'm worried this going to be one of the ways that elasticsearch and the opensearch fork diverge, become incompatible? I guess that's not a concern of the OpenSearch team?

**Comment by sharp-pixel** [comment]
Hi, I will start working on proposed changes. Thanks for constructive input!

**Comment by dblock** [comment]
@tlfeng Some plugins such as notifications are missing issues. Care to please create them and link from here?

**Comment by peternied** [comment]
@tlfeng Thanks for driving this effort, I would strongly recommend adding a mechanism to ensure we have removed all of these terms.  By onboarding a separate check style workflow that can be created and run automatically by plugins it ensure compliance and lets you capture metrics charting the progress to zero.

I've created a PR for this in the security plugin https://github.com/opensearch-project/security/pull/1782

**Comment by tlfeng** [comment]
@peternied Thank you for your suggestion! I knew this campaign lack a mechanism to validate the achievement, it looks like a feasible solution. 😄

**Comment by flavienbwk** [comment]
Strange for Amazon **engineers** to take a decision implying dozens of hours of refactoring (just highly political without any impact on the real world) instead of focusing on real features improving the software and asked by your community.

Just saying "this is inclusive" and "this solves a problem" doesn't mean it is nor it does... 

**How much time are you going to loose on this ?**

**Comment by peternied** [comment]
@flavienbwk I appreciate your desire to improve OpenSearch, please open an issue or create a pull request in areas you'd to see updated/enhanced.

**Comment by anasalkouz** [comment]
With 2.4 release, we have deprecated all non-inclusive usages (i.e. master, blacklist and whitelist) and we are planning to remove those deprecated usages on 3.0 release.

**Comment by morsik** [comment]
> all non-inclusive usages (i.e. master, blacklist and whitelist)

@anasalkouz after all this talk being on the other side of Ocean, I still don't see what's non-inclusive in those terms. Sorry. The world is just broken and you're doing wrong thing here.

**Comment by anasalkouz** [comment]
Closing the issue.
