### ISSUE TITLE
 [META] [Windows CI] Adding gradle check support for windows

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#4811]
**Is your feature request related to a problem? Please describe.**
Coming from #1448 - these are the steps to add gradle check support for windows via a github workflow.

- [x] #4815
- [x] #4816
- [x] #4817
- [ ] 4. Adding new windows agent profile based on the AMI in cdk.
- [ ] 5. Deploy the new cdk into the public jenkins.
- [ ] 6. Pull the 1 2 into Jenkins and try to test by manually triggering the workflow and fix until it passes.
- [ ] 7. Adjust parallel runs number and apply for more hardware for the task.

_Originally posted by @peterzhuamazon in https://github.com/opensearch-project/OpenSearch/issues/1448#issuecomment-1279479131_

We would like gradle check on windows to run against opensearch core to ensure robust testing. 
Opening this issue to track progress on these steps.

**Comment by peterzhuamazon** [comment]
Re-open the issue until gradle check is fully functional in Jenkins.

**Comment by minalsha** [comment]
Closing this issue since this is addressed and running as confirmed by @peterzhuamazon .
