### ISSUE TITLE
[META][Windows CI] Getting windows gradle check to green 

### ISSUE THREAD

**Issue by Poojita-Raj** [opensearch-project/OpenSearch#4924]
Coming from #1448, here is the meta issue tracking all failing tasks/tests on windows gradle check that need to be resolved in order to get gradle check to green. 

- [x] #4925
- [x] #4939
- [x] #4940
- [x] ResourceAwareTasksTests - these just hang for me in intellij.
- [x] HierarchyCircuitBreakerServiceTests.testFallbackG1RegionSize
- [x] PluginsServiceTests.testPluginLoadFailure & PluginsServiceTests.testPluginFromParentClassLoader
- [x] ShardIndexingPressureConcurrentExecutionTests
- [x] :build-tools:integTest - symlink tests failing for non-admin user

Cannot run opensearch as root - Grouping failures caused by running as admin: 
Should be fixed on reverting #4656

**Comment by mch2** [comment]
Running as Administrator is blocked with https://github.com/opensearch-project/OpenSearch/pull/4656. Enforced [here](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/bootstrap/Bootstrap.java#L123).  I bypassed this check and get the following failures in :server:test.  (re-ran a few times to fliter out flaky tests)

HierarchyCircuitBreakerServiceTests.testFallbackG1RegionSize
PluginsServiceTests.testPluginLoadFailure
PluginsServiceTests.testPluginFromParentClassLoader

**Comment by vibrantvarun** [comment]
@mch2 @Poojita-Raj Docker tests and running gradle check with admin

**Comment by mch2** [comment]
Listing project wise stats here, ignored means it is already ignored, not a new ignore.

rest-api-spec - 1,152 passed, 27 ignored.

**Comment by scrawfor99** [comment]
@mch2 what was your process for bypassing the admin check if you don't mind me asking? Did you incorporate it into a script or did you manually run the tests and just not the check file?

**Comment by mch2** [comment]
Ran check from intellij with admin:
passed: 15,861
ignored: 113
Failed: 9

The 9 that fail are in ShardIndexingPressureConcurrentExecutionTests.

**Comment by mch2** [comment]
from command line this test passes: 
```
./gradlew :server:test --tests "org.opensearch.indices.breaker.HierarchyCircuitBreakerServiceTests.testFallbackG1RegionSize"
```

It consistently fails from intellij.

**Comment by mch2** [comment]
@scrawfor99 for now i've simply bypassed the check in `initializeNatives` with Constants.WINDOWS == false.  We need a better solution here but it helped identify tests that still pass even with admin.

Working on getting a list of failures without admin.

**Comment by owaiskazi19** [comment]
Tested `PluginsServiceTests.testPluginLoadFailure & PluginsServiceTests.testPluginFromParentClassLoader` on admin/non-admin user with @vibrantvarun and they passed.

**Comment by vibrantvarun** [comment]
```C:\Users\Varun\project1\OpenSearch>gradlew ":server:test" --tests "org.opensearch.plugins.PluginsServiceTests.testPluginFromParentClassLoader"
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true

> Configure project :plugins:repository-hdfs
hdfsFixture unsupported, please set HADOOP_HOME and put HADOOP_HOME\bin in PATH

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Windows Server 2022 10.0 (amd64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : C:\Program Files\Amazon Corretto\jdk11.0.16_9
  Random Testing Seed   : 28955231E4B19E1A
  In FIPS 140 mode      : false
=======================================

> Task :server:test
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/C:/Users/Varun/project1/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/C:/Users/Varun/.gradle/wrapper/dists/gradle-7.5.1-all/1ehga6e77gqps5uk2kc5kf1vc/gradle-7.5.1/lib/plugins/gradle-testing-base-7.5.1.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 14s
42 actionable tasks: 1 executed, 41 up-to-date 
```


```gradlew ":server:test" --tests "org.opensearch.plugins.PluginsServiceTests.testPluginLoadFailure"
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
Starting a Gradle Daemon, 1 stopped Daemon could not be reused, use --status for details
cache fileHashes.bin (C:\Users\Varun\project1\OpenSearch\.gradle\7.5.1\fileHashes\fileHashes.bin) is corrupt. Discarding.

> Configure project :plugins:repository-hdfs
hdfsFixture unsupported, please set HADOOP_HOME and put HADOOP_HOME\bin in PATH

> Configure project :qa:os
Cannot add task 'destructiveDistroTest.docker' as a task with that name already exists.
=======================================
OpenSearch Build Hamster says Hello!
  Gradle Version        : 7.5.1
  OS Info               : Windows Server 2022 10.0 (amd64)
  JDK Version           : 11 (Amazon Corretto JDK)
  JAVA_HOME             : C:\Program Files\Amazon Corretto\jdk11.0.16_9
  Random Testing Seed   : AA86F954220D0020
  In FIPS 140 mode      : false
=======================================

> Task :server:test
Picked up _JAVA_OPTIONS: -Djava.net.preferIPv4Stack=true
OpenJDK 64-Bit Server VM warning: Ignoring option --illegal-access=warn; support was removed in 17.0
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.opensearch.bootstrap.BootstrapForTesting (file:/C:/Users/Varun/project1/OpenSearch/test/framework/build/distributions/framework-3.0.0-SNAPSHOT.jar)
WARNING: Please consider reporting this to the maintainers of org.opensearch.bootstrap.BootstrapForTesting
WARNING: System::setSecurityManager will be removed in a future release
WARNING: A terminally deprecated method in java.lang.System has been called
WARNING: System::setSecurityManager has been called by org.gradle.api.internal.tasks.testing.worker.TestWorker (file:/C:/Users/Varun/.gradle/wrapper/dists/gradle-7.5.1-all/1ehga6e77gqps5uk2kc5kf1vc/gradle-7.5.1/lib/plugins/gradle-testing-base-7.5.1.jar)
WARNING: Please consider reporting this to the maintainers of org.gradle.api.internal.tasks.testing.worker.TestWorker
WARNING: System::setSecurityManager will be removed in a future release

BUILD SUCCESSFUL in 40s
42 actionable tasks: 2 executed, 40 up-to-date
```

**Comment by Rishikesh1159** [comment]
Tested `ShardIndexingPressureConcurrentExecutionTests` in isolation. Looks like a flaky test as it was not failing. Marking it as done.
`./gradlew :server:test --tests "org.opensearch.index.ShardIndexingPressureConcurrentExecutionTests.*"`

**Comment by Poojita-Raj** [comment]
Failing for non - Administrator users: 

> Task :build-tools:integTest

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2Tar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2TarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2Tar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2TarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2Tar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2TarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2Tar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testBZip2TarDoNotPreserveFileTimestamps FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testGZipTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

org.opensearch.gradle.tar.SymbolicLinkPreservingTarIT > testTar FAILED
    java.nio.file.FileSystemException at SymbolicLinkPreservingTarIT.java:66

45 tests completed, 24 failed

> Task :build-tools:integTest FAILED

**Comment by saratvemulapalli** [comment]
For Symlink tests here is the summary so far:
Symlink creation in windows needs elevated permissions: https://docs.oracle.com/javase/7/docs/api/java/nio/file/FileSystemException.html
So we can solve the problem in 3 ways:
- Run as non-admin, instead of creating a symlink, copy the directory/content to the place we need.
- Run as admin and enable symlink permissions(very likely through Java Options).
- Skip symlinks on windows.
I
 would prefer the first approach as we would still continue to do the tests with regular permissions. You can check for file permissions using `@Before` annotation for each test and if the permissions dont exist for creating a symlink you could copy the directory.
Here are few solutions which other repositories took:
https://github.com/golang/dep/issues/773
https://github.com/srikanth-lingala/zip4j/issues/278
https://github.com/pypa/flit/issues/599
https://github.com/admb-project/admb/issues/272

**Comment by dblock** [comment]
@saratvemulapalli The question is, do we support symlinks on windows? that's pretty unusual AFAIK, I would be fine with (3) as well

**Comment by mch2** [comment]
Dumping all Files.createSymbolicLink locations:

Src:
SymbolicLinkPreservingUntarTransform.java - looks to be bypassed with https://github.com/opensearch-project/OpenSearch/pull/1433

Test code:
PidFileTests.java
SymbolicLinkPreservingTarIT.java
EvilSecurityTests.java
PluginCliTests.java

**Comment by mch2** [comment]
@dblock @saratvemulapalli I think we can safely go the skip route for `SymbolicLinkPreservingTarIT` because we skip other distros on windows and only build a zip - have opened a PR [here](https://github.com/opensearch-project/OpenSearch/pull/5023). 

All other instances of createSymbolicLink are already skipped.

**Comment by mch2** [comment]
BwcTest is the only task within check consistently failing for me now - the following passes (had to retry a few times to rule out flakiness).
```
./gradlew check -x bwcTest
```

BwcTest fails because. do not have windows builds for prior versions.

**Comment by dblock** [comment]
@mch2 Is it worth trying to produce a 1-time windows reference build manually with an older version to ensure we exercise the upgrade path in tests before we ship anything?

**Comment by mch2** [comment]
I didn't realize bwcTest isn't actually fully executed within check, only a subset, from our [docs](https://github.com/opensearch-project/OpenSearch/blob/main/TESTING.md#testing-backwards-compatibility):
> When running ./gradlew check, minimal bwc checks are also run against compatible versions that are not yet released.

 I was able to just get a full passing check on 2.4 so looking to see if that subset is sufficient.  If not then yeah we should do a manual build and run all of bwcTest.

**Comment by mch2** [comment]
Looking at a [successful check](https://build.ci.opensearch.org/job/gradle-check/6159/console) run on a 2.4 backport.  The bwc tests are running against 1.3.7 and 2.3.1.  The tests clone & compile the previous major & minor where running bwcTest alone does not for the additional versions it checks.

The following are passing for me on windows. - will edit this as they complete.
```
./gradlew :qa:mixed-cluster:1.3.7#mixedClusterTest
```
