### ISSUE TITLE
[PURIFY] Remove `Default` distribution and only create OSS distribution.

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#50]
The Default distribution is governed by Elastic license and hence needs to be removed and only create OSS distribution.

### Clean up `distribution` (@setiah)

- [x] Clean up non OSS distributions in Docker. - https://github.com/opendistro-for-elasticsearch/search/blob/main/distribution/docker
- [x] Clean up non OSS flavors in Elasticsearch Distributions. - https://github.com/opendistro-for-elasticsearch/search/blob/main/buildSrc/src/main/java/org/elasticsearch/gradle/ElasticsearchDistribution.java#L77
- [x] Clean up non OSS flavors in packaging - https://github.com/opendistro-for-elasticsearch/search/tree/main/distribution/packages
- [x] Clean up UBI Docker flavor - @saratvemulapalli 

PR: #102 #103 #110 

**Test with failures**

- [x] DistributionDownloadPluginFuncTest. bwc version can be resolved
- [x] DistributionDownloadPluginFuncTest. current version can be resolved
- [x] DistributionDownloadPluginFuncTest. released version can be resolved
- [x] DistributionDownloadPluginFuncTest. transformed versions are kept across builds
- [x] DistributionDownloadPluginFuncTest. transforms are reused across projects
- [x] TestClustersPluginFuncTest. custom distro folder created for tweaked cluster distribution
- [x] TestClustersPluginFuncTest. test cluster distribution is configured and started
- [x] InternalDistributionBwcSetupPluginFuncTest. builds distribution from branches via archives assemble
- [x] InternalDistributionBwcSetupPluginFuncTest. bwc distribution archives can be resolved as bwc project artifact
- [x] InternalDistributionBwcSetupPluginFuncTest. bwc expanded distribution folder can be resolved as bwc project artifact
- [x] InternalDistributionDownloadPluginFuncTest. resolves current version from local build
- [x] InternalDistributionDownloadPluginFuncTest. resolves expanded bwc versions from source

### Remove Flavor Enums (@adnapibar)

- [x] remove the Flavor support
- [x] remove -oss flag dependencies in package and build tests

PR: #104 

**Test with failures**

`./gradlew ':qa:rolling-upgrade:v6.8.15#oneThirdUpgradedTest'`

- [x] org.elasticsearch.upgrades.IndexingIT.testIndexing
- [x] org.elasticsearch.upgrades.RecoveryIT.testUpdateDoc
- [x] org.elasticsearch.upgrades.RecoveryIT.testSoftDeletesDisabledWarning
- [x] org.elasticsearch.upgrades.RecoveryIT.testRelocationWithConcurrentIndexing
- [x] org.elasticsearch.upgrades.RecoveryIT.testAutoExpandIndicesDuringRollingUpgrade
- [x] org.elasticsearch.upgrades.RecoveryIT.testRetentionLeasesEstablishedWhenPromotingPrimary
- [x] org.elasticsearch.upgrades.RecoveryIT.testRecoveryWithConcurrentIndexing
- [x] org.elasticsearch.upgrades.RecoveryIT.testCloseIndexDuringRollingUpgrade

`./gradlew ':qa:mixed-cluster:v6.8.15#mixedClusterTest'`

- [x] org.elasticsearch.backwards.IndexingIT.testUpdateSnapshotStatus
- [x] org.elasticsearch.backwards.IndexingIT.testIndexVersionPropagation
- [x] org.elasticsearch.backwards.MixedClusterClientYamlTestSuiteIT

### Clean up `buildSrc` (@setiah)
- [x] Remove logic to check the distribution flavor and make the OSS as the only option.
