### ISSUE TITLE
[Version] Rebase version for OpenSearch to 1.0.0 

### ISSUE THREAD

**Issue by adnapibar** [opensearch-project/OpenSearch#500]
This is the meta issue to track the effort for rebase versioning for OpenSearch as discussed in #417. The versioning work is being done in the feature branch `opensearch/rebaseVersion`. All PRs for this issue need to be created against this feature branch.

**Tasks**

- [x] Task `:rest-api-spec:yamlRestTest` FAILED (PR #501)
     - java.lang.IllegalArgumentException: unable to consistently parse [cluster.routing.allocation.disk.watermark.low=1b]...
     - java.lang.AssertionError: remove this service once unsafe upgrades are no longer needed

- [x] Task `:modules:analysis-common:test` FAILED  (PR #501) 
     - "org.opensearch.analysis.common.HighlighterWithAnalyzersTests.testNgramHighlightingWithBrokenPositions" 
     - ﻿"org.opensearch.analysis.common.HighlighterWithAnalyzersTests.testMultiPhraseCutoff"
     - "org.opensearch.analysis.common.HighlighterWithAnalyzersTests.testSynonyms"
     -  "org.opensearch.analysis.common.HighlighterWithAnalyzersTests.testPhrasePrefix"

- [x] Task `:modules:reindex:test` FAILED (PR #501)
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryOnReadOnlyIndex
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testSlices
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testMissingSources
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByMatchQuery
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testBasics
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryOnReadOnlyAllowDeleteIndex
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithRouting
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testMultipleSources
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithMissingIndex
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithDateMath
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithOneIndex
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.testDeleteByQueryWithMultipleIndices
    - org.opensearch.index.reindex.DeleteByQueryBasicTests.classMethod
    - org.opensearch.index.reindex.ReindexSingleNodeTests.testDeprecatedSort
    - org.opensearch.index.reindex.ReindexSingleNodeTests.classMethod
    - org.opensearch.index.reindex.RestUpdateByQueryActionTests.testParseEmpty
    - org.opensearch.index.reindex.RestUpdateByQueryActionTests.testTypeInPath
    - org.opensearch.index.reindex.RestUpdateByQueryActionTests.classMethod
    - org.opensearch.index.reindex.ReindexFromRemoteBuildRestClientTests.testBuildRestClient
    - org.opensearch.index.reindex.ReindexFromRemoteBuildRestClientTests.testHeaders
    - org.opensearch.index.reindex.ReindexFromRemoteBuildRestClientTests.classMethod

- [x] Task `':server:test` FAILED  (PR #501)
    - org.opensearch.ExceptionSerializationTests.* (31 failures)
    - org.opensearch.discovery.zen.NodeJoinControllerTests.testRejectingJoinWithIncompatibleVersion

- [x] Task `:modules:transport-netty4:test` FAILED  (PR #501)
    - org.opensearch.transport.netty4.SimpleNetty4TransportTests.* (3 tests)
    - org.opensearch.transport.netty4.SimpleNetty4TransportTests.testTransportStatsWithException
    - org.opensearch.transport.netty4.SimpleNetty4TransportTests.testErrorMessage
    - org.opensearch.transport.netty4.SimpleNetty4TransportTests.testMessageListeners

- [x] `ParentChildClientYamlTestSuiteIT`
    - [test] [yaml=/30_inner_hits/Test two sub-queries with only one having inner_hits] before test
