### ISSUE TITLE
[Meta] Promote Segment Replication out of experimental.

### ISSUE THREAD

**Issue by mch2** [opensearch-project/OpenSearch#5147]
More to come on this list.

- [x] #4478
- [x] #4554 
- [x] #5240
- [x] #5242
- [x] #4102 
- [x] #6045
- [x] https://github.com/opensearch-project/OpenSearch/issues/6210
- [x] https://github.com/opensearch-project/OpenSearch/issues/6027

Improvements:
- [x] https://github.com/opensearch-project/OpenSearch/issues/5743
- [x] https://github.com/opensearch-project/OpenSearch/issues/6121

Bugs:
- [x] #4665 
- [x] #5669 
- [x] https://github.com/opensearch-project/OpenSearch/issues/5701
- [x] https://github.com/opensearch-project/OpenSearch/issues/5706
- [x] https://github.com/opensearch-project/OpenSearch/issues/5946
- [x] https://github.com/opensearch-project/OpenSearch/issues/6578

**Comment by anasalkouz** [comment]
Now, you can track the progress of Segment Replication on this [board](https://github.com/orgs/opensearch-project/projects/99/views/1).
If you are interested and want to contribute, feel free to pick any of the pending task.
cc: @mattweber

**Comment by DarshitChanpura** [comment]
Hey @mch2 @andrross. Is the issue still on track to be completed by code-freeze on Apr-17 for `v2.7.0`. If not, it will be marked for next release `v2.8.0`

**Comment by anasalkouz** [comment]
Yes, it's on track for 2.7.

**Comment by mch2** [comment]
Closing, tracking of work moved to project https://github.com/orgs/opensearch-project/projects/99
