### ISSUE TITLE
[META] Migrate AD backend plugin to AD Extension

### ISSUE THREAD

**Issue by owaiskazi19** [opensearch-project/OpenSearch#5224]
**Is your feature request related to a problem? Please describe.**
Based on https://github.com/opensearch-project/OpenSearch/issues/2447 and https://github.com/opensearch-project/OpenSearch/issues/1422. We are working on migrating Anomaly Detection backend plugin to extension. This issue tracks the features of AD:
- [x] https://github.com/opensearch-project/OpenSearch/issues/3635
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/217
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/211
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/353
- [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/451
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/373
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/374
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/375
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/376
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/377
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/378
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/379
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/380
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/381
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/382
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/383
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/384
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/385
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/685
 - [x] https://github.com/opensearch-project/opensearch-sdk-java/issues/675
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/720

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by dbwiddis** [comment]
Revised sub-issues (I can't edit into original comment):
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/353
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/373
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/374
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/375
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/376
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/377
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/378
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/379
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/380
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/381
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/382
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/383
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/384
 - [ ] https://github.com/opensearch-project/opensearch-sdk-java/issues/385

**Comment by owaiskazi19** [comment]
Closing this as extensions is released as experimental feature
