### ISSUE TITLE
[Feature/extensions] Meta: Merge back to main tracking issue

### ISSUE THREAD

**Issue by ryanbogan** [opensearch-project/OpenSearch#5263]
This is a tracking issue for merging the feature/extensions branch into main, and then backported to 2.x.

The merge will be performed in four steps, and all functionality will be behind a feature flag.

Meta-issue for experimental release: [139](https://github.com/opensearch-project/opensearch-sdk-java/issues/139)

Sub-issues:
- [x] https://github.com/opensearch-project/OpenSearch/issues/5264
- [x] https://github.com/opensearch-project/OpenSearch/issues/5271
- [x] https://github.com/opensearch-project/OpenSearch/issues/5272
- [x] https://github.com/opensearch-project/OpenSearch/issues/5273
