### ISSUE TITLE
[META] Implement a Communication Mechanism Between Job Scheduler as a Plugin and Anomaly Detection as an Extension

### ISSUE THREAD

**Issue by joshpalis** [opensearch-project/OpenSearch#5585]
## Problem
Anomaly Detection currently takes Job Scheduler as a dependency in order to schedule Anomaly Detectors to run for a specified time interval. Job Scheduler has an SPI (Service Provider Interface) design and provides the [JobSchedulerExtension interface](https://github.com/opensearch-project/job-scheduler/blob/main/spi/src/main/java/org/opensearch/jobscheduler/spi/JobSchedulerExtension.java) which Anomaly Detection implements for its own Job Runner. Job Scheduler also implements the [Extensible Plugin Interface](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/plugins/ExtensiblePlugin.java) which provides the capability to class load Anomaly Detection's implementations for the Job Scheduler Extension. This is the currently plugin architecture that enables Anomaly Detection to use Job Scheduler to schedule its own jobs, however in the case of Anomaly Detection as an extension running in a separate JVM process, the SPI design is not compatible.

## Objective
In order to provide Anomaly Detection as an extension with the capability to schedule its own jobs, we must design and develop a communication mechanism between Anomaly Detection Extension and Job Scheduler as a plugin installed within OpenSearch. This communication mechanism should be integrated alongside the current plugin architecture in order to support both plugins and extensions.

## AD Features Dependent on Job Scheduler Integration
In order to achieve support for Anomaly Detection Extension to schedule jobs, the communication mechanism must be able to facilitate the workflow triggered by the following APIs.

- https://github.com/opensearch-project/opensearch-sdk-java/issues/216

## Start Detector Workflow
The Start Detector API triggers the process in which Anomaly Detector Jobs are configured and scheduled, therefore it is important to first understand the interactions of Job Scheduler and Anomaly Detection throughout this process within the current plugin architecture in order to determine how to build around this. The following workflow diagram describes how Job Scheduler class loads AD's JobSchedulerExtension implementations and also traces the events that invoke this job scheduling and execution. 

Note : For Anomaly Detector jobs, Job Scheduler is used only to schedule and execute **real-time** anomaly detectors, therefore we have omitted exploration of the historical analysis workflow. 

## Design for Communication Mechanism between Plugins and Extensions
*Issues will be created and linked here*
- [x] **Work item 1** : https://github.com/opensearch-project/opensearch-sdk-java/issues/262
- [x] **Work Item 2** : opensearch-project/opensearch-sdk-java#274 
- [x] **Work Item 3** : https://github.com/opensearch-project/opensearch-sdk-java/issues/424
- [x] **Work Item 4** https://github.com/opensearch-project/opensearch-sdk-java/issues/309
- [x] **Work Item 5** https://github.com/opensearch-project/opensearch-sdk-java/issues/363
- [x] **Work Item 6** https://github.com/opensearch-project/opensearch-sdk-java/issues/370

Note : The work items above correspond with the purple boxes found on the start detector workflow diagram, which indicate when these various request/responses should executed 

![StartDetector (3)](https://user-images.githubusercontent.com/99766446/208555868-484b4c33-a56c-43b0-8ada-68b8e1ce1bff.png)
