### ISSUE TITLE
[META] [Feature/Identity] RoadMap for Identity in OpenSearch

### ISSUE THREAD

**Issue by DarshitChanpura** [opensearch-project/OpenSearch#5834]
# Supporting Native AuthN/AuthZ with Core

Every thing done within OpenSearch should be permissible, no matter the source.  This is why we need to move authentication and authorization into OpenSearch core codebase.  The plugin model is very useful for optional things, security primitives are not one of them.

**Getting these new native concepts out to OpenSearch developers and customers quickly for feedback and iteration is our aim to achieve this.**

_Terminology:_
* Subject: An individual, process, or device that causes information to flow among objects or change to the system state.
* Principal: An application-wide identifier that is persisted

## Minimal viable system

To move quickly, and provide a surface area for experimentation we are going to cut some corners.  This effort will first be within a feature branch, then be controlled via an experimental feature flag shipped with OpenSearch distribution, finally made available for adoption with backwards compatible support.

- [ ] Ship with an experimental feature flag
- [ ] Introduce Identity as a module. PR #5583

### Blog Posts

This section is for tracking any updates that would be made Identity related blog-posts.

- [ ] Identity Blog Post PR https://github.com/opensearch-project/project-website/pull/1149
- [ ] Introducing Identity use-cases PR #5513

The following are the areas of focus to create this minimal set of functionality along with an estimated complexity to develop to help in terms of understanding the projects.  Complexity attempts to score uncertainty, not effort, delivering more complex items implies more prototypes/design reviews.

### Identity Concepts

- [ ] #3

- [OpenSearch requests should know the identity of the caller #3846](https://github.com/opensearch-project/OpenSearch/issues/3846)
- [Add support for using User Identity in extensions #37](https://github.com/opensearch-project/opensearch-sdk-java/issues/37)
- [Create a permissions check API for extensions to us with custom resources #40](https://github.com/opensearch-project/opensearch-sdk-java/issues/40)

### Principal Identifiers
- [ ] [Complexity 2] Principal identity for Opensearch requests to/from extensions PR #4299 
- [ ] [Complexity 3] https://github.com/opensearch-project/OpenSearch/issues/4485 

### Delegate Execution

- [ ] [Complexity 5] Strategize authority Delegation via JWT Tokens PR #4826
- [ ] [Complexity 5] Delegate any tasks to system subject or interactive user sessions. The default mechanism should use access tokens that are cryptographically secured against tampering. 

### Access Tokens

- [ ] [Complexity 5] Add APIs to: generate token for principal, refresh token, expire all refresh tokens
- [ ] [Complexity 5] Secrets generation / storage

### Internal Identity Provider

- [ ] [Complexity 2] Create basic in memory user store for username/password based authentication PR #4659
- [ ] [Complexity 3] Persistently store the users across the cluster in a way that is kept consistent PR #5613
 
### CRUD operations on Subject

- [ ] [Complexity 3] Allow CRUD operations for subjects for system processes or for users to run on their behalf PR #4741
- [ ] [Complexity 3] Add REST API for subject creation 

### Authentication

- [ ] [Complexity 3] Support basic username/password authentication PR #4798
- [ ] [Complexity 3] Support bearer token authentication PR #5611

### Permissions/Authorization

- [ ] [Complexity 3] Design the permissions model and any potential changes. Notability existing permissions based on action names will be on deprecation path PR #5698
- [ ] [Complexity 3] Adding Permissions check API #4516
- [ ] [Complexity 2] Registration of permissions from all permissions sources in core
- [ ] [Complexity 5] Registration of permissions for extension/plugins
- [ ] [Complexity 2] Have a process where from a Subject a list of permissions is generated so they can be checked
- [ ] [Complexity 8] For the new permission come up with a structured naming convention building blocks, such as {SourceName}{ResourceName}{ActionVerb} -> Ad.Detector.Create.  Additionally come up with a 'blessed' list of action verbs to prevent http methods from being used as action names.
- [ ] [Complexity 2] With the new naming convention create updated names for all core permissions
- [ ] [Complexity 2] Confirm evaluation of permissions for Actions in core
- [ ] [Complexity 2] Grant permissions to a subject, through the identity provider

### TODOs

This section contains all the current and pending TODO items in the identity code. 

- [ ] TODOs - Meta issue to keep track of all todos introduces while developing

(The following section should be moved into the meta issue above.)
You can search for comments using the phrase below

#### `authn` library
- [ ] AuthenticationTokenHandler.java
         - check for other type of HeaderTokens
- [ ] BasicAuthenticationIT.java
         - Update this test to check for missing-header response, once that is implemented
- [ ] InternalUsersStore.java
         - Check if there is a better way around this
 - [ ] InternalRealm.java
         - load this at cluster start
         - Revisit this
         - Check if this is correct
         - Expose all the operations below as a rest API
         - Add restrictions around who can do this <- 3 occurrences
         - 1. Are we supporting this. 2. If so add restrictions around who can do this

#### `identity` module
- [ ] build.gradle
         - move the integ tests into qa module after this is moved out of sandbox?
- [ ] IdentityPlugin.java
         - revisit this
- [ ] SecurityFilter.java
         - Get jwt here and verify
         - Move this logic to right after successful login
         - Figure out where internal actions are invoked and create token on invocation
- [ ] SecurityRestFilter.java
         - Handle anonymous Auth - Allowed or Disallowed (set by the user of the system) - 401 or Login-redirect ??
         - Uncomment this once it is decided to proceed with this workflow
         - Change this to false once there is a decision on what to do with requests that don't have auth Headers
- [ ] HttpSmokeCaseWithIdentity.java
         - not sure why ThreadLeakScope.NONE is required

## Future Scope

The following items are not required for the critical path delivery and will likely be started on following the stabilization of the MVP components.

### Loading from configuration

- [ ] [Complexity 8] Reuse/replace existing YAML configuration

### Index View(s)

- [ ] [Complexity 8] Might be further expanded into a generic 'resource collection'

### Authorization Abstractions

- [ ] [Complexity 8] Roles, groups, trees, or other intermediate representations of permissions.

### Rename plugin permissions (OOB?)

- [ ] [Complexity 8] Drive the renaming of permissions through all the existing plugins.

### Migration from Security Plugin

- [ ] [Complexity 13] How to do a complete, or partial migration(s) from the security plugin.

### Authentication providers

- [ ] [Complexity 8] OIDC, SAML, and other(s).

### Security testing

- [ ] [Complexity 8] How to author test cases for security features, and building out these test cases for all critical scenarios

### Identity Information

- [ ] [Complexity 8] Allow retrieve/storage of user information

**Comment by dblock** [comment]
This is quite thorough!

I'd be careful about saying "thing", and get more specific. 

Every ~thing done within~ resource and external api call in OpenSearch should be unambiguously permissible, nomatter the source. This is why we need to move authentication and authorization into OpenSearch core codebase. The plugin model is very useful for optional things, security primitives are not one of them. 

We also need to say something like "the starting process needs to launch with a built-in identity. Every thread spawned, and every task scheduled should be running under a clear identity."
