### ISSUE TITLE
[Meta] Cluster health api to support awareness attribute level health

### ISSUE THREAD

**Issue by nishchay21** [opensearch-project/OpenSearch#5851]
Please comment on this issue with any feedback on our recent release.

This is a meta issue for all work relating to awareness attribute health.

Core changes:

- [X] Add API to check per awareness attribute value health. https://github.com/opensearch-project/OpenSearch/issues/5230
- [X] Adding core changes for API to check per awareness attribute health https://github.com/opensearch-project/OpenSearch/pull/5231
- [X] Awareness health API rest and transport layer changes #5694 https://github.com/opensearch-project/OpenSearch/pull/5694

Doc Changes:
- [X] [DOC] API to check per awareness attribute health https://github.com/opensearch-project/documentation-website/issues/2281

**Comment by andrross** [comment]
Closing as all linked issues have been completed
