### ISSUE TITLE
Internal User Rest APIs

### ISSUE THREAD

**Issue by peternied** [opensearch-project/OpenSearch#5883]
### Dependency
Requires `Internal User Management APIs` tasks

### Use case:
There are Rest APIs `POST/GET/PUT/DELETE` via `/identity/user/{username}` mapped the the internal actions

### Acceptance Criteria:
- Integration tests for each API

**Comment by peternied** [comment]
@DarshitChanpura We've gone back and forth on how this an the related tasks should be structured to express, designing an API, creating customer facing REST APIs, and finally building up integration testing.  Could you pilot this and provide a recommendation if you'd like to structure this differently.

**Comment by DarshitChanpura** [comment]
## APIs that will be introduced:

- [ ] Create a user via PUT - #5990 
- [ ] Update a user via PUT - #5990
- [ ] Read a user via GET - #6189 
- [ ] Read all users via GET - #6189 
- [ ] Delete a user via DELETE - #6189

## Sample request and responses:

<details>
<summary>Create a user - PUT:</summary>

```
➜ curl -XPUT http://new-user:password@localhost:9200/_identity/api/users/apitest --data '{ "password" : "apitest", "attributes": { "attr1": "val1"}, "permissions": ["indices:admin:read"] }' -H "Content-type: application/json" | jq

{
  "successful": true,
  "username": "apitest",
  "message": "apitest created successfully."
}
```
</details>

<details>
<summary>Read a user - GET:</summary>

```
➜ curl -XGET http://new-user:password@localhost:9200/_identity/api/users/apitest | jq

{
  "apitest": {
    "attributes": {
      "attr1": "val1"
    },
    "permissions": [
      "indices:admin:read"
    ]
  }
}
```
</details>

<details>
<summary>Update a user - PUT:</summary>

```
➜ curl -XPUT http://new-user:password@localhost:9200/_identity/api/users/apitest --data '{ "password" : "random",  "attributes": { "attr1": "val2", "attr2":"val1"}, "permissions": ["indices:admin:create"]}' -H "Content-type: application/json" | jq

{
  "successful": true,
  "username": "apitest",
  "message": "apitest updated successfully."
}
```
</details>

<details>
<summary>Read all users - GET:</summary>

```
➜ curl -XGET http://new-user:password@localhost:9200/_identity/api/users | jq

{
   "users":[
      {
         "new-user": {
           "attributes": {
             "attribute1": "value1"
           },
           "permissions": [
             "indices:admin:create",
             "indices:data:write:index",
             "indices:data/read/search|my-index*,other-index*",
             "indices:data/read/search|third-index*",
             "indices:data/read/search|my*"
           ]
         }
      },
      ....
      {
         "apitest": {
            "attributes": {
               "attr1": "val2",
               "attr2": "val1"
            },
             "permissions": [
               "indices:admin:create"
            ]
         }
      },
      .....
   ]
}
```
</details>

<details>
<summary>Delete a user - DELETE:</summary>

```
➜ curl -XDELETE http://new-user:password@localhost:9200/_identity/api/users/apitest | jq

{
  "successful": true,
  "message": "apitest deleted successfully."
}
```
</details>

<br>
This is the current request/response structure. If anyone has  suggestions we can discuss upon this.
