### ISSUE TITLE
[Meta] GA for searchable snapshots reading legacy versions

### ISSUE THREAD

**Issue by kartg** [opensearch-project/OpenSearch#5948]
**Is your feature request related to a problem? Please describe.**
This meta-issue tracks follow-up items to https://github.com/opensearch-project/OpenSearch/issues/5451.

Today, the ability for [searchable snapshots](https://opensearch.org/docs/latest/opensearch/snapshots/searchable_snapshot/) to read snapshots written by legacy versions has been merged to `main` (https://github.com/opensearch-project/OpenSearch/pull/5812) and `2.x` (https://github.com/opensearch-project/OpenSearch/pull/5429) behind a feature flag. This feature is useful for users storing data for long periods of time (and thereby across major version upgrades) for log analysis or audit use-cases. As an example, see https://github.com/opensearch-project/OpenSearch/issues/5443

**What is a legacy version?** (adapted from [here](https://github.com/opensearch-project/OpenSearch/issues/5451#issuecomment-1338818760))

IMO a "legacy" version is any version older than OpenSearch's standard backwards compatibility guarantee (one prior major version). So:
* For `3.x`, OpenSearch 1.x (or ElasticSearch 7.10.2) and lower versions are considered legacy
* For `2.x` -> ElasticSearch 6.x and lower
* For `1.x` -> ElasticSearch 5.x and lower

I think these should also have a lower bound, but I don't have a value in mind at this time. The [current implementation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectory.java#L41) only goes as far back as ElasticSearch 6.0.

---

**Follow-up items**

- [ ] Implement a testing strategy for searchable snapshots reading legacy versions.

Currently, no integration tests exist for the feature. Individual classes are unit-tested using a compressed ElasticSearch 6.0 index directory ([README](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/test/resources/indices/bwc/es-6.3.0/README.md)). Ideally we should be able to produce tests that provide confidence beyond simply "best-effort" (as is currently the case with the [Lucene 9 implementation](https://github.com/apache/lucene/commit/c1ae6dc07c9a988533cbe7176bdeb49e2fca1d9c))

- [x] Remove the workarounds in Lucene access

Currently, the "expert" `readLatestCommit` API is package-private in Lucene, which prevents OpenSearch from accessing it directly. Thus, the code path uses [a workaround](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/common/lucene/Lucene.java#L139-L145). We should seek to remove this workaround and use the expert API directly, by submitting upstream changes to Lucene if need be.

- [ ] Expand support to ElasticSearch 5.x

The [current implementation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectory.java#L41) only goes as far back as ElasticSearch 6.0. Users would benefit from expanding this feature to support ElasticSearch 5.x snapshots as well.

**Comment by kartg** [comment]
> Expand support to ElasticSearch 5.x

> The [current implementation](https://github.com/opensearch-project/OpenSearch/blob/main/server/src/main/java/org/opensearch/index/store/remote/directory/RemoteSnapshotDirectory.java#L41) only goes as far back as ElasticSearch 6.0. Users would benefit from expanding this feature to support ElasticSearch 5.x snapshots as well.

This may not be viable because [Lucene does not support reading indices older than 7.0](https://github.com/apache/lucene-solr/pull/2212#discussion_r559385012) due to the Segment Infos format.

**Comment by kartg** [comment]
> Remove the workarounds in Lucene access

This is being tracked here - https://github.com/opensearch-project/OpenSearch/issues/7084

**Comment by andrross** [comment]
This experimental feature was never taken any further and was removed in #18592. I'm going to close this issue as we'll have to revisit the whole implementation if this is to be picked up again.
