### ISSUE TITLE
[META] Search Pipelines - GA

### ISSUE THREAD

**Issue by macohen** [opensearch-project/OpenSearch#6278]
This issue tracks all work that must be included for us to make Search Pipelines generally available. 

Search Pipelines will enable builders to configure an ordered list of processors that take queries, results, or both to enable transformations that typically occur in client applications either before queries are submitted to OpenSearch or after results are retrieved. This feature will make it easy to integrate and test result re-rankers, query re-writers, and other features to send data to other applications. We also want to enable features like running multiple pipelines per index, comparing results between pipelines, and setting a default pipeline for an index. 

This will enable partners to more easily integrate their features with OpenSearch and empower customers to focus more energy on building their applications and less time integrating/building custom processors.

**Describe alternatives you've considered**
See https://github.com/opensearch-project/search-processor/issues/80 for the RFC for the project. We want your feedback!

- [x] https://github.com/opensearch-project/search-processor/issues/80
- [x] https://github.com/opensearch-project/search-processor/issues/97
- [x] https://github.com/opensearch-project/search-processor/issues/38
- [x] https://github.com/opensearch-project/search-processor/issues/36
- [x] https://github.com/opensearch-project/search-processor/issues/44
- [x] https://github.com/opensearch-project/documentation-website/issues/2560
- [x] https://github.com/opensearch-project/search-processor/issues/115
- [x] #6717 
- [x] #6719
- [x] #6723

**Comment by msfroh** [comment]
Commenting here, since I can't edit the issue to enumerate the tasks that need to be completed in time for a 2.7 release:

1. Prototype / initial implementation: https://github.com/opensearch-project/search-processor/issues/97 / https://github.com/opensearch-project/OpenSearch/pull/6587
2. Pipeline specified in a search request (ad hoc execution).
3. Index default pipelines
4. Processors that modify both request and response ("bracket processor").
5. Search pipeline metrics (at least on par w/ ingestion pipeline metrics).
6. Processor toolbox
    1. ~~Filter query request processor~~ (done as part of prototype)
    2. Rename field response processor
    3. Scripting (painless/mustache) request processor
    4. Scripting (painless/mustache) response processor
    5. Conditional request processor
    6. Conditional response processor
    7. TODO: Other ideas that come up

I'll create tasks for each of these, which we can link from the issue description.

**Comment by noCharger** [comment]
Some other feastures
1. Add search pipeline support in OpenSearch JS client
2. https://github.com/opensearch-project/dashboards-search-relevance/issues/182 (depend on 1)

**Comment by msfroh** [comment]
This issue tracks task that need to be completed to before search pipelines are generally available, like metrics, documentation, integration w/ OpenSearch Dashboards.

**Comment by macohen** [comment]
I'm removing a couple of line items
#6722 
#6907 
from the original issue list as they are not required for GA for 2.9. 

@noCharger do you think that the three features here https://github.com/opensearch-project/OpenSearch/issues/6278#issuecomment-1514115436 are critical for GA?

**Comment by noCharger** [comment]
> I'm removing a couple of line items #6722 #6907 from the original issue list as they are not required for GA for 2.9.
> 
> @noCharger do you think that the three features here [#6278 (comment)](https://github.com/opensearch-project/OpenSearch/issues/6278#issuecomment-1514115436) are critical for GA?

Nope, 3 is done. 1 and 2 are supportive features.

**Comment by macohen** [comment]
Search Pipelines is GA in 2.9
