### ISSUE TITLE
Support rolling upgrades to OpenSearch 1.0 from ODFE 1.13 and ES 7.10.x

### ISSUE THREAD

**Issue by dblock** [opensearch-project/OpenSearch#671]
Upgrading your cluster from ElasticSearch to OpenSearch and OpenSearch Dashboards is just like upgrading your cluster between versions of ElasticSearch and Kibana. Specifically, OpenSearch supports rolling upgrades and restart upgrades from ElasticSearch 6.8.0 through ElasticSearch 7.10.2 and to OpenSearch 1.0. OpenSearch Dashboards supports restart upgrades from Kibana 6.8.0 through Kibana 7.10.2 and to OpenSearch Dashboards 1.0.

- [ ] OpenSearch Dashboards, see https://github.com/opensearch-project/OpenSearch-Dashboards/issues/334. 
- [x] OpenSearch Plugins, see https://github.com/opensearch-project/opensearch-plugins/issues/12. 
- [x] OpenSearch itself, see https://github.com/opensearch-project/OpenSearch/issues/640.
- [x] Upgrade/migration guide, https://github.com/opensearch-project/OpenSearch/issues/801

We have [asked the community](https://discuss.opendistrocommunity.dev/t/upgrade-path-to-opensearch/5788) regarding the upgrade path to OpenSearch. Please continue adding your comments.

**Additional context**

![](https://media.giphy.com/media/3ohuPrNwUE7j3Zm7kc/giphy-downsized.gif)

**Comment by saratvemulapalli** [comment]
For OpenSearch we still have to understand what we have broken and what needs to be backwards compatible. 
For example plugins: https://github.com/opensearch-project/opensearch-plugins/issues/12

Here is an issue we opened to track them and I am confident this just scratching the surface: https://github.com/opensearch-project/OpenSearch/issues/640

**Comment by saratvemulapalli** [comment]
Pasting it back from the earlier issue since this is important.
These are all the items which we should consider while working on the drop in upgrades.

Ordering of upgrading
Naming conventions
Upgrade time-lag (aka downtime)
Replication
Security
Downstream Dependencies
Upgrade alerting and notifications
Limits
Performance
Availability
Latency
Compatibility Matrix
Downgrade
APIs

**Comment by dblock** [comment]
> Can we convert this into a meta issue and track incremental issues the community can help pick off?

What's a "meta" issue? How do I convert this?

**Comment by nknize** [comment]
Blocked by #801  awaiting feedback.

**Comment by dblock** [comment]
#801 is resolved, however we don't have documentation for migrating from Kibana OSS to OpenSearch Dashboards, for which I opened https://github.com/opensearch-project/documentation-website/issues/71

**Comment by dblock** [comment]
Closing this with https://github.com/opensearch-project/documentation-website/issues/71 resolved.

**Comment by shawnz** [comment]
Hi there, please also consider supporting upgrades directly from ES 7.10.x to OS 1.1. If this path is not supported it will be somewhat inconvenient for us as OS 1.0 is not available as an RPM distribution.

See also https://github.com/opensearch-project/OpenSearch-Dashboards/issues/334#issuecomment-904901805
