### ISSUE TITLE
[META] Track plugin backports refactoring XContent from common to core namespace 

### ISSUE THREAD

**Issue by nknize** [opensearch-project/OpenSearch#6841]
From #6470 the following issues track backporting XContent refactor from `common` to `core` namespace on all affected downstream plugins:

- [ ] alerting: https://github.com/opensearch-project/alerting/issues/837
- [ ] anomaly-detection: https://github.com/opensearch-project/anomaly-detection/issues/846
- [ ] asynchronous-search: https://github.com/opensearch-project/asynchronous-search/issues/261
- [ ] common-utils: https://github.com/opensearch-project/common-utils/issues/391
- [ ] cross-cluster-replication: https://github.com/opensearch-project/cross-cluster-replication/issues/756
- [ ] data-prepper: https://github.com/opensearch-project/data-prepper/issues/2404
- [ ] geospatial: https://github.com/opensearch-project/geospatial/issues/249
- [ ] job-scheduler: https://github.com/opensearch-project/job-scheduler/issues/350
- [ ] k-nn: https://github.com/opensearch-project/k-NN/issues/821
- [ ] ml-commons: https://github.com/opensearch-project/ml-commons/issues/828
- [ ] neural-search: https://github.com/opensearch-project/neural-search/issues/146
- [ ] notifications: https://github.com/opensearch-project/notifications/issues/645
- [ ] opensearch-migrations: https://github.com/opensearch-project/opensearch-migrations/issues/123
- [ ] opensearch-oci-object-storage: https://github.com/opensearch-project/opensearch-oci-object-storage/issues/44
- [ ] opensearch-plugins (meta): https://github.com/opensearch-project/opensearch-plugins/issues/212
- [ ] opensearch-sdk-java: https://github.com/opensearch-project/opensearch-sdk-java/issues/614
- [ ] performance-analyzer: https://github.com/opensearch-project/performance-analyzer/issues/406
- [ ] performance-analyzer-rca: https://github.com/opensearch-project/performance-analyzer-rca/issues/309
- [ ] reporting: https://github.com/opensearch-project/reporting/issues/677
- [ ] search-processor: https://github.com/opensearch-project/search-processor/issues/120
- [ ] security: https://github.com/opensearch-project/security/issues/2588
- [ ] security-analytics: https://github.com/opensearch-project/security-analytics/issues/382
- [ ] simple-schema: https://github.com/opensearch-project/simple-schema/issues/72
- [ ] spring-data-opensearch: https://github.com/opensearch-project/spring-data-opensearch/issues/116
- [ ] sql: https://github.com/opensearch-project/sql/issues/1475

Going forward this will not be a common practice of the core repo as downstream projects should not stall progress PRs for weeks on end.

**Comment by nknize** [comment]
Affected plugin repos have been assigned the `v2.7.0` label for the next 2.x release.

**Comment by nknize** [comment]
All issues have been updated w/ notice of merge

**Comment by DarshitChanpura** [comment]
@nknize Since Apr 17, Monday will be code-free for `v2.7.0` and there are still 4 issues pending for this META, what should be the next steps for this issue?

**Comment by nknize** [comment]
> @nknize Since Apr 17, Monday will be code-free for `v2.7.0` and there are still 4 issues pending for this META, what should be the next steps for this issue?

I pinged the remaining issues to see if anything needs to be done. If no response then we move forward on the build.

**Comment by Rishikesh1159** [comment]
No Response from the 4 issues pending for this META. Moving forward with build. @nknize can we close this issue?

**Comment by mch2** [comment]
No response, closing.
