### ISSUE TITLE
[Meta] Remote Store Performance Improvement

### ISSUE THREAD

**Issue by linuxpi** [opensearch-project/OpenSearch#7380]
#### Meta issue to keep track of Remote Store Performance improvement tasks

- [x] Explore tag based deletion to avoid delete bottlenecks https://github.com/opensearch-project/OpenSearch/issues/7380#issue-1693451322
- [x] Parallel upload of segment files https://github.com/opensearch-project/OpenSearch/issues/7385
- [x] Fix s3 upload retry flow, currently it fails with IOException("Resetting to invalid mark") https://github.com/opensearch-project/OpenSearch/issues/7387
- [x] During segment upload, metadata and snapshot files are not deleted if upload fails. https://github.com/opensearch-project/OpenSearch/issues/7388
- [x] Too many Translog files to delete after flush. This can happen if a successful flush happens after a while https://github.com/opensearch-project/OpenSearch/issues/7381
- S3 Throttling 
   - Segment https://github.com/opensearch-project/OpenSearch/issues/7389
   - Translog https://github.com/opensearch-project/OpenSearch/issues/7390

**Comment by gbbafna** [comment]
>  Too many Translog files to delete after flush. This can happen if a successful flush happens after a while

This would get tackled in https://github.com/opensearch-project/OpenSearch/issues/7381

**Comment by cwperks** [comment]
@sachinpkale Is this on track for 2.8.0?

**Comment by linuxpi** [comment]
@cwperks please remove 2.8 and add 2.9
