### ISSUE TITLE
[Meta] Remote Store: 2.8.0 - Release Tracking

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#7382]
This meta issue will track remote store feature related tasks that are aimed for OpenSearch 2.8.0 release.
This list is WIP and will be modified as we identify more tasks.

#### Features
 - [x] https://github.com/opensearch-project/OpenSearch/issues/6851
- [x] https://github.com/opensearch-project/OpenSearch/issues/7153

#### Enhancements
- [x] https://github.com/opensearch-project/OpenSearch/issues/7381
- [x] https://github.com/opensearch-project/OpenSearch/issues/5670
- [x] https://github.com/opensearch-project/OpenSearch/issues/5475
- [x] https://github.com/opensearch-project/OpenSearch/issues/4315
- [x] https://github.com/opensearch-project/OpenSearch/issues/7443

#### Bug Fixes
- [x] https://github.com/opensearch-project/OpenSearch/issues/6195
- [x] https://github.com/opensearch-project/OpenSearch/issues/7388
- [x] https://github.com/opensearch-project/OpenSearch/issues/7643
- [x] https://github.com/opensearch-project/OpenSearch/issues/7592
- [x] https://github.com/opensearch-project/OpenSearch/issues/7685
- [x] https://github.com/opensearch-project/OpenSearch/issues/7687
