### ISSUE TITLE
Fix broken links in the repo

### ISSUE THREAD

**Issue by VachaShah** [opensearch-project/OpenSearch#894]
The broken links checker #877 found the following broken links in the files which need to be fixed:

- [x] Errors in plugins/analysis-nori/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/analysis-phonetic/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/analysis-smartcn/licenses/lucene-NOTICE.txt
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))

- [x] Errors in plugins/analysis-stempel/licenses/lucene-NOTICE.txt
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))

- [x] Errors in plugins/ingest-attachment/licenses/fontbox-LICENSE.txt
✗ http://opensource.adobe.com/wiki/display/cmap/Downloads (HTTP status client error (404 Not Found) for url (https://opensource.adobe.com/wiki/display/cmap/Downloads))

- [x] Errors in modules/transport-netty4/licenses/netty-NOTICE.txt
✗ http://viewvc.jboss.org/cgi-bin/viewvc.cgi/jbosscache/experimental/jsr166/

- [x] Errors in plugins/ingest-attachment/licenses/poi-NOTICE.txt
✗ http://eid-applet.googlecode.com/ (HTTP status client error (404 Not Found) for url (http://eid-applet.googlecode.com/))

- [x] Errors in plugins/analysis-stempel/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/transport-nio/licenses/netty-NOTICE.txt
✗ http://viewvc.jboss.org/cgi-bin/viewvc.cgi/jbosscache/experimental/jsr166/

- [x] Errors in plugins/ingest-attachment/licenses/poi-ooxml-NOTICE.txt
✗ http://eid-applet.googlecode.com/ (HTTP status client error (404 Not Found) for url (http://eid-applet.googlecode.com/))

- [x] Errors in client/benchmark/README.md
✗ http://benchmarks.opensearch.org.s3.amazonaws.com/corpora/geonames (HTTP status client error (404 Not Found) for url (http://benchmarks.opensearch.org.s3.amazonaws.com/corpora/geonames))

- [x] Errors in plugins/ingest-attachment/licenses/pdfbox-LICENSE.txt
✗ http://opensource.adobe.com/wiki/display/cmap/Downloads (HTTP status client error (404 Not Found) for url (https://opensource.adobe.com/wiki/display/cmap/Downloads))

- [x] Errors in plugins/ingest-attachment/licenses/poi-scratchpad-LICENSE.txt
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf))
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf))

- [x] Errors in server/licenses/lucene-NOTICE.txt
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))

- [x] Errors in plugins/analysis-ukrainian/licenses/lucene-NOTICE.txt
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))

- [x] Errors in release-notes/opensearch.release-notes-1.0.0-rc1.md
✗ 48720201+meetshah777@users.noreply.github.com (Unreachable mail address: 48720201+meetshah777@users.noreply.github.com)
✗ ketanv3@users.noreply.github.com (Unreachable mail address: ketanv3@users.noreply.github.com)
✗ VachaShah@users.noreply.github.com (Unreachable mail address: VachaShah@users.noreply.github.com)
✗ 81695996+soosinha@users.noreply.github.com (Unreachable mail address: 81695996+soosinha@users.noreply.github.com)

- [x] Errors in plugins/ingest-attachment/licenses/poi-ooxml-schemas-NOTICE.txt
✗ http://eid-applet.googlecode.com/ (HTTP status client error (404 Not Found) for url (http://eid-applet.googlecode.com/))

- [x] Errors in plugins/analysis-kuromoji/licenses/lucene-NOTICE.txt
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))

- [x] Errors in plugins/examples/rest-handler/src/yamlRestTest/resources/rest-api-spec/api/cat.example.json
✗ https://www.opensearch.co/guide/en/opensearch/plugins/current/plugin-authors.html (error sending request for url (https://www.opensearch.co/guide/en/opensearch/plugins/current/plugin-authors.html): error trying to connect: dns error: failed to lookup address information: Name or service not known)

- [x] Errors in plugins/analysis-nori/licenses/lucene-NOTICE.txt
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))

- [x] Errors in plugins/analysis-icu/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/analysis-smartcn/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/ingest-attachment/licenses/poi-ooxml-schemas-LICENSE.txt
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf))
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf))

- [x] Errors in plugins/analysis-phonetic/licenses/lucene-NOTICE.txt
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))

- [x] Errors in plugins/analysis-icu/licenses/lucene-NOTICE.txt
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))

- [x] Errors in plugins/analysis-kuromoji/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in server/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/ingest-attachment/licenses/poi-scratchpad-NOTICE.txt
✗ http://eid-applet.googlecode.com/ (HTTP status client error (404 Not Found) for url (http://eid-applet.googlecode.com/))

- [x] Errors in modules/lang-expression/licenses/lucene-NOTICE.txt
✗ http://project.carrot2.org/license.html (HTTP status client error (404 Not Found) for url (https://github.com/carrot2/carrot2license.html))
✗ http://bitbucket.org/jpbarrette/moman/overview/ (HTTP status client error (404 Not Found) for url (https://bitbucket.org/jpbarrette/moman/overview/))
✗ http://www.eclipse.org/jetty/downloads.php (HTTP status client error (404 Not Found) for url (http://www.eclipse.org/jetty/downloads.php))

- [x] Errors in modules/lang-expression/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

- [x] Errors in plugins/ingest-attachment/licenses/poi-LICENSE.txt
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf))
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf))

- [x] Errors in plugins/ingest-attachment/licenses/poi-ooxml-LICENSE.txt
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Edition%202%20Microsoft%20Patent%20Declaration.pdf))
✗ http://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf (HTTP status client error (404 Not Found) for url (https://www.ecma-international.org/publications/files/ECMA-ST/Ecma%20PATENT/Patent%20statements%20ok/ECMA-376%20Adobe%20Patent%20Declaration.pdf))

- [x] Errors in rest-api-spec/src/main/resources/rest-api-spec/test/README.md
✗ http://snapshot/ (error sending request for url (http://snapshot/): error trying to connect: dns error: failed to lookup address information: Name or service not known)

- [x] Errors in plugins/analysis-ukrainian/licenses/lucene-LICENSE.txt
✗ http://www.unicode.org/Public/PROGRAMS/CVTUTF (HTTP status client error (404 Not Found) for url (http://www.unicode.org/Public/PROGRAMS/CVTUTF))

**Comment by stockholmux** [comment]
@VachaShah We can ignore anything that's a `LICENSE.txt` or `NOTICE.txt` file for now. Some of these projects linked are dead and gone from the internet, so we _could_ append something like 'originally available at', although this is orthogonal to the effort outlined here (and a lower priority).

Could you clean up these `LICENSE.txt` or `NOTICE.txt` links to narrow down the list?

**Comment by VachaShah** [comment]
@stockholmux Thank you for the confirmation! I will update the link checker to exclude the `NOTICE.txt` and `LICENSE.txt` and update the broken links list accordingly.

**Comment by VachaShah** [comment]
@stockholmux I have updated the checker to exclude the `LICENSE.txt` and `NOTICE.txt` links and also excluded the check for email addresses. The task list is now updated with the remaining broken links.

**Comment by VachaShah** [comment]
All links fixed in this PR: #877. Closing this issue.
