### ISSUE TITLE
 [META] Streaming Indexing API

### ISSUE THREAD

**Issue by reta** [opensearch-project/OpenSearch#9065]
**Is your feature request related to a problem? Please describe.**
The meta issue to track the Streaming Indexing API progress

**Describe the solution you'd like**
As outcome of the https://github.com/opensearch-project/OpenSearch/issues/5001, we have outlined the way such steaming support could be integrated into OpenSearch.

- [ ] Introduce new experimental HTTP transport based on Netty 4 and Project Reactor (Reactor Netty)
- [ ] Introduce Project Reactor to OpenSearch core (dependencies)
- [ ] Enhance  `RestAction`s with streaming support
- [ ] Enhance `RestClient` with a new streaming API support
- [ ] Enhance `OpenSearch Java Client` with a new streaming API support

**Describe alternatives you've considered**

**Additional context**

**Comment by dblock** [comment]
@reta pretty great stuff - there's other work on improving client/server performance, how do you see us fit work on Protobuf (@VachaShah) / gRPC?

**Comment by reta** [comment]
> @reta pretty great stuff - there's other work on improving client/server performance, how do you see us fit work on Protobuf (@VachaShah) / gRPC?

Thanks @dblock, the gRPC would definitely benefit from the reactive streaming part. From other side, I assume the gRPC would be uses at node transport layer (at least, initially), so the HTTP reactive layer (as suggested alternative transport)  would benefit enormously from that - we will be having end-to-end reactive processing pipeline.

**Comment by shwetathareja** [comment]
@reta Looking to collaborate on the Streaming API changes and see by when it can make it to OpenSearch release.

**Comment by reta** [comment]
> @reta Looking to collaborate on the Streaming API changes and see by when it can make it to OpenSearch release.

@shwetathareja  that would be great, the first thing is to get this one in https://github.com/opensearch-project/OpenSearch/pull/9672 - the pull requests add new HTTP transport based on Reactor Netty 4 with streaming support, it is well on schedule for `2.12`. What is left there is testing part, since this transport is not default (and experimental), needs some ad-hoc testing.  I should be able to wrap it up this week (the two back to back releases derailed the plans a bit).

Once the transport is there, we could split the work, there are quite a few opportunities for doing that in parallel, thank you.

**Comment by shwetathareja** [comment]
@reta sounds good. I will also go through https://github.com/opensearch-project/OpenSearch/pull/9672 to get better understanding. Lets connect next week around how we can split the remaining work. Looking forward to working together. Thank you!

**Comment by reta** [comment]
> Does the current implementation support bi-directional streaming, I.e. returning responses for each chunk/document?

Just for visibility, yes the implementation support bi-directional streaming, thanks @T-J-L !

**Comment by thomas-long-f3** [comment]
I didn't want to clutter this issue so created a separate one [here](https://github.com/opensearch-project/OpenSearch/issues/16035), but any help would be appreciated 😄

**Comment by ylwu-amzn** [comment]
> Once the transport is there, we could split the work, there are quite a few opportunities for doing that in parallel, thank you.


@reta , any plan to build transport support ?

**Comment by reta** [comment]
> [@reta](https://github.com/reta) , any plan to build transport support ?  

Thanks @ylwu-amzn , there are efforts to bring alternative transports (like https://github.com/opensearch-project/OpenSearch/pull/16962), but AFAIK no one is working on making the native transport streaming capable at the moment.

> Better to release in 3.0 if this will be some breaking change 

Thanks @ylwu-amzn , we were able to deliver the streaming HTTP transport as non-breaking change, I expect this to be the case for node-to-node as well.
