### ISSUE TITLE
[BUG] Update developer guide on how to run spotless task on subprojects

### ISSUE THREAD

**Issue by vrozov** [opensearch-project/OpenSearch#974]
**Describe the bug**
Developer guide suggests to run `./gradlew server:spotlessJavaCheck` as an example for executing it on subprojects, but spotless is not enabled for the server subproject, so it errors out:
```
FAILURE: Build failed with an exception.

* What went wrong:
Task 'spotlessJavaCheck' not found in project ':server'.
```

**Comment by owaiskazi19** [comment]
This is a meta issue to track spotless enabled for all modules.

- [ ] :client:benchmark
- [ ] :client:client-benchmark-noop-api-plugin
- [ ] :client:rest
- [ ] :client:rest-high-level
- [ ] :client:sniffer
- [ ] :client:test
- [ ]  :client:transport
- [ ]  :example-plugins:custom-settings
- [ ]  :example-plugins:custom-significance-heuristic
- [ ]  :example-plugins:custom-suggester
- [ ]  :example-plugins:painless-whitelist
- [ ]  :example-plugins:rescore
- [ ]  :example-plugins:rest-handler
- [ ]  :example-plugins:script-expert-scoring
- [ ]  :libs:opensearch-cli
- [ ]  :libs:opensearch-core
- [ ]  :libs:opensearch-dissect
- [ ]  :libs:opensearch-geo
- [ ]  :libs:opensearch-grok
- [ ]  :libs:opensearch-nio
- [ ]  :libs:opensearch-plugin-classloader
- [ ]  :libs:opensearch-secure-sm
- [ ]  :libs:opensearch-ssl-config
- [ ]  :libs:opensearch-x-content
- [ ]  :modules:aggs-matrix-stats
- [ ]  :modules:analysis-common
- [ ]  :modules:ingest-common
- [ ]  :modules:ingest-geoip
- [ ]  :modules:ingest-user-agent
- [ ]  :modules:lang-expression
- [ ]  :modules:lang-mustache
- [ ]  :modules:lang-painless
- [ ]  :modules:lang-painless:spi
- [ ]  :modules:mapper-extras
- [ ]  :modules:parent-join
- [ ]  :modules:percolator
- [ ]  :modules:rank-eval
- [ ]  :modules:reindex
- [ ]  :modules:repository-url
- [ ]  :modules:systemd
- [ ]  :modules:tasks
- [ ]  :modules:transport-netty4
- [ ]  :plugins:analysis-icu
- [ ]  :plugins:analysis-kuromoji
- [ ]  :plugins:analysis-nori
- [ ]  :plugins:analysis-phonetic
- [ ]  :plugins:analysis-smartcn
- [ ]  :plugins:analysis-stempel
- [ ]  :plugins:analysis-ukrainian
- [ ]  :plugins:discovery-azure-classic
- [ ]  :plugins:discovery-ec2
- [ ]  :plugins:discovery-gce
- [ ]  :plugins:ingest-attachment
- [ ]  :plugins:mapper-annotated-text
- [ ]  :plugins:mapper-murmur3
- [ ]  :plugins:mapper-size
- [ ]  :plugins:repository-azure
- [ ]  :plugins:repository-gcs
- [ ]  :plugins:repository-hdfs
- [ ]  :plugins:repository-s3
- [ ]  :plugins:store-smb
- [ ]  :plugins:transport-nio
- [ ]  :qa:die-with-dignity
- [ ]  :rest-api-spec
- [ ]  :server
- [ ]  :test:fixtures:azure-fixture
- [ ]  :test:fixtures:gcs-fixture
- [ ]  :test:fixtures:hdfs-fixture
- [ ]  :test:fixtures:krb5kdc-fixture
- [ ]  :test:fixtures:minio-fixture
- [ ]  :test:fixtures:old-elasticsearch
- [ ]  :test:fixtures:s3-fixture
- [ ]  :test:framework
- [ ]  :test:logger-usage

**Comment by owaiskazi19** [comment]
All the modules have Spotless as code formatting plugin now. Closing this issue.
