### ISSUE TITLE
[Meta] Remote Store: 2.10.0 - Release Tracking

### ISSUE THREAD

**Issue by sachinpkale** [opensearch-project/OpenSearch#9805]
This meta issue will track remote store feature related tasks that are aimed for OpenSearch 2.10.0 release.
This list is WIP and will be modified as we identify more tasks.

#### Features
- [x] https://github.com/opensearch-project/OpenSearch/issues/9344
- [x] https://github.com/opensearch-project/OpenSearch/issues/8623
- [x] https://github.com/opensearch-project/OpenSearch/issues/8311

#### Enhancements
- [x] https://github.com/opensearch-project/OpenSearch/issues/8395
- [x] https://github.com/opensearch-project/OpenSearch/pull/9168
- [x] https://github.com/opensearch-project/OpenSearch/pull/9393
- [x] https://github.com/opensearch-project/OpenSearch/pull/9454
- [x] https://github.com/opensearch-project/OpenSearch/issues/7228
- [x] https://github.com/opensearch-project/OpenSearch/issues/8483
- [x] https://github.com/opensearch-project/OpenSearch/issues/7722
- [x] https://github.com/opensearch-project/OpenSearch/issues/8311
- [x] https://github.com/opensearch-project/OpenSearch/issues/8770
- [x] https://github.com/opensearch-project/OpenSearch/issues/9249
- [x] https://github.com/opensearch-project/OpenSearch/issues/8717
- [x] https://github.com/opensearch-project/OpenSearch/issues/9266
- [x] https://github.com/opensearch-project/OpenSearch/issues/9574
- [x] https://github.com/opensearch-project/OpenSearch/issues/8834
- [x] https://github.com/opensearch-project/OpenSearch/pull/9448
- [x] https://github.com/opensearch-project/OpenSearch/issues/4315
- [x] https://github.com/opensearch-project/OpenSearch/pull/8792

#### Bug Fixes
- [x] https://github.com/opensearch-project/OpenSearch/issues/8479
- [x] https://github.com/opensearch-project/OpenSearch/issues/8658
- [x] https://github.com/opensearch-project/OpenSearch/issues/8947
- [x] https://github.com/opensearch-project/OpenSearch/issues/7923
- [x] https://github.com/opensearch-project/OpenSearch/issues/9185
- [x] https://github.com/opensearch-project/OpenSearch/issues/9249
- [x] https://github.com/opensearch-project/OpenSearch/issues/8131
- [x] https://github.com/opensearch-project/OpenSearch/issues/9191
- [x] https://github.com/opensearch-project/OpenSearch/issues/9455
- [x] https://github.com/opensearch-project/OpenSearch/issues/9408
- [x] https://github.com/opensearch-project/OpenSearch/issues/7791
